packages:
  - e2e
  - devtools
  - devtools/tools/*
  - devtools/ui

allowBuilds:
  "@playwright/browser-chromium": true
  esbuild: true

minimumReleaseAgeExclude:
  - webanvil@0.0.17
  - skyemu-static@0.0.2
