import { type Direction, type GameMap, type Item, type StoryFlag } from "../harness/game-session"

type Approach = { x: number; y: number; facing: Direction }
type Pickup = { floor: GameMap; kind: "visible" | "hidden"; item: Item; flag: StoryFlag; approach: Approach; target: { x: number; y: number } }
type Door = { floor: GameMap; flag: StoryFlag; approach: Approach; target: { x: number; y: number } }
type Panel = { floor: GameMap; index: number; approach: Approach; destination: GameMap; target: { x: number; y: number } }

export const silphPickups = [
  {"floor": "silph-2f", "kind": "hidden", "item": "ultraBall", "flag": "silph2FUltraBallHiddenReceived", "approach": {"x": 11, "y": 20, "facing": "down"}, "target": {"x": 11, "y": 21}},
  {"floor": "silph-3f", "kind": "visible", "item": "hyperPotion", "flag": "silph3FHyperPotionReceived", "approach": {"x": 8, "y": 11, "facing": "up"}, "target": {"x": 8, "y": 10}},
  {"floor": "silph-3f", "kind": "hidden", "item": "protein", "flag": "silph3FProteinHiddenReceived", "approach": {"x": 34, "y": 19, "facing": "up"}, "target": {"x": 34, "y": 18}},
  {"floor": "silph-4f", "kind": "visible", "item": "maxRevive", "flag": "silph4FMaxReviveReceived", "approach": {"x": 3, "y": 12, "facing": "up"}, "target": {"x": 3, "y": 11}},
  {"floor": "silph-4f", "kind": "visible", "item": "escapeRope", "flag": "silph4FEscapeRopeReceived", "approach": {"x": 4, "y": 13, "facing": "up"}, "target": {"x": 4, "y": 12}},
  {"floor": "silph-4f", "kind": "visible", "item": "fullHeal", "flag": "silph4FFullHealReceived", "approach": {"x": 2, "y": 14, "facing": "up"}, "target": {"x": 2, "y": 13}},
  {"floor": "silph-4f", "kind": "visible", "item": "tmTorment", "flag": "silph4FTm41Received", "approach": {"x": 30, "y": 19, "facing": "up"}, "target": {"x": 30, "y": 18}},
  {"floor": "silph-4f", "kind": "hidden", "item": "iron", "flag": "silph4FIronHiddenReceived", "approach": {"x": 35, "y": 21, "facing": "up"}, "target": {"x": 35, "y": 20}},
  {"floor": "silph-5f", "kind": "visible", "item": "protein", "flag": "silph5FProteinReceived", "approach": {"x": 4, "y": 10, "facing": "up"}, "target": {"x": 4, "y": 9}},
  {"floor": "silph-5f", "kind": "visible", "item": "tmFocusPunch", "flag": "silph5FTm01Received", "approach": {"x": 1, "y": 19, "facing": "up"}, "target": {"x": 1, "y": 18}},
  {"floor": "silph-5f", "kind": "visible", "item": "silphCardKey", "flag": "silphCardKeyReceived", "approach": {"x": 23, "y": 21, "facing": "left"}, "target": {"x": 22, "y": 21}},
  {"floor": "silph-5f", "kind": "hidden", "item": "elixir", "flag": "silph5FElixirHiddenReceived", "approach": {"x": 13, "y": 17, "facing": "up"}, "target": {"x": 13, "y": 16}},
  {"floor": "silph-5f", "kind": "hidden", "item": "ppUp", "flag": "silph5FPpUpHiddenReceived", "approach": {"x": 32, "y": 10, "facing": "up"}, "target": {"x": 32, "y": 9}},
  {"floor": "silph-6f", "kind": "visible", "item": "hpUp", "flag": "silph6FHpUpReceived", "approach": {"x": 3, "y": 14, "facing": "left"}, "target": {"x": 2, "y": 14}},
  {"floor": "silph-6f", "kind": "visible", "item": "xSpecial", "flag": "silph6FXSpecialReceived", "approach": {"x": 1, "y": 18, "facing": "up"}, "target": {"x": 1, "y": 17}},
  {"floor": "silph-6f", "kind": "hidden", "item": "carbos", "flag": "silph6FCarbosHiddenReceived", "approach": {"x": 1, "y": 9, "facing": "up"}, "target": {"x": 1, "y": 8}},
  {"floor": "silph-7f", "kind": "visible", "item": "calcium", "flag": "silph7FCalciumReceived", "approach": {"x": 0, "y": 13, "facing": "up"}, "target": {"x": 0, "y": 12}},
  {"floor": "silph-7f", "kind": "visible", "item": "tmBulkUp", "flag": "silph7FTm08Received", "approach": {"x": 30, "y": 12, "facing": "up"}, "target": {"x": 30, "y": 11}},
  {"floor": "silph-7f", "kind": "hidden", "item": "zinc", "flag": "silph7FZincHiddenReceived", "approach": {"x": 22, "y": 12, "facing": "up"}, "target": {"x": 22, "y": 11}},
  {"floor": "silph-8f", "kind": "visible", "item": "iron", "flag": "silph8FIronReceived", "approach": {"x": 24, "y": 9, "facing": "up"}, "target": {"x": 24, "y": 8}},
  {"floor": "silph-8f", "kind": "hidden", "item": "nugget", "flag": "silph8FNuggetHiddenReceived", "approach": {"x": 29, "y": 11, "facing": "up"}, "target": {"x": 29, "y": 10}},
  {"floor": "silph-9f", "kind": "hidden", "item": "maxPotion", "flag": "silph9FMaxPotionHiddenReceived", "approach": {"x": 11, "y": 15, "facing": "up"}, "target": {"x": 11, "y": 14}},
  {"floor": "silph-9f", "kind": "hidden", "item": "calcium", "flag": "silph9FCalciumHiddenReceived", "approach": {"x": 5, "y": 9, "facing": "up"}, "target": {"x": 5, "y": 8}},
  {"floor": "silph-10f", "kind": "visible", "item": "carbos", "flag": "silph10FCarbosReceived", "approach": {"x": 6, "y": 15, "facing": "left"}, "target": {"x": 5, "y": 15}},
  {"floor": "silph-10f", "kind": "visible", "item": "ultraBall", "flag": "silph10FUltraBallReceived", "approach": {"x": 1, "y": 15, "facing": "right"}, "target": {"x": 2, "y": 15}},
  {"floor": "silph-10f", "kind": "visible", "item": "rareCandy", "flag": "silph10FRareCandyReceived", "approach": {"x": 3, "y": 18, "facing": "up"}, "target": {"x": 3, "y": 17}},
  {"floor": "silph-10f", "kind": "hidden", "item": "hpUp", "flag": "silph10FHpUpHiddenReceived", "approach": {"x": 9, "y": 10, "facing": "up"}, "target": {"x": 9, "y": 9}},
  {"floor": "silph-11f", "kind": "visible", "item": "zinc", "flag": "silph11FZincReceived", "approach": {"x": 16, "y": 19, "facing": "up"}, "target": {"x": 16, "y": 18}},
  {"floor": "silph-11f", "kind": "hidden", "item": "revive", "flag": "silph11FReviveHiddenReceived", "approach": {"x": 10, "y": 19, "facing": "up"}, "target": {"x": 10, "y": 18}},
] as const satisfies readonly Pickup[]

export const silphDoors = [
  {"floor": "silph-2f", "flag": "silph2FDoor1", "approach": {"x": 5, "y": 7, "facing": "down"}, "target": {"x": 5, "y": 8}},
  {"floor": "silph-2f", "flag": "silph2FDoor2", "approach": {"x": 5, "y": 14, "facing": "down"}, "target": {"x": 5, "y": 15}},
  {"floor": "silph-3f", "flag": "silph3FDoor1", "approach": {"x": 11, "y": 12, "facing": "left"}, "target": {"x": 10, "y": 12}},
  {"floor": "silph-3f", "flag": "silph3FDoor2", "approach": {"x": 22, "y": 12, "facing": "left"}, "target": {"x": 21, "y": 12}},
  {"floor": "silph-4f", "flag": "silph4FDoor1", "approach": {"x": 3, "y": 15, "facing": "down"}, "target": {"x": 3, "y": 16}},
  {"floor": "silph-4f", "flag": "silph4FDoor2", "approach": {"x": 15, "y": 10, "facing": "down"}, "target": {"x": 15, "y": 11}},
  {"floor": "silph-5f", "flag": "silph5FDoor1", "approach": {"x": 9, "y": 9, "facing": "left"}, "target": {"x": 8, "y": 9}},
  {"floor": "silph-5f", "flag": "silph5FDoor2", "approach": {"x": 9, "y": 18, "facing": "left"}, "target": {"x": 8, "y": 18}},
  {"floor": "silph-5f", "flag": "silph5FDoor3", "approach": {"x": 20, "y": 13, "facing": "left"}, "target": {"x": 19, "y": 13}},
  {"floor": "silph-6f", "flag": "silph6FDoor", "approach": {"x": 7, "y": 15, "facing": "left"}, "target": {"x": 6, "y": 15}},
  {"floor": "silph-7f", "flag": "silph7FDoor1", "approach": {"x": 11, "y": 7, "facing": "down"}, "target": {"x": 11, "y": 8}},
  {"floor": "silph-7f", "flag": "silph7FDoor2", "approach": {"x": 24, "y": 6, "facing": "down"}, "target": {"x": 24, "y": 7}},
  {"floor": "silph-7f", "flag": "silph7FDoor3", "approach": {"x": 25, "y": 12, "facing": "down"}, "target": {"x": 25, "y": 13}},
  {"floor": "silph-8f", "flag": "silph8FDoor", "approach": {"x": 7, "y": 10, "facing": "left"}, "target": {"x": 6, "y": 10}},
  {"floor": "silph-9f", "flag": "silph9FDoor1", "approach": {"x": 4, "y": 10, "facing": "left"}, "target": {"x": 3, "y": 10}},
  {"floor": "silph-9f", "flag": "silph9FDoor2", "approach": {"x": 14, "y": 16, "facing": "left"}, "target": {"x": 13, "y": 16}},
  {"floor": "silph-9f", "flag": "silph9FDoor3", "approach": {"x": 21, "y": 5, "facing": "down"}, "target": {"x": 21, "y": 6}},
  {"floor": "silph-9f", "flag": "silph9FDoor4", "approach": {"x": 21, "y": 14, "facing": "up"}, "target": {"x": 21, "y": 13}},
  {"floor": "silph-10f", "flag": "silph10FDoor", "approach": {"x": 12, "y": 10, "facing": "down"}, "target": {"x": 12, "y": 11}},
  {"floor": "silph-11f", "flag": "silph11FDoor", "approach": {"x": 5, "y": 15, "facing": "down"}, "target": {"x": 5, "y": 16}},
] as const satisfies readonly Door[]

export const silphPanels = [
  {"floor": "silph-2f", "index": 1, "approach": {"x": 2, "y": 7, "facing": "up"}, "destination": "silph-3f", "target": {"x": 33, "y": 5}},
  {"floor": "silph-2f", "index": 2, "approach": {"x": 15, "y": 7, "facing": "up"}, "destination": "silph-8f", "target": {"x": 2, "y": 17}},
  {"floor": "silph-2f", "index": 4, "approach": {"x": 7, "y": 20, "facing": "up"}, "destination": "silph-6f", "target": {"x": 29, "y": 5}},
  {"floor": "silph-2f", "index": 5, "approach": {"x": 33, "y": 20, "facing": "up"}, "destination": "silph-8f", "target": {"x": 10, "y": 6}},
  {"floor": "silph-3f", "index": 1, "approach": {"x": 4, "y": 7, "facing": "up"}, "destination": "silph-5f", "target": {"x": 15, "y": 7}},
  {"floor": "silph-3f", "index": 2, "approach": {"x": 13, "y": 15, "facing": "up"}, "destination": "silph-7f", "target": {"x": 5, "y": 4}},
  {"floor": "silph-3f", "index": 4, "approach": {"x": 2, "y": 15, "facing": "up"}, "destination": "silph-9f", "target": {"x": 9, "y": 4}},
  {"floor": "silph-3f", "index": 5, "approach": {"x": 3, "y": 21, "facing": "up"}, "destination": "silph-5f", "target": {"x": 2, "y": 20}},
  {"floor": "silph-3f", "index": 6, "approach": {"x": 29, "y": 15, "facing": "up"}, "destination": "silph-3f", "target": {"x": 32, "y": 20}},
  {"floor": "silph-3f", "index": 7, "approach": {"x": 32, "y": 21, "facing": "up"}, "destination": "silph-3f", "target": {"x": 29, "y": 14}},
  {"floor": "silph-3f", "index": 8, "approach": {"x": 33, "y": 6, "facing": "up"}, "destination": "silph-2f", "target": {"x": 2, "y": 6}},
  {"floor": "silph-4f", "index": 1, "approach": {"x": 18, "y": 7, "facing": "up"}, "destination": "silph-6f", "target": {"x": 2, "y": 6}},
  {"floor": "silph-4f", "index": 3, "approach": {"x": 12, "y": 10, "facing": "up"}, "destination": "silph-10f", "target": {"x": 10, "y": 14}},
  {"floor": "silph-4f", "index": 4, "approach": {"x": 2, "y": 21, "facing": "up"}, "destination": "silph-10f", "target": {"x": 14, "y": 17}},
  {"floor": "silph-4f", "index": 5, "approach": {"x": 18, "y": 15, "facing": "up"}, "destination": "silph-10f", "target": {"x": 14, "y": 9}},
  {"floor": "silph-5f", "index": 1, "approach": {"x": 15, "y": 8, "facing": "up"}, "destination": "silph-3f", "target": {"x": 4, "y": 6}},
  {"floor": "silph-5f", "index": 3, "approach": {"x": 10, "y": 21, "facing": "up"}, "destination": "silph-9f", "target": {"x": 22, "y": 18}},
  {"floor": "silph-5f", "index": 4, "approach": {"x": 2, "y": 21, "facing": "up"}, "destination": "silph-3f", "target": {"x": 3, "y": 20}},
  {"floor": "silph-5f", "index": 5, "approach": {"x": 33, "y": 6, "facing": "up"}, "destination": "silph-7f", "target": {"x": 25, "y": 17}},
  {"floor": "silph-6f", "index": 1, "approach": {"x": 29, "y": 6, "facing": "up"}, "destination": "silph-2f", "target": {"x": 7, "y": 19}},
  {"floor": "silph-6f", "index": 3, "approach": {"x": 2, "y": 7, "facing": "up"}, "destination": "silph-4f", "target": {"x": 18, "y": 6}},
  {"floor": "silph-7f", "index": 1, "approach": {"x": 5, "y": 9, "facing": "up"}, "destination": "silph-11f", "target": {"x": 2, "y": 5}},
  {"floor": "silph-7f", "index": 2, "approach": {"x": 25, "y": 18, "facing": "up"}, "destination": "silph-5f", "target": {"x": 33, "y": 5}},
  {"floor": "silph-7f", "index": 4, "approach": {"x": 5, "y": 5, "facing": "up"}, "destination": "silph-3f", "target": {"x": 13, "y": 14}},
  {"floor": "silph-8f", "index": 1, "approach": {"x": 10, "y": 10, "facing": "right"}, "destination": "silph-8f", "target": {"x": 2, "y": 12}},
  {"floor": "silph-8f", "index": 2, "approach": {"x": 10, "y": 7, "facing": "up"}, "destination": "silph-2f", "target": {"x": 33, "y": 19}},
  {"floor": "silph-8f", "index": 4, "approach": {"x": 2, "y": 13, "facing": "up"}, "destination": "silph-8f", "target": {"x": 11, "y": 10}},
  {"floor": "silph-8f", "index": 5, "approach": {"x": 2, "y": 18, "facing": "up"}, "destination": "silph-2f", "target": {"x": 15, "y": 6}},
  {"floor": "silph-9f", "index": 1, "approach": {"x": 21, "y": 18, "facing": "right"}, "destination": "silph-5f", "target": {"x": 10, "y": 20}},
  {"floor": "silph-9f", "index": 2, "approach": {"x": 9, "y": 5, "facing": "up"}, "destination": "silph-3f", "target": {"x": 2, "y": 14}},
  {"floor": "silph-10f", "index": 1, "approach": {"x": 10, "y": 15, "facing": "up"}, "destination": "silph-4f", "target": {"x": 12, "y": 9}},
  {"floor": "silph-10f", "index": 2, "approach": {"x": 14, "y": 10, "facing": "up"}, "destination": "silph-4f", "target": {"x": 18, "y": 14}},
  {"floor": "silph-10f", "index": 4, "approach": {"x": 14, "y": 18, "facing": "up"}, "destination": "silph-4f", "target": {"x": 2, "y": 20}},
  {"floor": "silph-11f", "index": 1, "approach": {"x": 2, "y": 6, "facing": "up"}, "destination": "silph-7f", "target": {"x": 5, "y": 8}},
] as const satisfies readonly Panel[]
