#!/usr/bin/env python3
"""Generate the selected FRLG Celadon Hideout parties for Wayfarer."""
from __future__ import annotations

import argparse
import importlib.util
import re
import subprocess
import tempfile
from pathlib import Path

GAME = Path(__file__).resolve().parents[2]
OUTPUT = GAME / "src/data/trainers_wayfarer_celadon_hideout.h"
SOURCES = [*(f"TRAINER_TEAM_ROCKET_GRUNT_{i}" for i in range(7, 19)), "TRAINER_BOSS_GIOVANNI"]
TARGETS = [*(f"TRAINER_CELADON_HIDEOUT_GRUNT_{i}_HNS" for i in range(7, 19)),
           "TRAINER_CELADON_HIDEOUT_GIOVANNI_HNS"]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    with tempfile.TemporaryDirectory(prefix="wayfarer-hideout-") as directory:
        directory = Path(directory)
        binary, generated = directory / "trainerproc", directory / "trainers.h"
        subprocess.run(["cc", "-O2", str(GAME / "tools/trainerproc/main.c"), "-o", str(binary)], check=True)
        source = subprocess.run(
            ["cpp", "-traditional-cpp", "-P", "-DPOKEMON_WAYFARER", "-DPOKEMON_HNS",
             "-DIS_WAYFARER=1", "-DIS_HNS=1", "-DIS_FRLG=0", "-DIS_EMERALD=0",
             "-I", str(GAME / "include"), str(GAME / "src/data/trainers_frlg.party")],
            text=True, capture_output=True, check=True,
        ).stdout
        subprocess.run([str(binary), "-i", "src/data/trainers_frlg.party", "-o", str(generated), "-"],
                       input=source, text=True, capture_output=True, check=True)
        compiled = generated.read_text()
    spec = importlib.util.spec_from_file_location("scaling", GAME / "tools/trainer_scaling/generate.py")
    module = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    spec.loader.exec_module(module)
    records = []
    for source_id, target_id in zip(SOURCES, TARGETS):
        match = re.search(rf"\[{re.escape(source_id)}\]\s*=\s*\{{", compiled)
        if not match:
            raise ValueError(f"missing FRLG source party {source_id}")
        _, end = module.balanced(compiled, match.end() - 1)
        record = re.sub(r"(?m)^#line .*\n", "", compiled[match.start():end])
        records.append(record.replace(f"[{source_id}]", f"[{target_id}]", 1) + ",")
    text = "// Generated by tools/wayfarer_celadon_hideout_trainers/generate.py; do not edit.\n\n"
    text += "\n\n".join(records) + "\n"
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text() != text:
            raise ValueError(f"stale Hideout trainer roster: {OUTPUT}")
    else:
        OUTPUT.write_text(text)


if __name__ == "__main__":
    main()
