"""Export walkability grids for e2e journeys that walk real routes.

The SkyEmu suite never reads game/ at runtime, so journeys that need to path
around map geometry use this checked-in snapshot instead. Regenerate it after
changing a listed map's layout, then commit the result:

    python3 game/tools/e2e_collision/export.py > e2e/src/fixtures/kanto-opening-collision.ts
"""

import json
import re
import struct
from pathlib import Path

GAME = Path(__file__).resolve().parents[2]
MAPS = {
    "reds-house-2f": "PalletTown_RedsHouse_2F_hns",
    "reds-house-1f": "PalletTown_RedsHouse_1F_hns",
    "blues-house": "PalletTown_House2_hns",
    "pallet-town": "PalletTown_hns",
    "oak-lab": "PalletTown_Lab_hns",
    "route-1": "Route1_hns",
    "viridian-city": "ViridianCity_hns",
    "viridian-mart": "ViridianCity_Mart_hns",
}
PRIMARY_METATILES = 640  # HNS layouts; see include/fieldmap.h
LEDGES = {0x38: ">", 0x39: "<", 0x3A: "^", 0x3B: "v"}  # MB_JUMP_EAST..SOUTH
# MB_IMPASSABLE_* sides: a step is refused out of a tile through a blocked side
# and into a tile through its blocked side.
SIDES = {
    0x30: "e", 0x31: "w", 0x32: "n", 0x33: "s",
    0x34: "1", 0x35: "2", 0x36: "3", 0x37: "4",  # NE, NW, SE, SW
    0xC0: "|", 0xC1: "=",  # north and south, west and east
}

layouts = {
    layout["id"]: layout
    for layout in json.loads((GAME / "data/layouts/layouts.json").read_text())["layouts"]
    if "id" in layout
}
headers = (GAME / "src/data/tilesets/headers.h").read_text()
metatiles = (GAME / "src/data/tilesets/metatiles.h").read_text()


def attributes(tileset: str) -> tuple[int, ...]:
    symbol = re.search(
        rf"const struct Tileset {tileset} =\s*\{{.*?metatileAttributes = (\w+)", headers, re.S
    ).group(1)
    path = re.search(rf'{symbol}\[\] = INCBIN_U16\("([^"]+)"\)', metatiles).group(1)
    data = (GAME / path).read_bytes()
    return struct.unpack(f"<{len(data) // 2}H", data)


def grid(map_dir: str) -> list[str]:
    header = json.loads((GAME / f"data/maps/{map_dir}/map.json").read_text())
    layout = layouts[header["layout"]]
    warps = {(warp["x"], warp["y"]) for warp in header.get("warp_events", [])}
    width, height = layout["width"], layout["height"]
    blocks = (GAME / layout["blockdata_filepath"]).read_bytes()
    primary = attributes(layout["primary_tileset"])
    secondary = attributes(layout["secondary_tileset"])
    rows = []
    for y in range(height):
        row = ""
        for x in range(width):
            block = struct.unpack_from("<H", blocks, 2 * (y * width + x))[0]
            metatile = block & 0x3FF
            behavior = (
                primary[metatile]
                if metatile < PRIMARY_METATILES
                else secondary[metatile - PRIMARY_METATILES]
            ) & 0xFF
            collision, elevation = (block >> 10) & 3, block >> 12
            # Ledges carry the collision bit; their behavior still allows a jump.
            if (x, y) in warps:
                row += "@"
            elif behavior in LEDGES:
                row += LEDGES[behavior]
            elif behavior in SIDES and not collision and elevation != 1:
                row += SIDES[behavior]
            elif collision:
                row += "#"
            elif elevation == 1:
                row += "~"
            else:
                row += "."
        rows.append(row)
    return rows


print("// Generated by game/tools/e2e_collision/export.py; do not edit by hand.")
print("// '.' walkable, '#' blocked, '~' water, '^v<>' one-way ledges, '@' warp;")
print("// 'nswe' / '1234' (NE NW SE SW) / '|' (N+S) / '=' (W+E) walkable with blocked sides.")
print("export const kantoOpeningCollision = {")
for name, map_dir in MAPS.items():
    print(f'  "{name}": [')
    for row in grid(map_dir):
        print(f'    "{row}",')
    print("  ],")
print("} as const")
