// Generated by tools/wayfarer_story_encounters/generate.py.
// Only reviewed callers in ordinary.json authorize field loss return.
#if IS_WAYFARER
extern const u8 EventScript_WayfarerStoryLossRetreat[];
extern const u8 AbandonedShip_Corridors_1F_EventScript_Charlie[];
extern const u8 AbandonedShip_Corridors_B1F_EventScript_Duncan[];
extern const u8 AbandonedShip_Rooms2_1F_EventScript_Dan[];
extern const u8 AbandonedShip_Rooms2_1F_EventScript_DanRematch[];
extern const u8 AbandonedShip_Rooms2_1F_EventScript_Garrison[];
extern const u8 AbandonedShip_Rooms2_1F_EventScript_Jani[];
extern const u8 AbandonedShip_Rooms2_1F_EventScript_Kira[];
extern const u8 AbandonedShip_Rooms2_1F_EventScript_KiraRematch[];
extern const u8 AbandonedShip_Rooms_1F_EventScript_Demetrius[];
extern const u8 AbandonedShip_Rooms_1F_EventScript_Thalia[];
extern const u8 AbandonedShip_Rooms_1F_EventScript_ThaliaRematch[];
extern const u8 Alola_AkalaCave_TrainerBattleCamper[];
extern const u8 Alola_AkalaCave_TrainerBattleHiker[];
extern const u8 Alola_AkalaCave_TrainerBattlePicnicker[];
extern const u8 Alola_AkalaForest_TrainerBattleBugCatcher1[];
extern const u8 Alola_AkalaForest_TrainerBattleBugCatcher2[];
extern const u8 Alola_Akala_TrainerBattleCamper[];
extern const u8 Alola_Akala_TrainerBattleHiker[];
extern const u8 Alola_Akala_TrainerBattlePicnicker[];
extern const u8 Alola_Akala_TrainerBattleSwimmerLand[];
extern const u8 Alola_Akala_TrainerBattleSwimmerWater[];
extern const u8 Alola_Akala_TrainerBattleSwimmerWaterM[];
extern const u8 Alola_MelemeleSea_TrainerBattleSwimmer[];
extern const u8 Alola_Melemele_TrainerBattleSwimmer[];
extern const u8 Alola_Poni_TrainerBattleSwimmer1[];
extern const u8 Alola_Poni_TrainerBattleSwimmer2[];
extern const u8 Alola_Ulaula_TrainerBattleCooltrainer[];
extern const u8 Alola_Ulaula_TrainerBattleHiker[];
extern const u8 Alola_Ulaula_TrainerBattlePicnicker[];
extern const u8 Alola_Ulaula_TrainerBattleYoungster[];
extern const u8 AquaHideout_1F_EventScript_Grunt1[];
extern const u8 AquaHideout_B1F_EventScript_Grunt2[];
extern const u8 AquaHideout_B1F_EventScript_Grunt3[];
extern const u8 AquaHideout_B1F_EventScript_Grunt5[];
extern const u8 AquaHideout_B1F_EventScript_Grunt7[];
extern const u8 AquaHideout_B2F_EventScript_Grunt4[];
extern const u8 AquaHideout_B2F_EventScript_Grunt6[];
extern const u8 AquaHideout_B2F_EventScript_Grunt8[];
extern const u8 BurnedTower_1F_EventScript_Nard[];
extern const u8 BurnedTower_1F_EventScript_Richardo[];
extern const u8 DragonsDen_Cavern_EventScript_Cara[];
extern const u8 DragonsDen_Cavern_EventScript_Darin[];
extern const u8 DragonsDen_Cavern_EventScript_TwinLea[];
extern const u8 DragonsDen_Cavern_EventScript_TwinPia[];
extern const u8 GabbyAndTy_EventScript_GabbyBattle1[];
extern const u8 GabbyAndTy_EventScript_GabbyBattle2[];
extern const u8 GabbyAndTy_EventScript_GabbyBattle3[];
extern const u8 GabbyAndTy_EventScript_GabbyBattle4[];
extern const u8 GabbyAndTy_EventScript_GabbyBattle5[];
extern const u8 GabbyAndTy_EventScript_GabbyBattle6[];
extern const u8 GabbyAndTy_EventScript_TyBattle1[];
extern const u8 GabbyAndTy_EventScript_TyBattle2[];
extern const u8 GabbyAndTy_EventScript_TyBattle3[];
extern const u8 GabbyAndTy_EventScript_TyBattle4[];
extern const u8 GabbyAndTy_EventScript_TyBattle5[];
extern const u8 GabbyAndTy_EventScript_TyBattle6[];
extern const u8 GoldenrodCity_RadioTower_4F4_EventScript_Scientist[];
extern const u8 GoldenrodCity_UndergroundStorage_EventScript_Eto[];
extern const u8 GoldenrodCity_UndergroundStorage_EventScript_Grunt12[];
extern const u8 GoldenrodCity_UndergroundStorage_EventScript_Grunt19[];
extern const u8 GoldenrodCity_UndergroundSwitches_EventScript_Duncan[];
extern const u8 GoldenrodCity_UndergroundSwitches_EventScript_Eddie[];
extern const u8 GoldenrodCity_UndergroundSwitches_EventScript_Grunt10[];
extern const u8 GoldenrodCity_UndergroundSwitches_EventScript_Grunt11[];
extern const u8 GoldenrodCity_UndergroundSwitches_EventScript_Grunt20[];
extern const u8 GoldenrodCity_UndergroundSwitches_EventScript_Grunt27[];
extern const u8 GoldenrodRaidoTower2_EventScript_Grunt3[];
extern const u8 GoldenrodRaidoTower2_EventScript_Grunt4[];
extern const u8 GoldenrodRaidoTower2_EventScript_Grunt5[];
extern const u8 GoldenrodRaidoTower2_EventScript_GruntF2[];
extern const u8 GoldenrodRaidoTower3_EventScript_Grunt6[];
extern const u8 GoldenrodRaidoTower3_EventScript_Grunt7[];
extern const u8 GoldenrodRaidoTower3_EventScript_Grunt8[];
extern const u8 GoldenrodRaidoTower3_EventScript_Scientist[];
extern const u8 GoldenrodRaidoTower4_EventScript_Grunt28[];
extern const u8 GoldenrodRaidoTower4_EventScript_Grunt9[];
extern const u8 GoldenrodUnderground_EventScript_Donald[];
extern const u8 GoldenrodUnderground_EventScript_Eric[];
extern const u8 GoldenrodUnderground_EventScript_Issac[];
extern const u8 GoldenrodUnderground_EventScript_Teru[];
extern const u8 IlexForest_EventScript_BugcatcherWayne[];
extern const u8 JaggedPass_EventScript_Autumn[];
extern const u8 JaggedPass_EventScript_Diana[];
extern const u8 JaggedPass_EventScript_DianaRematch[];
extern const u8 JaggedPass_EventScript_Eric[];
extern const u8 JaggedPass_EventScript_Ethan[];
extern const u8 JaggedPass_EventScript_EthanRematch[];
extern const u8 JaggedPass_EventScript_Julio[];
extern const u8 LakeOfRage_EventScript_Aaron[];
extern const u8 LakeOfRage_EventScript_Andre[];
extern const u8 LakeOfRage_EventScript_Lois[];
extern const u8 LakeOfRage_EventScript_Raymond[];
extern const u8 MagmaHideout_1F_EventScript_Grunt1[];
extern const u8 MagmaHideout_1F_EventScript_Grunt2[];
extern const u8 MagmaHideout_2F_1R_EventScript_Grunt14[];
extern const u8 MagmaHideout_2F_1R_EventScript_Grunt3[];
extern const u8 MagmaHideout_2F_1R_EventScript_Grunt4[];
extern const u8 MagmaHideout_2F_1R_EventScript_Grunt5[];
extern const u8 MagmaHideout_2F_2R_EventScript_Grunt15[];
extern const u8 MagmaHideout_2F_2R_EventScript_Grunt6[];
extern const u8 MagmaHideout_2F_2R_EventScript_Grunt7[];
extern const u8 MagmaHideout_2F_2R_EventScript_Grunt8[];
extern const u8 MagmaHideout_3F_1R_EventScript_Grunt16[];
extern const u8 MagmaHideout_3F_1R_EventScript_Grunt9[];
extern const u8 MagmaHideout_3F_2R_EventScript_Grunt10[];
extern const u8 MagmaHideout_4F_EventScript_Grunt11[];
extern const u8 MagmaHideout_4F_EventScript_Grunt12[];
extern const u8 MagmaHideout_4F_EventScript_Grunt13[];
extern const u8 MagmaHideout_4F_EventScript_Tabitha[];
extern const u8 MeteorFalls_1F_2R_EventScript_Jay[];
extern const u8 MeteorFalls_1F_2R_EventScript_John[];
extern const u8 MeteorFalls_1F_2R_EventScript_Nicolas[];
extern const u8 MeteorFalls_1F_2R_EventScript_RematchJay[];
extern const u8 MeteorFalls_1F_2R_EventScript_RematchJohn[];
extern const u8 MeteorFalls_1F_2R_EventScript_RematchNicolas[];
extern const u8 MossdeepCity_SpaceCenter_1F_EventScript_Grunt1[];
extern const u8 MossdeepCity_SpaceCenter_1F_EventScript_Grunt3[];
extern const u8 MossdeepCity_SpaceCenter_1F_EventScript_Grunt4[];
extern const u8 MtChimney_EventScript_Grunt1[];
extern const u8 MtChimney_EventScript_Grunt2[];
extern const u8 MtChimney_EventScript_Melissa[];
extern const u8 MtChimney_EventScript_RematchShelby[];
extern const u8 MtChimney_EventScript_Sawyer[];
extern const u8 MtChimney_EventScript_SawyerRematch[];
extern const u8 MtChimney_EventScript_Sheila[];
extern const u8 MtChimney_EventScript_Shelby[];
extern const u8 MtChimney_EventScript_Shirley[];
extern const u8 MtChimney_EventScript_Tabitha[];
extern const u8 MtMortar_1F_North_EventScript_Markus[];
extern const u8 MtMortar_1F_North_EventScript_Miller[];
extern const u8 MtMortar_2F_EventScript_Nerd[];
extern const u8 MtPyre_2F_EventScript_Dez[];
extern const u8 MtPyre_2F_EventScript_Leah[];
extern const u8 MtPyre_2F_EventScript_Luke[];
extern const u8 MtPyre_2F_EventScript_Mark[];
extern const u8 MtPyre_2F_EventScript_Zander[];
extern const u8 MtPyre_3F_EventScript_Gabrielle[];
extern const u8 MtPyre_3F_EventScript_Kayla[];
extern const u8 MtPyre_3F_EventScript_RematchGabrielle[];
extern const u8 MtPyre_3F_EventScript_William[];
extern const u8 MtPyre_4F_EventScript_Tasha[];
extern const u8 MtPyre_5F_EventScript_Atsushi[];
extern const u8 MtPyre_6F_EventScript_Cedric[];
extern const u8 MtPyre_6F_EventScript_RematchValerie[];
extern const u8 MtPyre_6F_EventScript_Valerie[];
extern const u8 MtPyre_Summit_EventScript_Grunt1[];
extern const u8 MtPyre_Summit_EventScript_Grunt2[];
extern const u8 MtPyre_Summit_EventScript_Grunt3[];
extern const u8 MtPyre_Summit_EventScript_Grunt4[];
extern const u8 NationalPark_Normal_EventScript_Beverly[];
extern const u8 NationalPark_Normal_EventScript_Jack[];
extern const u8 NationalPark_Normal_EventScript_Krise[];
extern const u8 NationalPark_Normal_EventScript_RematchBeverly[];
extern const u8 NationalPark_Normal_EventScript_RematchJack[];
extern const u8 NationalPark_Normal_EventScript_William[];
extern const u8 OlivineLighthouse_EventScript_BirdKeeperDenis[];
extern const u8 OlivineLighthouse_EventScript_BirdKeeperTheo[];
extern const u8 OlivineLighthouse_EventScript_GentlemanAlfred[];
extern const u8 OlivineLighthouse_EventScript_GentlemanPreston[];
extern const u8 OlivineLighthouse_EventScript_Huey[];
extern const u8 OlivineLighthouse_EventScript_LassConnie[];
extern const u8 OlivineLighthouse_EventScript_RematchHuey[];
extern const u8 OlivineLighthouse_EventScript_SailorErnest[];
extern const u8 OlivineLighthouse_EventScript_SailorKent[];
extern const u8 OlivineLighthouse_EventScript_SailorTerrell[];
extern const u8 PetalburgWoods_EventScript_James[];
extern const u8 PetalburgWoods_EventScript_JamesRematch[];
extern const u8 PetalburgWoods_EventScript_Lyle[];
extern const u8 RocketHideout_B1F_EventScript_Rocket16[];
extern const u8 RocketHideout_B1F_EventScript_TrainerJed[];
extern const u8 RocketHideout_B2F_EventScript_Grunt14[];
extern const u8 RocketHideout_B2F_EventScript_Grunt15[];
extern const u8 RocketHideout_B2F_EventScript_Grunt16[];
extern const u8 RocketHideout_B3F_EventScript_Mitch[];
extern const u8 RocketHideout_B3F_EventScript_Ross[];
extern const u8 Route102_EventScript_Allen[];
extern const u8 Route102_EventScript_AmyRematch[];
extern const u8 Route102_EventScript_Calvin[];
extern const u8 Route102_EventScript_CalvinRematch[];
extern const u8 Route102_EventScript_LivRematch[];
extern const u8 Route102_EventScript_Rick[];
extern const u8 Route102_EventScript_Tiana[];
extern const u8 Route103_EventScript_Amy[];
extern const u8 Route103_EventScript_Andrew[];
extern const u8 Route103_EventScript_Daisy[];
extern const u8 Route103_EventScript_Isabelle[];
extern const u8 Route103_EventScript_Liv[];
extern const u8 Route103_EventScript_Marcos[];
extern const u8 Route103_EventScript_Miguel[];
extern const u8 Route103_EventScript_MiguelRematch[];
extern const u8 Route103_EventScript_Pete[];
extern const u8 Route103_EventScript_Rhett[];
extern const u8 Route104_EventScript_Billy[];
extern const u8 Route104_EventScript_Cindy[];
extern const u8 Route104_EventScript_Darian[];
extern const u8 Route104_EventScript_Gina[];
extern const u8 Route104_EventScript_Haley[];
extern const u8 Route104_EventScript_Ivan[];
extern const u8 Route104_EventScript_Mia[];
extern const u8 Route104_EventScript_RematchCindy[];
extern const u8 Route104_EventScript_RematchHaley[];
extern const u8 Route104_EventScript_RematchWinston[];
extern const u8 Route104_EventScript_Winston[];
extern const u8 Route105_EventScript_Andres[];
extern const u8 Route105_EventScript_AndresRematch[];
extern const u8 Route105_EventScript_Beverly[];
extern const u8 Route105_EventScript_Dominik[];
extern const u8 Route105_EventScript_Foster[];
extern const u8 Route105_EventScript_Imani[];
extern const u8 Route105_EventScript_Josue[];
extern const u8 Route105_EventScript_Luis[];
extern const u8 Route106_EventScript_Douglas[];
extern const u8 Route106_EventScript_Elliot[];
extern const u8 Route106_EventScript_ElliotRematch[];
extern const u8 Route106_EventScript_Kyla[];
extern const u8 Route106_EventScript_Ned[];
extern const u8 Route107_EventScript_Beth[];
extern const u8 Route107_EventScript_Camron[];
extern const u8 Route107_EventScript_Darrin[];
extern const u8 Route107_EventScript_Denise[];
extern const u8 Route107_EventScript_Lisa[];
extern const u8 Route107_EventScript_Ray[];
extern const u8 Route107_EventScript_Tony[];
extern const u8 Route107_EventScript_TonyRematch[];
extern const u8 Route108_EventScript_Carolina[];
extern const u8 Route108_EventScript_Cory[];
extern const u8 Route108_EventScript_CoryRematch[];
extern const u8 Route108_EventScript_Jerome[];
extern const u8 Route108_EventScript_Matthew[];
extern const u8 Route108_EventScript_Missy[];
extern const u8 Route108_EventScript_Tara[];
extern const u8 Route109_EventScript_Alice[];
extern const u8 Route109_EventScript_Austina[];
extern const u8 Route109_EventScript_Carter[];
extern const u8 Route109_EventScript_Chandler[];
extern const u8 Route109_EventScript_David[];
extern const u8 Route109_EventScript_Edmond[];
extern const u8 Route109_EventScript_Elijah[];
extern const u8 Route109_EventScript_Gwen[];
extern const u8 Route109_EventScript_Hailey[];
extern const u8 Route109_EventScript_Huey[];
extern const u8 Route109_EventScript_Lola[];
extern const u8 Route109_EventScript_LolaRematch[];
extern const u8 Route109_EventScript_Mel[];
extern const u8 Route109_EventScript_Paul[];
extern const u8 Route109_EventScript_Ricky[];
extern const u8 Route109_EventScript_RickyRematch[];
extern const u8 Route109_SeashoreHouse_EventScript_Dwayne[];
extern const u8 Route109_SeashoreHouse_EventScript_Johanna[];
extern const u8 Route109_SeashoreHouse_EventScript_Simon[];
extern const u8 Route10_EventScript_Jim[];
extern const u8 Route10_EventScript_Robert[];
extern const u8 Route110_EventScript_Abigail[];
extern const u8 Route110_EventScript_AbigailRematch[];
extern const u8 Route110_EventScript_Alyssa[];
extern const u8 Route110_EventScript_Anthony[];
extern const u8 Route110_EventScript_Benjamin[];
extern const u8 Route110_EventScript_BenjaminRematch[];
extern const u8 Route110_EventScript_Dale[];
extern const u8 Route110_EventScript_Edward[];
extern const u8 Route110_EventScript_Edwin[];
extern const u8 Route110_EventScript_EdwinRematch[];
extern const u8 Route110_EventScript_Isabel[];
extern const u8 Route110_EventScript_IsabelRematch[];
extern const u8 Route110_EventScript_Jaclyn[];
extern const u8 Route110_EventScript_Jacob[];
extern const u8 Route110_EventScript_Jasmine[];
extern const u8 Route110_EventScript_Joseph[];
extern const u8 Route110_EventScript_Kaleb[];
extern const u8 Route110_EventScript_Timmy[];
extern const u8 Route110_TrickHousePuzzle1_EventScript_Eddie[];
extern const u8 Route110_TrickHousePuzzle1_EventScript_Robin[];
extern const u8 Route110_TrickHousePuzzle1_EventScript_Sally[];
extern const u8 Route110_TrickHousePuzzle2_EventScript_Georgia[];
extern const u8 Route110_TrickHousePuzzle2_EventScript_Paul[];
extern const u8 Route110_TrickHousePuzzle2_EventScript_Ted[];
extern const u8 Route110_TrickHousePuzzle3_EventScript_Alan[];
extern const u8 Route110_TrickHousePuzzle3_EventScript_Justin[];
extern const u8 Route110_TrickHousePuzzle3_EventScript_Martha[];
extern const u8 Route110_TrickHousePuzzle4_EventScript_Cora[];
extern const u8 Route110_TrickHousePuzzle4_EventScript_Paula[];
extern const u8 Route110_TrickHousePuzzle4_EventScript_Yuji[];
extern const u8 Route110_TrickHousePuzzle6_EventScript_Benny[];
extern const u8 Route110_TrickHousePuzzle6_EventScript_Sebastian[];
extern const u8 Route110_TrickHousePuzzle6_EventScript_Sophia[];
extern const u8 Route110_TrickHousePuzzle7_EventScript_Alexis[];
extern const u8 Route110_TrickHousePuzzle7_EventScript_Alvaro[];
extern const u8 Route110_TrickHousePuzzle7_EventScript_Everett[];
extern const u8 Route110_TrickHousePuzzle7_EventScript_Joshua[];
extern const u8 Route110_TrickHousePuzzle7_EventScript_Mariela[];
extern const u8 Route110_TrickHousePuzzle7_EventScript_Patricia[];
extern const u8 Route110_TrickHousePuzzle8_EventScript_Keira[];
extern const u8 Route110_TrickHousePuzzle8_EventScript_Leroy[];
extern const u8 Route110_TrickHousePuzzle8_EventScript_Vincent[];
extern const u8 Route111_EventScript_Beau[];
extern const u8 Route111_EventScript_Becky[];
extern const u8 Route111_EventScript_Bianca[];
extern const u8 Route111_EventScript_Branden[];
extern const u8 Route111_EventScript_Brooke[];
extern const u8 Route111_EventScript_Bryan[];
extern const u8 Route111_EventScript_Celia[];
extern const u8 Route111_EventScript_Celina[];
extern const u8 Route111_EventScript_Daisuke[];
extern const u8 Route111_EventScript_Drew[];
extern const u8 Route111_EventScript_Dusty[];
extern const u8 Route111_EventScript_Hayden[];
extern const u8 Route111_EventScript_Heidi[];
extern const u8 Route111_EventScript_Irene[];
extern const u8 Route111_EventScript_RematchBrooke[];
extern const u8 Route111_EventScript_RematchDusty[];
extern const u8 Route111_EventScript_RematchWilton[];
extern const u8 Route111_EventScript_Travis[];
extern const u8 Route111_EventScript_Tyron[];
extern const u8 Route111_EventScript_Wilton[];
extern const u8 Route112_EventScript_Brice[];
extern const u8 Route112_EventScript_Bryant[];
extern const u8 Route112_EventScript_Carol[];
extern const u8 Route112_EventScript_Larry[];
extern const u8 Route112_EventScript_RematchTrent[];
extern const u8 Route112_EventScript_Shayla[];
extern const u8 Route112_EventScript_Trent[];
extern const u8 Route113_EventScript_Coby[];
extern const u8 Route113_EventScript_Dillon[];
extern const u8 Route113_EventScript_Jaylen[];
extern const u8 Route113_EventScript_Lao[];
extern const u8 Route113_EventScript_Lawrence[];
extern const u8 Route113_EventScript_Lung[];
extern const u8 Route113_EventScript_Madeline[];
extern const u8 Route113_EventScript_RematchLao[];
extern const u8 Route113_EventScript_RematchMadeline[];
extern const u8 Route113_EventScript_Sophie[];
extern const u8 Route113_EventScript_Tia[];
extern const u8 Route113_EventScript_Tori[];
extern const u8 Route113_EventScript_Wyatt[];
extern const u8 Route114_EventScript_Angelina[];
extern const u8 Route114_EventScript_Bernie[];
extern const u8 Route114_EventScript_Charlotte[];
extern const u8 Route114_EventScript_Claude[];
extern const u8 Route114_EventScript_Ivy[];
extern const u8 Route114_EventScript_Kai[];
extern const u8 Route114_EventScript_Lenny[];
extern const u8 Route114_EventScript_Lucas[];
extern const u8 Route114_EventScript_Nancy[];
extern const u8 Route114_EventScript_Nolan[];
extern const u8 Route114_EventScript_RematchBernie[];
extern const u8 Route114_EventScript_RematchSteve[];
extern const u8 Route114_EventScript_Shane[];
extern const u8 Route114_EventScript_Steve[];
extern const u8 Route114_EventScript_Tyra[];
extern const u8 Route115_EventScript_Alix[];
extern const u8 Route115_EventScript_Cyndy[];
extern const u8 Route115_EventScript_Hector[];
extern const u8 Route115_EventScript_Helene[];
extern const u8 Route115_EventScript_Jaiden[];
extern const u8 Route115_EventScript_Koichi[];
extern const u8 Route115_EventScript_Kyra[];
extern const u8 Route115_EventScript_Marlene[];
extern const u8 Route115_EventScript_Nob[];
extern const u8 Route115_EventScript_RematchCyndy[];
extern const u8 Route115_EventScript_RematchNob[];
extern const u8 Route115_EventScript_RematchTimothy[];
extern const u8 Route115_EventScript_Timothy[];
extern const u8 Route116_EventScript_Clark[];
extern const u8 Route116_EventScript_Dawson[];
extern const u8 Route116_EventScript_Devan[];
extern const u8 Route116_EventScript_Janice[];
extern const u8 Route116_EventScript_Jerry[];
extern const u8 Route116_EventScript_Joey[];
extern const u8 Route116_EventScript_Johnson[];
extern const u8 Route116_EventScript_Jose[];
extern const u8 Route116_EventScript_Karen[];
extern const u8 Route116_EventScript_RematchJerry[];
extern const u8 Route116_EventScript_RematchKaren[];
extern const u8 Route116_EventScript_Sarah[];
extern const u8 Route117_EventScript_Aisha[];
extern const u8 Route117_EventScript_Anna[];
extern const u8 Route117_EventScript_Brandi[];
extern const u8 Route117_EventScript_Derek[];
extern const u8 Route117_EventScript_Dylan[];
extern const u8 Route117_EventScript_Isaac[];
extern const u8 Route117_EventScript_Lydia[];
extern const u8 Route117_EventScript_Maria[];
extern const u8 Route117_EventScript_Meg[];
extern const u8 Route117_EventScript_Melina[];
extern const u8 Route117_EventScript_RematchAnna[];
extern const u8 Route117_EventScript_RematchDylan[];
extern const u8 Route117_EventScript_RematchIsaac[];
extern const u8 Route117_EventScript_RematchLydia[];
extern const u8 Route117_EventScript_RematchMaria[];
extern const u8 Route117_EventScript_RematchMeg[];
extern const u8 Route118_EventScript_Barny[];
extern const u8 Route118_EventScript_Chester[];
extern const u8 Route118_EventScript_Dalton[];
extern const u8 Route118_EventScript_Deandre[];
extern const u8 Route118_EventScript_Perry[];
extern const u8 Route118_EventScript_RematchDalton[];
extern const u8 Route118_EventScript_RematchRose[];
extern const u8 Route118_EventScript_Rose[];
extern const u8 Route118_EventScript_Wade[];
extern const u8 Route119_EventScript_Brent[];
extern const u8 Route119_EventScript_Catherine[];
extern const u8 Route119_EventScript_Chris[];
extern const u8 Route119_EventScript_Dayton[];
extern const u8 Route119_EventScript_Donald[];
extern const u8 Route119_EventScript_Doug[];
extern const u8 Route119_EventScript_Fabian[];
extern const u8 Route119_EventScript_Greg[];
extern const u8 Route119_EventScript_Hideo[];
extern const u8 Route119_EventScript_Hugh[];
extern const u8 Route119_EventScript_Jackson[];
extern const u8 Route119_EventScript_Kent[];
extern const u8 Route119_EventScript_Phil[];
extern const u8 Route119_EventScript_Rachel[];
extern const u8 Route119_EventScript_RematchCatherine[];
extern const u8 Route119_EventScript_RematchJackson[];
extern const u8 Route119_EventScript_Takashi[];
extern const u8 Route119_EventScript_Taylor[];
extern const u8 Route119_EventScript_Yasu[];
extern const u8 Route119_WeatherInstitute_1F_EventScript_Grunt1[];
extern const u8 Route119_WeatherInstitute_1F_EventScript_Grunt4[];
extern const u8 Route119_WeatherInstitute_2F_EventScript_Grunt2[];
extern const u8 Route119_WeatherInstitute_2F_EventScript_Grunt3[];
extern const u8 Route119_WeatherInstitute_2F_EventScript_Grunt5[];
extern const u8 Route11_EventScript_Fidel[];
extern const u8 Route11_EventScript_Herman[];
extern const u8 Route11_EventScript_Jason[];
extern const u8 Route11_EventScript_Owen[];
extern const u8 Route120_EventScript_Angelica[];
extern const u8 Route120_EventScript_Callie[];
extern const u8 Route120_EventScript_Chip[];
extern const u8 Route120_EventScript_Clarissa[];
extern const u8 Route120_EventScript_Colin[];
extern const u8 Route120_EventScript_Jeffrey[];
extern const u8 Route120_EventScript_Jenna[];
extern const u8 Route120_EventScript_Jennifer[];
extern const u8 Route120_EventScript_Keigo[];
extern const u8 Route120_EventScript_Leonel[];
extern const u8 Route120_EventScript_Lorenzo[];
extern const u8 Route120_EventScript_RematchJeffrey[];
extern const u8 Route120_EventScript_RematchRobert[];
extern const u8 Route120_EventScript_Riley[];
extern const u8 Route120_EventScript_Robert[];
extern const u8 Route121_EventScript_Cale[];
extern const u8 Route121_EventScript_Cristin[];
extern const u8 Route121_EventScript_Jessica[];
extern const u8 Route121_EventScript_Joy[];
extern const u8 Route121_EventScript_Kate[];
extern const u8 Route121_EventScript_Marcel[];
extern const u8 Route121_EventScript_Myles[];
extern const u8 Route121_EventScript_Pat[];
extern const u8 Route121_EventScript_RematchCristin[];
extern const u8 Route121_EventScript_RematchJessica[];
extern const u8 Route121_EventScript_RematchWalter[];
extern const u8 Route121_EventScript_Tammy[];
extern const u8 Route121_EventScript_Vanessa[];
extern const u8 Route121_EventScript_Walter[];
extern const u8 Route123_EventScript_Alberto[];
extern const u8 Route123_EventScript_Braxton[];
extern const u8 Route123_EventScript_Cameron[];
extern const u8 Route123_EventScript_Davis[];
extern const u8 Route123_EventScript_Ed[];
extern const u8 Route123_EventScript_Fernando[];
extern const u8 Route123_EventScript_Frederick[];
extern const u8 Route123_EventScript_Jacki[];
extern const u8 Route123_EventScript_Jazmyn[];
extern const u8 Route123_EventScript_Jonas[];
extern const u8 Route123_EventScript_Kayley[];
extern const u8 Route123_EventScript_Kindra[];
extern const u8 Route123_EventScript_Miu[];
extern const u8 Route123_EventScript_RematchCameron[];
extern const u8 Route123_EventScript_RematchFernando[];
extern const u8 Route123_EventScript_RematchJacki[];
extern const u8 Route123_EventScript_Violet[];
extern const u8 Route123_EventScript_Wendy[];
extern const u8 Route123_EventScript_Yuki[];
extern const u8 Route124_EventScript_Chad[];
extern const u8 Route124_EventScript_Declan[];
extern const u8 Route124_EventScript_Grace[];
extern const u8 Route124_EventScript_Isabella[];
extern const u8 Route124_EventScript_Jenny[];
extern const u8 Route124_EventScript_Lila[];
extern const u8 Route124_EventScript_RematchJenny[];
extern const u8 Route124_EventScript_RematchLila[];
extern const u8 Route124_EventScript_RematchRoy[];
extern const u8 Route124_EventScript_Roland[];
extern const u8 Route124_EventScript_Roy[];
extern const u8 Route124_EventScript_Spencer[];
extern const u8 Route125_EventScript_Auron[];
extern const u8 Route125_EventScript_Ernest[];
extern const u8 Route125_EventScript_Iris[];
extern const u8 Route125_EventScript_Kim[];
extern const u8 Route125_EventScript_Nolen[];
extern const u8 Route125_EventScript_Presley[];
extern const u8 Route125_EventScript_RematchErnest[];
extern const u8 Route125_EventScript_Sharon[];
extern const u8 Route125_EventScript_Stan[];
extern const u8 Route125_EventScript_Tanya[];
extern const u8 Route126_EventScript_Barry[];
extern const u8 Route126_EventScript_Brenda[];
extern const u8 Route126_EventScript_Dean[];
extern const u8 Route126_EventScript_Isobel[];
extern const u8 Route126_EventScript_Leonardo[];
extern const u8 Route126_EventScript_Nikki[];
extern const u8 Route126_EventScript_Pablo[];
extern const u8 Route126_EventScript_RematchPablo[];
extern const u8 Route126_EventScript_Sienna[];
extern const u8 Route127_EventScript_Aidan[];
extern const u8 Route127_EventScript_Athena[];
extern const u8 Route127_EventScript_Camden[];
extern const u8 Route127_EventScript_Donny[];
extern const u8 Route127_EventScript_Henry[];
extern const u8 Route127_EventScript_Jonah[];
extern const u8 Route127_EventScript_Koji[];
extern const u8 Route127_EventScript_RematchKoji[];
extern const u8 Route127_EventScript_Roger[];
extern const u8 Route128_EventScript_Alexa[];
extern const u8 Route128_EventScript_Carlee[];
extern const u8 Route128_EventScript_Harrison[];
extern const u8 Route128_EventScript_Isaiah[];
extern const u8 Route128_EventScript_Katelyn[];
extern const u8 Route128_EventScript_RematchIsaiah[];
extern const u8 Route128_EventScript_RematchKatelyn[];
extern const u8 Route128_EventScript_Ruben[];
extern const u8 Route128_EventScript_Wayne[];
extern const u8 Route129_EventScript_Allison[];
extern const u8 Route129_EventScript_Chase[];
extern const u8 Route129_EventScript_Clarence[];
extern const u8 Route129_EventScript_Reed[];
extern const u8 Route129_EventScript_Tisha[];
extern const u8 Route12_EventScript_Barney[];
extern const u8 Route12_EventScript_Kyle[];
extern const u8 Route12_EventScript_Martin[];
extern const u8 Route12_EventScript_RematchKyle[];
extern const u8 Route12_EventScript_Stephen[];
extern const u8 Route130_EventScript_Katie[];
extern const u8 Route130_EventScript_Rodney[];
extern const u8 Route130_EventScript_Santiago[];
extern const u8 Route131_EventScript_Herman[];
extern const u8 Route131_EventScript_Ian[];
extern const u8 Route131_EventScript_Kara[];
extern const u8 Route131_EventScript_Kevin[];
extern const u8 Route131_EventScript_Reli[];
extern const u8 Route131_EventScript_Richard[];
extern const u8 Route131_EventScript_Susie[];
extern const u8 Route131_EventScript_Talia[];
extern const u8 Route132_EventScript_Dana[];
extern const u8 Route132_EventScript_Darcy[];
extern const u8 Route132_EventScript_Gilbert[];
extern const u8 Route132_EventScript_Jonathan[];
extern const u8 Route132_EventScript_Kiyo[];
extern const u8 Route132_EventScript_Makayla[];
extern const u8 Route132_EventScript_Paxton[];
extern const u8 Route132_EventScript_Ronald[];
extern const u8 Route133_EventScript_Beck[];
extern const u8 Route133_EventScript_Conor[];
extern const u8 Route133_EventScript_Debra[];
extern const u8 Route133_EventScript_Franklin[];
extern const u8 Route133_EventScript_Linda[];
extern const u8 Route133_EventScript_Mollie[];
extern const u8 Route133_EventScript_Warren[];
extern const u8 Route134_EventScript_Aaron[];
extern const u8 Route134_EventScript_Alex[];
extern const u8 Route134_EventScript_Hitoshi[];
extern const u8 Route134_EventScript_Hudson[];
extern const u8 Route134_EventScript_Jack[];
extern const u8 Route134_EventScript_Kelvin[];
extern const u8 Route134_EventScript_Laurel[];
extern const u8 Route134_EventScript_Marley[];
extern const u8 Route134_EventScript_Reyna[];
extern const u8 Route13_EventScript_Alex[];
extern const u8 Route13_EventScript_Bret[];
extern const u8 Route13_EventScript_Joshua[];
extern const u8 Route13_EventScript_Kenny[];
extern const u8 Route13_EventScript_Perry[];
extern const u8 Route13_EventScript_RematchAlex[];
extern const u8 Route13_EventScript_RematchKenny[];
extern const u8 Route14_EventScript_Carter[];
extern const u8 Route14_EventScript_RematchCarter[];
extern const u8 Route14_EventScript_RematchTrevor[];
extern const u8 Route14_EventScript_Roy[];
extern const u8 Route14_EventScript_Trevor[];
extern const u8 Route15_EventScript_Billy[];
extern const u8 Route15_EventScript_Colette[];
extern const u8 Route15_EventScript_Hillary[];
extern const u8 Route15_EventScript_Johnny[];
extern const u8 Route15_EventScript_Kipp[];
extern const u8 Route15_EventScript_RematchBilly[];
extern const u8 Route15_EventScript_RematchHillary[];
extern const u8 Route15_EventScript_Tommy[];
extern const u8 Route17_EventScript_Charles[];
extern const u8 Route17_EventScript_Glenn[];
extern const u8 Route17_EventScript_Joel[];
extern const u8 Route17_EventScript_RematchCharles[];
extern const u8 Route17_EventScript_RematchJoel[];
extern const u8 Route17_EventScript_RematchRiley[];
extern const u8 Route17_EventScript_Riley[];
extern const u8 Route18_EventScript_Bob[];
extern const u8 Route18_EventScript_Boris[];
extern const u8 Route19_EventScript_Dawn[];
extern const u8 Route19_EventScript_Harold[];
extern const u8 Route19_EventScript_Jerome[];
extern const u8 Route19_EventScript_Tucker[];
extern const u8 Route1_EventScript_Quinn[];
extern const u8 Route1_EventScript_SchoolboyDanny[];
extern const u8 Route20_EventScript_Cameron[];
extern const u8 Route20_EventScript_Lori[];
extern const u8 Route20_EventScript_Nicole[];
extern const u8 Route20_EventScript_RematchNicole[];
extern const u8 Route21_EventScript_Arnold[];
extern const u8 Route21_EventScript_Nikki[];
extern const u8 Route21_EventScript_Seth[];
extern const u8 Route25_EventScript_Dudley[];
extern const u8 Route25_EventScript_Ellen[];
extern const u8 Route25_EventScript_Joe[];
extern const u8 Route25_EventScript_Laura[];
extern const u8 Route25_EventScript_Lloyd[];
extern const u8 Route25_EventScript_Pat[];
extern const u8 Route25_EventScript_Shannon[];
extern const u8 Route26_EventScript_Beth[];
extern const u8 Route26_EventScript_Gaven[];
extern const u8 Route26_EventScript_Jake[];
extern const u8 Route26_EventScript_Joyce[];
extern const u8 Route26_EventScript_RematchBeth[];
extern const u8 Route26_EventScript_RematchGaven[];
extern const u8 Route26_EventScript_Richard[];
extern const u8 Route27_EventScript_Blake[];
extern const u8 Route27_EventScript_Brian[];
extern const u8 Route27_EventScript_Gilbert[];
extern const u8 Route27_EventScript_Jose[];
extern const u8 Route27_EventScript_Megan[];
extern const u8 Route27_EventScript_Reena[];
extern const u8 Route27_EventScript_RematchJose[];
extern const u8 Route27_EventScript_RematchReena[];
extern const u8 Route27_EventScript_Scott[];
extern const u8 Route2_EventScript_Doug[];
extern const u8 Route2_EventScript_Ed[];
extern const u8 Route2_EventScript_RematchRob[];
extern const u8 Route2_EventScript_Rob[];
extern const u8 Route30_EventScript_Bugcatcher_Don[];
extern const u8 Route30_EventScript_RematchJoey[];
extern const u8 Route30_EventScript_Youngster_Joey[];
extern const u8 Route30_EventScript_Youngster_Mikey[];
extern const u8 Route31_EventScript_Bugcatcher_Wade[];
extern const u8 Route31_EventScript_RematchWade[];
extern const u8 Route32_EventScript_BirdkeeperPeter[];
extern const u8 Route32_EventScript_CamperRoland[];
extern const u8 Route32_EventScript_FisherHenry[];
extern const u8 Route32_EventScript_FisherJustin[];
extern const u8 Route32_EventScript_FisherRalph[];
extern const u8 Route32_EventScript_PicnickerLiz[];
extern const u8 Route32_EventScript_RematchLiz[];
extern const u8 Route32_EventScript_RematchRalph[];
extern const u8 Route32_EventScript_YoungsterAlbert[];
extern const u8 Route32_EventScript_YoungsterGordon[];
extern const u8 Route33_EventScript_HikerAnthony[];
extern const u8 Route33_EventScript_RematchAnthony[];
extern const u8 Route34_EventScript_CamperTodd[];
extern const u8 Route34_EventScript_Irene[];
extern const u8 Route34_EventScript_Jenn[];
extern const u8 Route34_EventScript_Kate[];
extern const u8 Route34_EventScript_OfficerKeith[];
extern const u8 Route34_EventScript_PicnickerGina[];
extern const u8 Route34_EventScript_PokefanMBrandon[];
extern const u8 Route34_EventScript_RematchGina[];
extern const u8 Route34_EventScript_RematchTodd[];
extern const u8 Route34_EventScript_YoungsterIan[];
extern const u8 Route34_EventScript_YoungsterSamuel[];
extern const u8 Route35_EventScript_BirdKeeperBryan[];
extern const u8 Route35_EventScript_BugCatcherArnie[];
extern const u8 Route35_EventScript_CamperElliot[];
extern const u8 Route35_EventScript_CamperIvan[];
extern const u8 Route35_EventScript_FirebreatherWalt[];
extern const u8 Route35_EventScript_JugglerIrwin[];
extern const u8 Route35_EventScript_PicnickerBrooke[];
extern const u8 Route35_EventScript_PicnickerKim[];
extern const u8 Route35_EventScript_PolicemanDirk[];
extern const u8 Route35_EventScript_RematchArnie[];
extern const u8 Route35_EventScript_RematchIrwin[];
extern const u8 Route36_EventScript_Mark[];
extern const u8 Route36_EventScript_RematchAlan[];
extern const u8 Route36_EventScript_Schoolboy[];
extern const u8 Route37_EventScript_Greg[];
extern const u8 Route37_EventScript_TwinAnn[];
extern const u8 Route37_EventScript_TwinAnne[];
extern const u8 Route38_EventScript_Chad[];
extern const u8 Route38_EventScript_Dana[];
extern const u8 Route38_EventScript_Harry[];
extern const u8 Route38_EventScript_Olivia[];
extern const u8 Route38_EventScript_RematchChad[];
extern const u8 Route38_EventScript_RematchDana[];
extern const u8 Route38_EventScript_Toby[];
extern const u8 Route38_EventScript_Valerie[];
extern const u8 Route39_EventScript_Derek[];
extern const u8 Route39_EventScript_Eugene[];
extern const u8 Route39_EventScript_Jamie[];
extern const u8 Route39_EventScript_Norman[];
extern const u8 Route39_EventScript_RematchDerek[];
extern const u8 Route39_EventScript_Ruth[];
extern const u8 Route3_EventScript_Burt[];
extern const u8 Route3_EventScript_Jimmy[];
extern const u8 Route3_EventScript_Otis[];
extern const u8 Route3_EventScript_Warren[];
extern const u8 Route40_EventScript_Elaine[];
extern const u8 Route40_EventScript_Paula[];
extern const u8 Route40_EventScript_Randall[];
extern const u8 Route40_EventScript_Simon[];
extern const u8 Route41_EventScript_Berke[];
extern const u8 Route41_EventScript_Charlie[];
extern const u8 Route41_EventScript_Denise[];
extern const u8 Route41_EventScript_George[];
extern const u8 Route41_EventScript_Kara[];
extern const u8 Route41_EventScript_Kaylee[];
extern const u8 Route41_EventScript_Kirk[];
extern const u8 Route41_EventScript_Mathew[];
extern const u8 Route41_EventScript_Susie[];
extern const u8 Route41_EventScript_Wendy[];
extern const u8 Route42_EventScript_Ben[];
extern const u8 Route42_EventScript_RematchTully[];
extern const u8 Route42_EventScript_Shane[];
extern const u8 Route42_EventScript_Tully[];
extern const u8 Route43_EventScript_Ben[];
extern const u8 Route43_EventScript_Brent[];
extern const u8 Route43_EventScript_Marvin[];
extern const u8 Route43_EventScript_RematchBrent[];
extern const u8 Route43_EventScript_RematchTiffany[];
extern const u8 Route43_EventScript_Ron[];
extern const u8 Route43_EventScript_Spencer[];
extern const u8 Route43_EventScript_Tiffany[];
extern const u8 Route44_EventScript_Allen[];
extern const u8 Route44_EventScript_Cybil[];
extern const u8 Route44_EventScript_Edgar[];
extern const u8 Route44_EventScript_Phil[];
extern const u8 Route44_EventScript_RematchVance[];
extern const u8 Route44_EventScript_RematchWilton[];
extern const u8 Route44_EventScript_Vance[];
extern const u8 Route44_EventScript_Wilton[];
extern const u8 Route44_EventScript_Zach[];
extern const u8 Route45_EventScript_Erik[];
extern const u8 Route45_EventScript_Kelly[];
extern const u8 Route45_EventScript_Kenji[];
extern const u8 Route45_EventScript_Michael[];
extern const u8 Route45_EventScript_Parry[];
extern const u8 Route45_EventScript_Quentin[];
extern const u8 Route45_EventScript_RematchKenji[];
extern const u8 Route45_EventScript_RematchParry[];
extern const u8 Route45_EventScript_Ryan[];
extern const u8 Route45_EventScript_Timothy[];
extern const u8 Route46_EventScript_Bailey[];
extern const u8 Route46_EventScript_Erin[];
extern const u8 Route46_EventScript_RematchErin[];
extern const u8 Route46_EventScript_Ted[];
extern const u8 Route47_EventScript_Camper[];
extern const u8 Route47_EventScript_Duff[];
extern const u8 Route47_EventScript_Eda[];
extern const u8 Route47_EventScript_Hiker[];
extern const u8 Route47_EventScript_Kae[];
extern const u8 Route47_EventScript_Thom[];
extern const u8 Route4_EventScript_Hank[];
extern const u8 Route4_EventScript_Hope[];
extern const u8 Route4_EventScript_Sharon[];
extern const u8 Route6_EventScript_Allan[];
extern const u8 Route6_EventScript_Rex[];
extern const u8 Route8_EventScript_Dwayne[];
extern const u8 Route8_EventScript_Harris[];
extern const u8 Route8_EventScript_Sam[];
extern const u8 Route8_EventScript_Tom[];
extern const u8 Route8_EventScript_Zeke[];
extern const u8 Route9_EventScript_Dean[];
extern const u8 Route9_EventScript_Edna[];
extern const u8 Route9_EventScript_Heidi[];
extern const u8 Route9_EventScript_Sid[];
extern const u8 Route9_EventScript_Sidney[];
extern const u8 Route9_EventScript_Tim[];
extern const u8 RuinsOfAlph_Outside_EventScript_Nathan[];
extern const u8 RuinsOfAlph_Outside_EventScript_Stan[];
extern const u8 RusturfTunnel_EventScript_Mike[];
extern const u8 SSAqua_B1F_EventScript_Debra[];
extern const u8 SSAqua_B1F_EventScript_Fritz[];
extern const u8 SSAqua_B1F_EventScript_Garrett[];
extern const u8 SSAqua_B1F_EventScript_Jeff[];
extern const u8 SSAqua_B1F_EventScript_Jonah[];
extern const u8 SSAqua_B1F_EventScript_Kenneth[];
extern const u8 SSAqua_B1F_EventScript_Nate[];
extern const u8 SSAqua_B1F_EventScript_Ricky[];
extern const u8 SSAqua_B1F_EventScript_Shirley[];
extern const u8 SSAqua_B1F_EventScript_Wai[];
extern const u8 SSAqua_RoomNE_EventScript_Ethan[];
extern const u8 SSAqua_RoomNE_EventScript_Noland[];
extern const u8 SSAqua_RoomNNE_EventScript_Carol[];
extern const u8 SSAqua_RoomNNE_EventScript_Sean[];
extern const u8 SSAqua_RoomNW_EventScript_Corey[];
extern const u8 SSAqua_RoomNW_EventScript_Edward[];
extern const u8 SSAqua_RoomSE_EventScript_Colin[];
extern const u8 SSAqua_RoomSE_EventScript_Meg[];
extern const u8 SSAqua_RoomSE_EventScript_Peg[];
extern const u8 SSAqua_RoomSSW_EventScript_Ken[];
extern const u8 SSAqua_RoomSSW_EventScript_Lyle[];
extern const u8 SSAqua_RoomSW_EventScript_Cassie[];
extern const u8 SSAqua_RoomSW_EventScript_Clyde[];
extern const u8 SSTidalLowerDeck_EventScript_Leonard[];
extern const u8 SSTidalLowerDeck_EventScript_Phillip[];
extern const u8 SSTidalRooms_EventScript_Colton[];
extern const u8 SSTidalRooms_EventScript_Garret[];
extern const u8 SSTidalRooms_EventScript_Jed[];
extern const u8 SSTidalRooms_EventScript_Lea[];
extern const u8 SSTidalRooms_EventScript_Micah[];
extern const u8 SSTidalRooms_EventScript_Naomi[];
extern const u8 SSTidalRooms_EventScript_Thomas[];
extern const u8 SeafloorCavern_Room1_EventScript_Grunt1[];
extern const u8 SeafloorCavern_Room1_EventScript_Grunt2[];
extern const u8 SeafloorCavern_Room3_EventScript_Grunt5[];
extern const u8 SeafloorCavern_Room3_EventScript_Shelly[];
extern const u8 SeafloorCavern_Room4_EventScript_Grunt3[];
extern const u8 SeafloorCavern_Room4_EventScript_Grunt4[];
extern const u8 SlowpokeWell_B1F_EventScript_Eto[];
extern const u8 SlowpokeWell_B1F_EventScript_Grunt21[];
extern const u8 SlowpokeWell_B1F_EventScript_Grunt22F[];
extern const u8 SproutTower_1F_EventScript_SageChow[];
extern const u8 SproutTower_2F_EventScript_SageEdmond[];
extern const u8 SproutTower_2F_EventScript_SageNico[];
extern const u8 SproutTower_3F_EventScript_SageJin[];
extern const u8 SproutTower_3F_EventScript_SageNeal[];
extern const u8 SproutTower_3F_EventScript_SageTroy[];
extern const u8 UnionCave_1F_EventScript_FirebreatherBill[];
extern const u8 UnionCave_1F_EventScript_FirebreatherRay[];
extern const u8 UnionCave_1F_EventScript_HikerDaniel[];
extern const u8 UnionCave_1F_EventScript_HikerRussell[];
extern const u8 UnionCave_1F_EventScript_PokemaniacLarry[];
extern const u8 UnionCave_B1F_EventScript_HikerLeonard[];
extern const u8 UnionCave_B1F_EventScript_HikerPhillip[];
extern const u8 UnionCave_B1F_EventScript_PokemaniacAndrew[];
extern const u8 UnionCave_B1F_EventScript_PokemaniacCalvin[];
extern const u8 UnionCave_B2F_EventScript_CooltrainerNick[];
extern const u8 UnionCave_B2F_EventScript_CooltrainerfEmma[];
extern const u8 UnionCave_B2F_EventScript_CooltrainerfGwen[];
extern const u8 VictoryRoad_1F_EventScript_Albert[];
extern const u8 VictoryRoad_1F_EventScript_Edgar[];
extern const u8 VictoryRoad_1F_EventScript_Hope[];
extern const u8 VictoryRoad_1F_EventScript_Katelynn[];
extern const u8 VictoryRoad_1F_EventScript_Quincy[];
extern const u8 VictoryRoad_B1F_EventScript_Halle[];
extern const u8 VictoryRoad_B1F_EventScript_Michelle[];
extern const u8 VictoryRoad_B1F_EventScript_Mitchell[];
extern const u8 VictoryRoad_B1F_EventScript_Samuel[];
extern const u8 VictoryRoad_B1F_EventScript_Shannon[];
extern const u8 VictoryRoad_B2F_EventScript_Caroline[];
extern const u8 VictoryRoad_B2F_EventScript_Dianne[];
extern const u8 VictoryRoad_B2F_EventScript_Felix[];
extern const u8 VictoryRoad_B2F_EventScript_Julie[];
extern const u8 VictoryRoad_B2F_EventScript_Owen[];
extern const u8 VictoryRoad_B2F_EventScript_Vito[];
const u8 *const gWayfarerStoryOrdinaryCallers[] =
{
    AbandonedShip_Corridors_1F_EventScript_Charlie + 1,
    AbandonedShip_Corridors_B1F_EventScript_Duncan + 1,
    AbandonedShip_Rooms2_1F_EventScript_Dan + 1,
    AbandonedShip_Rooms2_1F_EventScript_DanRematch + 1,
    AbandonedShip_Rooms2_1F_EventScript_Garrison + 1,
    AbandonedShip_Rooms2_1F_EventScript_Jani + 1,
    AbandonedShip_Rooms2_1F_EventScript_Kira + 1,
    AbandonedShip_Rooms2_1F_EventScript_KiraRematch + 1,
    AbandonedShip_Rooms_1F_EventScript_Demetrius + 1,
    AbandonedShip_Rooms_1F_EventScript_Thalia + 1,
    AbandonedShip_Rooms_1F_EventScript_ThaliaRematch + 1,
    Alola_AkalaCave_TrainerBattleCamper + 1,
    Alola_AkalaCave_TrainerBattleHiker + 1,
    Alola_AkalaCave_TrainerBattlePicnicker + 1,
    Alola_AkalaForest_TrainerBattleBugCatcher1 + 1,
    Alola_AkalaForest_TrainerBattleBugCatcher2 + 1,
    Alola_Akala_TrainerBattleCamper + 1,
    Alola_Akala_TrainerBattleHiker + 1,
    Alola_Akala_TrainerBattlePicnicker + 1,
    Alola_Akala_TrainerBattleSwimmerLand + 1,
    Alola_Akala_TrainerBattleSwimmerWater + 1,
    Alola_Akala_TrainerBattleSwimmerWaterM + 1,
    Alola_MelemeleSea_TrainerBattleSwimmer + 1,
    Alola_Melemele_TrainerBattleSwimmer + 1,
    Alola_Poni_TrainerBattleSwimmer1 + 1,
    Alola_Poni_TrainerBattleSwimmer2 + 1,
    Alola_Ulaula_TrainerBattleCooltrainer + 1,
    Alola_Ulaula_TrainerBattleHiker + 1,
    Alola_Ulaula_TrainerBattlePicnicker + 1,
    Alola_Ulaula_TrainerBattleYoungster + 1,
    AquaHideout_1F_EventScript_Grunt1 + 1,
    AquaHideout_B1F_EventScript_Grunt2 + 1,
    AquaHideout_B1F_EventScript_Grunt3 + 1,
    AquaHideout_B1F_EventScript_Grunt5 + 1,
    AquaHideout_B1F_EventScript_Grunt7 + 1,
    AquaHideout_B2F_EventScript_Grunt4 + 1,
    AquaHideout_B2F_EventScript_Grunt6 + 1,
    AquaHideout_B2F_EventScript_Grunt8 + 1,
    BurnedTower_1F_EventScript_Nard + 1,
    BurnedTower_1F_EventScript_Richardo + 1,
    DragonsDen_Cavern_EventScript_Cara + 1,
    DragonsDen_Cavern_EventScript_Darin + 1,
    DragonsDen_Cavern_EventScript_TwinLea + 1,
    DragonsDen_Cavern_EventScript_TwinPia + 1,
    GabbyAndTy_EventScript_GabbyBattle1 + 1,
    GabbyAndTy_EventScript_GabbyBattle2 + 1,
    GabbyAndTy_EventScript_GabbyBattle3 + 1,
    GabbyAndTy_EventScript_GabbyBattle4 + 1,
    GabbyAndTy_EventScript_GabbyBattle5 + 1,
    GabbyAndTy_EventScript_GabbyBattle6 + 1,
    GabbyAndTy_EventScript_TyBattle1 + 1,
    GabbyAndTy_EventScript_TyBattle2 + 1,
    GabbyAndTy_EventScript_TyBattle3 + 1,
    GabbyAndTy_EventScript_TyBattle4 + 1,
    GabbyAndTy_EventScript_TyBattle5 + 1,
    GabbyAndTy_EventScript_TyBattle6 + 1,
    GoldenrodCity_RadioTower_4F4_EventScript_Scientist + 1,
    GoldenrodCity_UndergroundStorage_EventScript_Eto + 1,
    GoldenrodCity_UndergroundStorage_EventScript_Grunt12 + 1,
    GoldenrodCity_UndergroundStorage_EventScript_Grunt19 + 1,
    GoldenrodCity_UndergroundSwitches_EventScript_Duncan + 1,
    GoldenrodCity_UndergroundSwitches_EventScript_Eddie + 1,
    GoldenrodCity_UndergroundSwitches_EventScript_Grunt10 + 1,
    GoldenrodCity_UndergroundSwitches_EventScript_Grunt11 + 1,
    GoldenrodCity_UndergroundSwitches_EventScript_Grunt20 + 1,
    GoldenrodCity_UndergroundSwitches_EventScript_Grunt27 + 1,
    GoldenrodRaidoTower2_EventScript_Grunt3 + 1,
    GoldenrodRaidoTower2_EventScript_Grunt4 + 1,
    GoldenrodRaidoTower2_EventScript_Grunt5 + 1,
    GoldenrodRaidoTower2_EventScript_GruntF2 + 1,
    GoldenrodRaidoTower3_EventScript_Grunt6 + 1,
    GoldenrodRaidoTower3_EventScript_Grunt7 + 1,
    GoldenrodRaidoTower3_EventScript_Grunt8 + 1,
    GoldenrodRaidoTower3_EventScript_Scientist + 1,
    GoldenrodRaidoTower4_EventScript_Grunt28 + 1,
    GoldenrodRaidoTower4_EventScript_Grunt9 + 1,
    GoldenrodUnderground_EventScript_Donald + 1,
    GoldenrodUnderground_EventScript_Eric + 1,
    GoldenrodUnderground_EventScript_Issac + 1,
    GoldenrodUnderground_EventScript_Teru + 1,
    IlexForest_EventScript_BugcatcherWayne + 1,
    JaggedPass_EventScript_Autumn + 1,
    JaggedPass_EventScript_Diana + 1,
    JaggedPass_EventScript_DianaRematch + 1,
    JaggedPass_EventScript_Eric + 1,
    JaggedPass_EventScript_Ethan + 1,
    JaggedPass_EventScript_EthanRematch + 1,
    JaggedPass_EventScript_Julio + 1,
    LakeOfRage_EventScript_Aaron + 1,
    LakeOfRage_EventScript_Andre + 1,
    LakeOfRage_EventScript_Lois + 1,
    LakeOfRage_EventScript_Raymond + 1,
    MagmaHideout_1F_EventScript_Grunt1 + 1,
    MagmaHideout_1F_EventScript_Grunt2 + 1,
    MagmaHideout_2F_1R_EventScript_Grunt14 + 1,
    MagmaHideout_2F_1R_EventScript_Grunt3 + 1,
    MagmaHideout_2F_1R_EventScript_Grunt4 + 1,
    MagmaHideout_2F_1R_EventScript_Grunt5 + 1,
    MagmaHideout_2F_2R_EventScript_Grunt15 + 1,
    MagmaHideout_2F_2R_EventScript_Grunt6 + 1,
    MagmaHideout_2F_2R_EventScript_Grunt7 + 1,
    MagmaHideout_2F_2R_EventScript_Grunt8 + 1,
    MagmaHideout_3F_1R_EventScript_Grunt16 + 1,
    MagmaHideout_3F_1R_EventScript_Grunt9 + 1,
    MagmaHideout_3F_2R_EventScript_Grunt10 + 1,
    MagmaHideout_4F_EventScript_Grunt11 + 1,
    MagmaHideout_4F_EventScript_Grunt12 + 1,
    MagmaHideout_4F_EventScript_Grunt13 + 1,
    MagmaHideout_4F_EventScript_Tabitha + 1,
    MeteorFalls_1F_2R_EventScript_Jay + 1,
    MeteorFalls_1F_2R_EventScript_John + 1,
    MeteorFalls_1F_2R_EventScript_Nicolas + 1,
    MeteorFalls_1F_2R_EventScript_RematchJay + 1,
    MeteorFalls_1F_2R_EventScript_RematchJohn + 1,
    MeteorFalls_1F_2R_EventScript_RematchNicolas + 1,
    MossdeepCity_SpaceCenter_1F_EventScript_Grunt1 + 1,
    MossdeepCity_SpaceCenter_1F_EventScript_Grunt3 + 1,
    MossdeepCity_SpaceCenter_1F_EventScript_Grunt4 + 1,
    MtChimney_EventScript_Grunt1 + 1,
    MtChimney_EventScript_Grunt2 + 1,
    MtChimney_EventScript_Melissa + 1,
    MtChimney_EventScript_RematchShelby + 1,
    MtChimney_EventScript_Sawyer + 1,
    MtChimney_EventScript_SawyerRematch + 1,
    MtChimney_EventScript_Sheila + 1,
    MtChimney_EventScript_Shelby + 1,
    MtChimney_EventScript_Shirley + 1,
    MtChimney_EventScript_Tabitha + 1,
    MtMortar_1F_North_EventScript_Markus + 1,
    MtMortar_1F_North_EventScript_Miller + 1,
    MtMortar_2F_EventScript_Nerd + 1,
    MtPyre_2F_EventScript_Dez + 1,
    MtPyre_2F_EventScript_Leah + 1,
    MtPyre_2F_EventScript_Luke + 1,
    MtPyre_2F_EventScript_Mark + 1,
    MtPyre_2F_EventScript_Zander + 1,
    MtPyre_3F_EventScript_Gabrielle + 1,
    MtPyre_3F_EventScript_Kayla + 1,
    MtPyre_3F_EventScript_RematchGabrielle + 1,
    MtPyre_3F_EventScript_William + 1,
    MtPyre_4F_EventScript_Tasha + 1,
    MtPyre_5F_EventScript_Atsushi + 1,
    MtPyre_6F_EventScript_Cedric + 1,
    MtPyre_6F_EventScript_RematchValerie + 1,
    MtPyre_6F_EventScript_Valerie + 1,
    MtPyre_Summit_EventScript_Grunt1 + 1,
    MtPyre_Summit_EventScript_Grunt2 + 1,
    MtPyre_Summit_EventScript_Grunt3 + 1,
    MtPyre_Summit_EventScript_Grunt4 + 1,
    NationalPark_Normal_EventScript_Beverly + 1,
    NationalPark_Normal_EventScript_Jack + 1,
    NationalPark_Normal_EventScript_Krise + 1,
    NationalPark_Normal_EventScript_RematchBeverly + 1,
    NationalPark_Normal_EventScript_RematchJack + 1,
    NationalPark_Normal_EventScript_William + 1,
    OlivineLighthouse_EventScript_BirdKeeperDenis + 1,
    OlivineLighthouse_EventScript_BirdKeeperTheo + 1,
    OlivineLighthouse_EventScript_GentlemanAlfred + 1,
    OlivineLighthouse_EventScript_GentlemanPreston + 1,
    OlivineLighthouse_EventScript_Huey + 1,
    OlivineLighthouse_EventScript_LassConnie + 1,
    OlivineLighthouse_EventScript_RematchHuey + 1,
    OlivineLighthouse_EventScript_SailorErnest + 1,
    OlivineLighthouse_EventScript_SailorKent + 1,
    OlivineLighthouse_EventScript_SailorTerrell + 1,
    PetalburgWoods_EventScript_James + 1,
    PetalburgWoods_EventScript_JamesRematch + 1,
    PetalburgWoods_EventScript_Lyle + 1,
    RocketHideout_B1F_EventScript_Rocket16 + 1,
    RocketHideout_B1F_EventScript_TrainerJed + 1,
    RocketHideout_B2F_EventScript_Grunt14 + 1,
    RocketHideout_B2F_EventScript_Grunt15 + 1,
    RocketHideout_B2F_EventScript_Grunt16 + 1,
    RocketHideout_B3F_EventScript_Mitch + 1,
    RocketHideout_B3F_EventScript_Ross + 1,
    Route102_EventScript_Allen + 1,
    Route102_EventScript_AmyRematch + 1,
    Route102_EventScript_Calvin + 1,
    Route102_EventScript_CalvinRematch + 1,
    Route102_EventScript_LivRematch + 1,
    Route102_EventScript_Rick + 1,
    Route102_EventScript_Tiana + 1,
    Route103_EventScript_Amy + 1,
    Route103_EventScript_Andrew + 1,
    Route103_EventScript_Daisy + 1,
    Route103_EventScript_Isabelle + 1,
    Route103_EventScript_Liv + 1,
    Route103_EventScript_Marcos + 1,
    Route103_EventScript_Miguel + 1,
    Route103_EventScript_MiguelRematch + 1,
    Route103_EventScript_Pete + 1,
    Route103_EventScript_Rhett + 1,
    Route104_EventScript_Billy + 1,
    Route104_EventScript_Cindy + 1,
    Route104_EventScript_Darian + 1,
    Route104_EventScript_Gina + 1,
    Route104_EventScript_Haley + 1,
    Route104_EventScript_Ivan + 1,
    Route104_EventScript_Mia + 1,
    Route104_EventScript_RematchCindy + 1,
    Route104_EventScript_RematchHaley + 1,
    Route104_EventScript_RematchWinston + 1,
    Route104_EventScript_Winston + 1,
    Route105_EventScript_Andres + 1,
    Route105_EventScript_AndresRematch + 1,
    Route105_EventScript_Beverly + 1,
    Route105_EventScript_Dominik + 1,
    Route105_EventScript_Foster + 1,
    Route105_EventScript_Imani + 1,
    Route105_EventScript_Josue + 1,
    Route105_EventScript_Luis + 1,
    Route106_EventScript_Douglas + 1,
    Route106_EventScript_Elliot + 1,
    Route106_EventScript_ElliotRematch + 1,
    Route106_EventScript_Kyla + 1,
    Route106_EventScript_Ned + 1,
    Route107_EventScript_Beth + 1,
    Route107_EventScript_Camron + 1,
    Route107_EventScript_Darrin + 1,
    Route107_EventScript_Denise + 1,
    Route107_EventScript_Lisa + 1,
    Route107_EventScript_Ray + 1,
    Route107_EventScript_Tony + 1,
    Route107_EventScript_TonyRematch + 1,
    Route108_EventScript_Carolina + 1,
    Route108_EventScript_Cory + 1,
    Route108_EventScript_CoryRematch + 1,
    Route108_EventScript_Jerome + 1,
    Route108_EventScript_Matthew + 1,
    Route108_EventScript_Missy + 1,
    Route108_EventScript_Tara + 1,
    Route109_EventScript_Alice + 1,
    Route109_EventScript_Austina + 1,
    Route109_EventScript_Carter + 1,
    Route109_EventScript_Chandler + 1,
    Route109_EventScript_David + 1,
    Route109_EventScript_Edmond + 1,
    Route109_EventScript_Elijah + 1,
    Route109_EventScript_Gwen + 1,
    Route109_EventScript_Hailey + 1,
    Route109_EventScript_Huey + 1,
    Route109_EventScript_Lola + 1,
    Route109_EventScript_LolaRematch + 1,
    Route109_EventScript_Mel + 1,
    Route109_EventScript_Paul + 1,
    Route109_EventScript_Ricky + 1,
    Route109_EventScript_RickyRematch + 1,
    Route109_SeashoreHouse_EventScript_Dwayne + 1,
    Route109_SeashoreHouse_EventScript_Johanna + 1,
    Route109_SeashoreHouse_EventScript_Simon + 1,
    Route10_EventScript_Jim + 1,
    Route10_EventScript_Robert + 1,
    Route110_EventScript_Abigail + 1,
    Route110_EventScript_AbigailRematch + 1,
    Route110_EventScript_Alyssa + 1,
    Route110_EventScript_Anthony + 1,
    Route110_EventScript_Benjamin + 1,
    Route110_EventScript_BenjaminRematch + 1,
    Route110_EventScript_Dale + 1,
    Route110_EventScript_Edward + 1,
    Route110_EventScript_Edwin + 1,
    Route110_EventScript_EdwinRematch + 1,
    Route110_EventScript_Isabel + 1,
    Route110_EventScript_IsabelRematch + 1,
    Route110_EventScript_Jaclyn + 1,
    Route110_EventScript_Jacob + 1,
    Route110_EventScript_Jasmine + 1,
    Route110_EventScript_Joseph + 1,
    Route110_EventScript_Kaleb + 1,
    Route110_EventScript_Timmy + 1,
    Route110_TrickHousePuzzle1_EventScript_Eddie + 1,
    Route110_TrickHousePuzzle1_EventScript_Robin + 1,
    Route110_TrickHousePuzzle1_EventScript_Sally + 1,
    Route110_TrickHousePuzzle2_EventScript_Georgia + 1,
    Route110_TrickHousePuzzle2_EventScript_Paul + 1,
    Route110_TrickHousePuzzle2_EventScript_Ted + 1,
    Route110_TrickHousePuzzle3_EventScript_Alan + 1,
    Route110_TrickHousePuzzle3_EventScript_Justin + 1,
    Route110_TrickHousePuzzle3_EventScript_Martha + 1,
    Route110_TrickHousePuzzle4_EventScript_Cora + 1,
    Route110_TrickHousePuzzle4_EventScript_Paula + 1,
    Route110_TrickHousePuzzle4_EventScript_Yuji + 1,
    Route110_TrickHousePuzzle6_EventScript_Benny + 1,
    Route110_TrickHousePuzzle6_EventScript_Sebastian + 1,
    Route110_TrickHousePuzzle6_EventScript_Sophia + 1,
    Route110_TrickHousePuzzle7_EventScript_Alexis + 1,
    Route110_TrickHousePuzzle7_EventScript_Alvaro + 1,
    Route110_TrickHousePuzzle7_EventScript_Everett + 1,
    Route110_TrickHousePuzzle7_EventScript_Joshua + 1,
    Route110_TrickHousePuzzle7_EventScript_Mariela + 1,
    Route110_TrickHousePuzzle7_EventScript_Patricia + 1,
    Route110_TrickHousePuzzle8_EventScript_Keira + 1,
    Route110_TrickHousePuzzle8_EventScript_Leroy + 1,
    Route110_TrickHousePuzzle8_EventScript_Vincent + 1,
    Route111_EventScript_Beau + 1,
    Route111_EventScript_Becky + 1,
    Route111_EventScript_Bianca + 1,
    Route111_EventScript_Branden + 1,
    Route111_EventScript_Brooke + 1,
    Route111_EventScript_Bryan + 1,
    Route111_EventScript_Celia + 1,
    Route111_EventScript_Celina + 1,
    Route111_EventScript_Daisuke + 1,
    Route111_EventScript_Drew + 1,
    Route111_EventScript_Dusty + 1,
    Route111_EventScript_Hayden + 1,
    Route111_EventScript_Heidi + 1,
    Route111_EventScript_Irene + 1,
    Route111_EventScript_RematchBrooke + 1,
    Route111_EventScript_RematchDusty + 1,
    Route111_EventScript_RematchWilton + 1,
    Route111_EventScript_Travis + 1,
    Route111_EventScript_Tyron + 1,
    Route111_EventScript_Wilton + 1,
    Route112_EventScript_Brice + 1,
    Route112_EventScript_Bryant + 1,
    Route112_EventScript_Carol + 1,
    Route112_EventScript_Larry + 1,
    Route112_EventScript_RematchTrent + 1,
    Route112_EventScript_Shayla + 1,
    Route112_EventScript_Trent + 1,
    Route113_EventScript_Coby + 1,
    Route113_EventScript_Dillon + 1,
    Route113_EventScript_Jaylen + 1,
    Route113_EventScript_Lao + 1,
    Route113_EventScript_Lawrence + 1,
    Route113_EventScript_Lung + 1,
    Route113_EventScript_Madeline + 1,
    Route113_EventScript_RematchLao + 1,
    Route113_EventScript_RematchMadeline + 1,
    Route113_EventScript_Sophie + 1,
    Route113_EventScript_Tia + 1,
    Route113_EventScript_Tori + 1,
    Route113_EventScript_Wyatt + 1,
    Route114_EventScript_Angelina + 1,
    Route114_EventScript_Bernie + 1,
    Route114_EventScript_Charlotte + 1,
    Route114_EventScript_Claude + 1,
    Route114_EventScript_Ivy + 1,
    Route114_EventScript_Kai + 1,
    Route114_EventScript_Lenny + 1,
    Route114_EventScript_Lucas + 1,
    Route114_EventScript_Nancy + 1,
    Route114_EventScript_Nolan + 1,
    Route114_EventScript_RematchBernie + 1,
    Route114_EventScript_RematchSteve + 1,
    Route114_EventScript_Shane + 1,
    Route114_EventScript_Steve + 1,
    Route114_EventScript_Tyra + 1,
    Route115_EventScript_Alix + 1,
    Route115_EventScript_Cyndy + 1,
    Route115_EventScript_Hector + 1,
    Route115_EventScript_Helene + 1,
    Route115_EventScript_Jaiden + 1,
    Route115_EventScript_Koichi + 1,
    Route115_EventScript_Kyra + 1,
    Route115_EventScript_Marlene + 1,
    Route115_EventScript_Nob + 1,
    Route115_EventScript_RematchCyndy + 1,
    Route115_EventScript_RematchNob + 1,
    Route115_EventScript_RematchTimothy + 1,
    Route115_EventScript_Timothy + 1,
    Route116_EventScript_Clark + 1,
    Route116_EventScript_Dawson + 1,
    Route116_EventScript_Devan + 1,
    Route116_EventScript_Janice + 1,
    Route116_EventScript_Jerry + 1,
    Route116_EventScript_Joey + 1,
    Route116_EventScript_Johnson + 1,
    Route116_EventScript_Jose + 1,
    Route116_EventScript_Karen + 1,
    Route116_EventScript_RematchJerry + 1,
    Route116_EventScript_RematchKaren + 1,
    Route116_EventScript_Sarah + 1,
    Route117_EventScript_Aisha + 1,
    Route117_EventScript_Anna + 1,
    Route117_EventScript_Brandi + 1,
    Route117_EventScript_Derek + 1,
    Route117_EventScript_Dylan + 1,
    Route117_EventScript_Isaac + 1,
    Route117_EventScript_Lydia + 1,
    Route117_EventScript_Maria + 1,
    Route117_EventScript_Meg + 1,
    Route117_EventScript_Melina + 1,
    Route117_EventScript_RematchAnna + 1,
    Route117_EventScript_RematchDylan + 1,
    Route117_EventScript_RematchIsaac + 1,
    Route117_EventScript_RematchLydia + 1,
    Route117_EventScript_RematchMaria + 1,
    Route117_EventScript_RematchMeg + 1,
    Route118_EventScript_Barny + 1,
    Route118_EventScript_Chester + 1,
    Route118_EventScript_Dalton + 1,
    Route118_EventScript_Deandre + 1,
    Route118_EventScript_Perry + 1,
    Route118_EventScript_RematchDalton + 1,
    Route118_EventScript_RematchRose + 1,
    Route118_EventScript_Rose + 1,
    Route118_EventScript_Wade + 1,
    Route119_EventScript_Brent + 1,
    Route119_EventScript_Catherine + 1,
    Route119_EventScript_Chris + 1,
    Route119_EventScript_Dayton + 1,
    Route119_EventScript_Donald + 1,
    Route119_EventScript_Doug + 1,
    Route119_EventScript_Fabian + 1,
    Route119_EventScript_Greg + 1,
    Route119_EventScript_Hideo + 1,
    Route119_EventScript_Hugh + 1,
    Route119_EventScript_Jackson + 1,
    Route119_EventScript_Kent + 1,
    Route119_EventScript_Phil + 1,
    Route119_EventScript_Rachel + 1,
    Route119_EventScript_RematchCatherine + 1,
    Route119_EventScript_RematchJackson + 1,
    Route119_EventScript_Takashi + 1,
    Route119_EventScript_Taylor + 1,
    Route119_EventScript_Yasu + 1,
    Route119_WeatherInstitute_1F_EventScript_Grunt1 + 1,
    Route119_WeatherInstitute_1F_EventScript_Grunt4 + 1,
    Route119_WeatherInstitute_2F_EventScript_Grunt2 + 1,
    Route119_WeatherInstitute_2F_EventScript_Grunt3 + 1,
    Route119_WeatherInstitute_2F_EventScript_Grunt5 + 1,
    Route11_EventScript_Fidel + 1,
    Route11_EventScript_Herman + 1,
    Route11_EventScript_Jason + 1,
    Route11_EventScript_Owen + 1,
    Route120_EventScript_Angelica + 1,
    Route120_EventScript_Callie + 1,
    Route120_EventScript_Chip + 1,
    Route120_EventScript_Clarissa + 1,
    Route120_EventScript_Colin + 1,
    Route120_EventScript_Jeffrey + 1,
    Route120_EventScript_Jenna + 1,
    Route120_EventScript_Jennifer + 1,
    Route120_EventScript_Keigo + 1,
    Route120_EventScript_Leonel + 1,
    Route120_EventScript_Lorenzo + 1,
    Route120_EventScript_RematchJeffrey + 1,
    Route120_EventScript_RematchRobert + 1,
    Route120_EventScript_Riley + 1,
    Route120_EventScript_Robert + 1,
    Route121_EventScript_Cale + 1,
    Route121_EventScript_Cristin + 1,
    Route121_EventScript_Jessica + 1,
    Route121_EventScript_Joy + 1,
    Route121_EventScript_Kate + 1,
    Route121_EventScript_Marcel + 1,
    Route121_EventScript_Myles + 1,
    Route121_EventScript_Pat + 1,
    Route121_EventScript_RematchCristin + 1,
    Route121_EventScript_RematchJessica + 1,
    Route121_EventScript_RematchWalter + 1,
    Route121_EventScript_Tammy + 1,
    Route121_EventScript_Vanessa + 1,
    Route121_EventScript_Walter + 1,
    Route123_EventScript_Alberto + 1,
    Route123_EventScript_Braxton + 1,
    Route123_EventScript_Cameron + 1,
    Route123_EventScript_Davis + 1,
    Route123_EventScript_Ed + 1,
    Route123_EventScript_Fernando + 1,
    Route123_EventScript_Frederick + 1,
    Route123_EventScript_Jacki + 1,
    Route123_EventScript_Jazmyn + 1,
    Route123_EventScript_Jonas + 1,
    Route123_EventScript_Kayley + 1,
    Route123_EventScript_Kindra + 1,
    Route123_EventScript_Miu + 1,
    Route123_EventScript_RematchCameron + 1,
    Route123_EventScript_RematchFernando + 1,
    Route123_EventScript_RematchJacki + 1,
    Route123_EventScript_Violet + 1,
    Route123_EventScript_Wendy + 1,
    Route123_EventScript_Yuki + 1,
    Route124_EventScript_Chad + 1,
    Route124_EventScript_Declan + 1,
    Route124_EventScript_Grace + 1,
    Route124_EventScript_Isabella + 1,
    Route124_EventScript_Jenny + 1,
    Route124_EventScript_Lila + 1,
    Route124_EventScript_RematchJenny + 1,
    Route124_EventScript_RematchLila + 1,
    Route124_EventScript_RematchRoy + 1,
    Route124_EventScript_Roland + 1,
    Route124_EventScript_Roy + 1,
    Route124_EventScript_Spencer + 1,
    Route125_EventScript_Auron + 1,
    Route125_EventScript_Ernest + 1,
    Route125_EventScript_Iris + 1,
    Route125_EventScript_Kim + 1,
    Route125_EventScript_Nolen + 1,
    Route125_EventScript_Presley + 1,
    Route125_EventScript_RematchErnest + 1,
    Route125_EventScript_Sharon + 1,
    Route125_EventScript_Stan + 1,
    Route125_EventScript_Tanya + 1,
    Route126_EventScript_Barry + 1,
    Route126_EventScript_Brenda + 1,
    Route126_EventScript_Dean + 1,
    Route126_EventScript_Isobel + 1,
    Route126_EventScript_Leonardo + 1,
    Route126_EventScript_Nikki + 1,
    Route126_EventScript_Pablo + 1,
    Route126_EventScript_RematchPablo + 1,
    Route126_EventScript_Sienna + 1,
    Route127_EventScript_Aidan + 1,
    Route127_EventScript_Athena + 1,
    Route127_EventScript_Camden + 1,
    Route127_EventScript_Donny + 1,
    Route127_EventScript_Henry + 1,
    Route127_EventScript_Jonah + 1,
    Route127_EventScript_Koji + 1,
    Route127_EventScript_RematchKoji + 1,
    Route127_EventScript_Roger + 1,
    Route128_EventScript_Alexa + 1,
    Route128_EventScript_Carlee + 1,
    Route128_EventScript_Harrison + 1,
    Route128_EventScript_Isaiah + 1,
    Route128_EventScript_Katelyn + 1,
    Route128_EventScript_RematchIsaiah + 1,
    Route128_EventScript_RematchKatelyn + 1,
    Route128_EventScript_Ruben + 1,
    Route128_EventScript_Wayne + 1,
    Route129_EventScript_Allison + 1,
    Route129_EventScript_Chase + 1,
    Route129_EventScript_Clarence + 1,
    Route129_EventScript_Reed + 1,
    Route129_EventScript_Tisha + 1,
    Route12_EventScript_Barney + 1,
    Route12_EventScript_Kyle + 1,
    Route12_EventScript_Martin + 1,
    Route12_EventScript_RematchKyle + 1,
    Route12_EventScript_Stephen + 1,
    Route130_EventScript_Katie + 1,
    Route130_EventScript_Rodney + 1,
    Route130_EventScript_Santiago + 1,
    Route131_EventScript_Herman + 1,
    Route131_EventScript_Ian + 1,
    Route131_EventScript_Kara + 1,
    Route131_EventScript_Kevin + 1,
    Route131_EventScript_Reli + 1,
    Route131_EventScript_Richard + 1,
    Route131_EventScript_Susie + 1,
    Route131_EventScript_Talia + 1,
    Route132_EventScript_Dana + 1,
    Route132_EventScript_Darcy + 1,
    Route132_EventScript_Gilbert + 1,
    Route132_EventScript_Jonathan + 1,
    Route132_EventScript_Kiyo + 1,
    Route132_EventScript_Makayla + 1,
    Route132_EventScript_Paxton + 1,
    Route132_EventScript_Ronald + 1,
    Route133_EventScript_Beck + 1,
    Route133_EventScript_Conor + 1,
    Route133_EventScript_Debra + 1,
    Route133_EventScript_Franklin + 1,
    Route133_EventScript_Linda + 1,
    Route133_EventScript_Mollie + 1,
    Route133_EventScript_Warren + 1,
    Route134_EventScript_Aaron + 1,
    Route134_EventScript_Alex + 1,
    Route134_EventScript_Hitoshi + 1,
    Route134_EventScript_Hudson + 1,
    Route134_EventScript_Jack + 1,
    Route134_EventScript_Kelvin + 1,
    Route134_EventScript_Laurel + 1,
    Route134_EventScript_Marley + 1,
    Route134_EventScript_Reyna + 1,
    Route13_EventScript_Alex + 1,
    Route13_EventScript_Bret + 1,
    Route13_EventScript_Joshua + 1,
    Route13_EventScript_Kenny + 1,
    Route13_EventScript_Perry + 1,
    Route13_EventScript_RematchAlex + 1,
    Route13_EventScript_RematchKenny + 1,
    Route14_EventScript_Carter + 1,
    Route14_EventScript_RematchCarter + 1,
    Route14_EventScript_RematchTrevor + 1,
    Route14_EventScript_Roy + 1,
    Route14_EventScript_Trevor + 1,
    Route15_EventScript_Billy + 1,
    Route15_EventScript_Colette + 1,
    Route15_EventScript_Hillary + 1,
    Route15_EventScript_Johnny + 1,
    Route15_EventScript_Kipp + 1,
    Route15_EventScript_RematchBilly + 1,
    Route15_EventScript_RematchHillary + 1,
    Route15_EventScript_Tommy + 1,
    Route17_EventScript_Charles + 1,
    Route17_EventScript_Glenn + 1,
    Route17_EventScript_Joel + 1,
    Route17_EventScript_RematchCharles + 1,
    Route17_EventScript_RematchJoel + 1,
    Route17_EventScript_RematchRiley + 1,
    Route17_EventScript_Riley + 1,
    Route18_EventScript_Bob + 1,
    Route18_EventScript_Boris + 1,
    Route19_EventScript_Dawn + 1,
    Route19_EventScript_Harold + 1,
    Route19_EventScript_Jerome + 1,
    Route19_EventScript_Tucker + 1,
    Route1_EventScript_Quinn + 1,
    Route1_EventScript_SchoolboyDanny + 1,
    Route20_EventScript_Cameron + 1,
    Route20_EventScript_Lori + 1,
    Route20_EventScript_Nicole + 1,
    Route20_EventScript_RematchNicole + 1,
    Route21_EventScript_Arnold + 1,
    Route21_EventScript_Nikki + 1,
    Route21_EventScript_Seth + 1,
    Route25_EventScript_Dudley + 1,
    Route25_EventScript_Ellen + 1,
    Route25_EventScript_Joe + 1,
    Route25_EventScript_Laura + 1,
    Route25_EventScript_Lloyd + 1,
    Route25_EventScript_Pat + 1,
    Route25_EventScript_Shannon + 1,
    Route26_EventScript_Beth + 1,
    Route26_EventScript_Gaven + 1,
    Route26_EventScript_Jake + 1,
    Route26_EventScript_Joyce + 1,
    Route26_EventScript_RematchBeth + 1,
    Route26_EventScript_RematchGaven + 1,
    Route26_EventScript_Richard + 1,
    Route27_EventScript_Blake + 1,
    Route27_EventScript_Brian + 1,
    Route27_EventScript_Gilbert + 1,
    Route27_EventScript_Jose + 1,
    Route27_EventScript_Megan + 1,
    Route27_EventScript_Reena + 1,
    Route27_EventScript_RematchJose + 1,
    Route27_EventScript_RematchReena + 1,
    Route27_EventScript_Scott + 1,
    Route2_EventScript_Doug + 1,
    Route2_EventScript_Ed + 1,
    Route2_EventScript_RematchRob + 1,
    Route2_EventScript_Rob + 1,
    Route30_EventScript_Bugcatcher_Don + 1,
    Route30_EventScript_RematchJoey + 1,
    Route30_EventScript_Youngster_Joey + 1,
    Route30_EventScript_Youngster_Mikey + 1,
    Route31_EventScript_Bugcatcher_Wade + 1,
    Route31_EventScript_RematchWade + 1,
    Route32_EventScript_BirdkeeperPeter + 1,
    Route32_EventScript_CamperRoland + 1,
    Route32_EventScript_FisherHenry + 1,
    Route32_EventScript_FisherJustin + 1,
    Route32_EventScript_FisherRalph + 1,
    Route32_EventScript_PicnickerLiz + 1,
    Route32_EventScript_RematchLiz + 1,
    Route32_EventScript_RematchRalph + 1,
    Route32_EventScript_YoungsterAlbert + 1,
    Route32_EventScript_YoungsterGordon + 1,
    Route33_EventScript_HikerAnthony + 1,
    Route33_EventScript_RematchAnthony + 1,
    Route34_EventScript_CamperTodd + 1,
    Route34_EventScript_Irene + 1,
    Route34_EventScript_Jenn + 1,
    Route34_EventScript_Kate + 1,
    Route34_EventScript_OfficerKeith + 1,
    Route34_EventScript_PicnickerGina + 1,
    Route34_EventScript_PokefanMBrandon + 1,
    Route34_EventScript_RematchGina + 1,
    Route34_EventScript_RematchTodd + 1,
    Route34_EventScript_YoungsterIan + 1,
    Route34_EventScript_YoungsterSamuel + 1,
    Route35_EventScript_BirdKeeperBryan + 1,
    Route35_EventScript_BugCatcherArnie + 1,
    Route35_EventScript_CamperElliot + 1,
    Route35_EventScript_CamperIvan + 1,
    Route35_EventScript_FirebreatherWalt + 1,
    Route35_EventScript_JugglerIrwin + 1,
    Route35_EventScript_PicnickerBrooke + 1,
    Route35_EventScript_PicnickerKim + 1,
    Route35_EventScript_PolicemanDirk + 1,
    Route35_EventScript_RematchArnie + 1,
    Route35_EventScript_RematchIrwin + 1,
    Route36_EventScript_Mark + 1,
    Route36_EventScript_RematchAlan + 1,
    Route36_EventScript_Schoolboy + 1,
    Route37_EventScript_Greg + 1,
    Route37_EventScript_TwinAnn + 1,
    Route37_EventScript_TwinAnne + 1,
    Route38_EventScript_Chad + 1,
    Route38_EventScript_Dana + 1,
    Route38_EventScript_Harry + 1,
    Route38_EventScript_Olivia + 1,
    Route38_EventScript_RematchChad + 1,
    Route38_EventScript_RematchDana + 1,
    Route38_EventScript_Toby + 1,
    Route38_EventScript_Valerie + 1,
    Route39_EventScript_Derek + 1,
    Route39_EventScript_Eugene + 1,
    Route39_EventScript_Jamie + 1,
    Route39_EventScript_Norman + 1,
    Route39_EventScript_RematchDerek + 1,
    Route39_EventScript_Ruth + 1,
    Route3_EventScript_Burt + 1,
    Route3_EventScript_Jimmy + 1,
    Route3_EventScript_Otis + 1,
    Route3_EventScript_Warren + 1,
    Route40_EventScript_Elaine + 1,
    Route40_EventScript_Paula + 1,
    Route40_EventScript_Randall + 1,
    Route40_EventScript_Simon + 1,
    Route41_EventScript_Berke + 1,
    Route41_EventScript_Charlie + 1,
    Route41_EventScript_Denise + 1,
    Route41_EventScript_George + 1,
    Route41_EventScript_Kara + 1,
    Route41_EventScript_Kaylee + 1,
    Route41_EventScript_Kirk + 1,
    Route41_EventScript_Mathew + 1,
    Route41_EventScript_Susie + 1,
    Route41_EventScript_Wendy + 1,
    Route42_EventScript_Ben + 1,
    Route42_EventScript_RematchTully + 1,
    Route42_EventScript_Shane + 1,
    Route42_EventScript_Tully + 1,
    Route43_EventScript_Ben + 1,
    Route43_EventScript_Brent + 1,
    Route43_EventScript_Marvin + 1,
    Route43_EventScript_RematchBrent + 1,
    Route43_EventScript_RematchTiffany + 1,
    Route43_EventScript_Ron + 1,
    Route43_EventScript_Spencer + 1,
    Route43_EventScript_Tiffany + 1,
    Route44_EventScript_Allen + 1,
    Route44_EventScript_Cybil + 1,
    Route44_EventScript_Edgar + 1,
    Route44_EventScript_Phil + 1,
    Route44_EventScript_RematchVance + 1,
    Route44_EventScript_RematchWilton + 1,
    Route44_EventScript_Vance + 1,
    Route44_EventScript_Wilton + 1,
    Route44_EventScript_Zach + 1,
    Route45_EventScript_Erik + 1,
    Route45_EventScript_Kelly + 1,
    Route45_EventScript_Kenji + 1,
    Route45_EventScript_Michael + 1,
    Route45_EventScript_Parry + 1,
    Route45_EventScript_Quentin + 1,
    Route45_EventScript_RematchKenji + 1,
    Route45_EventScript_RematchParry + 1,
    Route45_EventScript_Ryan + 1,
    Route45_EventScript_Timothy + 1,
    Route46_EventScript_Bailey + 1,
    Route46_EventScript_Erin + 1,
    Route46_EventScript_RematchErin + 1,
    Route46_EventScript_Ted + 1,
    Route47_EventScript_Camper + 1,
    Route47_EventScript_Duff + 1,
    Route47_EventScript_Eda + 1,
    Route47_EventScript_Hiker + 1,
    Route47_EventScript_Kae + 1,
    Route47_EventScript_Thom + 1,
    Route4_EventScript_Hank + 1,
    Route4_EventScript_Hope + 1,
    Route4_EventScript_Sharon + 1,
    Route6_EventScript_Allan + 1,
    Route6_EventScript_Rex + 1,
    Route8_EventScript_Dwayne + 1,
    Route8_EventScript_Harris + 1,
    Route8_EventScript_Sam + 1,
    Route8_EventScript_Tom + 1,
    Route8_EventScript_Zeke + 1,
    Route9_EventScript_Dean + 1,
    Route9_EventScript_Edna + 1,
    Route9_EventScript_Heidi + 1,
    Route9_EventScript_Sid + 1,
    Route9_EventScript_Sidney + 1,
    Route9_EventScript_Tim + 1,
    RuinsOfAlph_Outside_EventScript_Nathan + 1,
    RuinsOfAlph_Outside_EventScript_Stan + 1,
    RusturfTunnel_EventScript_Mike + 1,
    SSAqua_B1F_EventScript_Debra + 1,
    SSAqua_B1F_EventScript_Fritz + 1,
    SSAqua_B1F_EventScript_Garrett + 1,
    SSAqua_B1F_EventScript_Jeff + 1,
    SSAqua_B1F_EventScript_Jonah + 1,
    SSAqua_B1F_EventScript_Kenneth + 1,
    SSAqua_B1F_EventScript_Nate + 1,
    SSAqua_B1F_EventScript_Ricky + 1,
    SSAqua_B1F_EventScript_Shirley + 1,
    SSAqua_B1F_EventScript_Wai + 1,
    SSAqua_RoomNE_EventScript_Ethan + 1,
    SSAqua_RoomNE_EventScript_Noland + 1,
    SSAqua_RoomNNE_EventScript_Carol + 1,
    SSAqua_RoomNNE_EventScript_Sean + 1,
    SSAqua_RoomNW_EventScript_Corey + 1,
    SSAqua_RoomNW_EventScript_Edward + 1,
    SSAqua_RoomSE_EventScript_Colin + 1,
    SSAqua_RoomSE_EventScript_Meg + 1,
    SSAqua_RoomSE_EventScript_Peg + 1,
    SSAqua_RoomSSW_EventScript_Ken + 1,
    SSAqua_RoomSSW_EventScript_Lyle + 1,
    SSAqua_RoomSW_EventScript_Cassie + 1,
    SSAqua_RoomSW_EventScript_Clyde + 1,
    SSTidalLowerDeck_EventScript_Leonard + 1,
    SSTidalLowerDeck_EventScript_Phillip + 1,
    SSTidalRooms_EventScript_Colton + 1,
    SSTidalRooms_EventScript_Garret + 1,
    SSTidalRooms_EventScript_Jed + 1,
    SSTidalRooms_EventScript_Lea + 1,
    SSTidalRooms_EventScript_Micah + 1,
    SSTidalRooms_EventScript_Naomi + 1,
    SSTidalRooms_EventScript_Thomas + 1,
    SeafloorCavern_Room1_EventScript_Grunt1 + 1,
    SeafloorCavern_Room1_EventScript_Grunt2 + 1,
    SeafloorCavern_Room3_EventScript_Grunt5 + 1,
    SeafloorCavern_Room3_EventScript_Shelly + 1,
    SeafloorCavern_Room4_EventScript_Grunt3 + 1,
    SeafloorCavern_Room4_EventScript_Grunt4 + 1,
    SlowpokeWell_B1F_EventScript_Eto + 1,
    SlowpokeWell_B1F_EventScript_Grunt21 + 1,
    SlowpokeWell_B1F_EventScript_Grunt22F + 1,
    SproutTower_1F_EventScript_SageChow + 1,
    SproutTower_2F_EventScript_SageEdmond + 1,
    SproutTower_2F_EventScript_SageNico + 1,
    SproutTower_3F_EventScript_SageJin + 1,
    SproutTower_3F_EventScript_SageNeal + 1,
    SproutTower_3F_EventScript_SageTroy + 1,
    UnionCave_1F_EventScript_FirebreatherBill + 1,
    UnionCave_1F_EventScript_FirebreatherRay + 1,
    UnionCave_1F_EventScript_HikerDaniel + 1,
    UnionCave_1F_EventScript_HikerRussell + 1,
    UnionCave_1F_EventScript_PokemaniacLarry + 1,
    UnionCave_B1F_EventScript_HikerLeonard + 1,
    UnionCave_B1F_EventScript_HikerPhillip + 1,
    UnionCave_B1F_EventScript_PokemaniacAndrew + 1,
    UnionCave_B1F_EventScript_PokemaniacCalvin + 1,
    UnionCave_B2F_EventScript_CooltrainerNick + 1,
    UnionCave_B2F_EventScript_CooltrainerfEmma + 1,
    UnionCave_B2F_EventScript_CooltrainerfGwen + 1,
    VictoryRoad_1F_EventScript_Albert + 1,
    VictoryRoad_1F_EventScript_Edgar + 1,
    VictoryRoad_1F_EventScript_Hope + 1,
    VictoryRoad_1F_EventScript_Katelynn + 1,
    VictoryRoad_1F_EventScript_Quincy + 1,
    VictoryRoad_B1F_EventScript_Halle + 1,
    VictoryRoad_B1F_EventScript_Michelle + 1,
    VictoryRoad_B1F_EventScript_Mitchell + 1,
    VictoryRoad_B1F_EventScript_Samuel + 1,
    VictoryRoad_B1F_EventScript_Shannon + 1,
    VictoryRoad_B2F_EventScript_Caroline + 1,
    VictoryRoad_B2F_EventScript_Dianne + 1,
    VictoryRoad_B2F_EventScript_Felix + 1,
    VictoryRoad_B2F_EventScript_Julie + 1,
    VictoryRoad_B2F_EventScript_Owen + 1,
    VictoryRoad_B2F_EventScript_Vito + 1,
};
const u8 gWayfarerStoryOrdinaryMetadata[] =
{
    0x3C,
    0x38,
    0x28,
    0x08,
    0x38,
    0x3C,
    0x28,
    0x08,
    0x34,
    0x34,
    0x14,
    0x38,
    0x3C,
    0x34,
    0x30,
    0x34,
    0x3C,
    0x34,
    0x30,
    0x3C,
    0x38,
    0x30,
    0x38,
    0x3C,
    0x34,
    0x38,
    0x30,
    0x3C,
    0x30,
    0x34,
    0x39,
    0x39,
    0x39,
    0x39,
    0x35,
    0x35,
    0x39,
    0x31,
    0x34,
    0x34,
    0x38,
    0x30,
    0x24,
    0x24,
    0x24,
    0x24,
    0x2C,
    0x2C,
    0x24,
    0x20,
    0x24,
    0x24,
    0x2C,
    0x2C,
    0x24,
    0x20,
    0x32,
    0x3E,
    0x36,
    0x3A,
    0x3C,
    0x3C,
    0x32,
    0x32,
    0x3A,
    0x32,
    0x36,
    0x36,
    0x36,
    0x3A,
    0x36,
    0x36,
    0x32,
    0x3E,
    0x3E,
    0x3A,
    0x38,
    0x34,
    0x3C,
    0x34,
    0x34,
    0x34,
    0x30,
    0x10,
    0x30,
    0x34,
    0x14,
    0x3C,
    0x3C,
    0x30,
    0x38,
    0x34,
    0x37,
    0x33,
    0x33,
    0x33,
    0x33,
    0x37,
    0x3F,
    0x37,
    0x37,
    0x3F,
    0x37,
    0x33,
    0x37,
    0x37,
    0x33,
    0x3B,
    0x33,
    0x28,
    0x28,
    0x34,
    0x08,
    0x08,
    0x14,
    0x3B,
    0x3B,
    0x3B,
    0x33,
    0x3F,
    0x30,
    0x10,
    0x34,
    0x14,
    0x38,
    0x30,
    0x3C,
    0x3B,
    0x34,
    0x30,
    0x38,
    0x2C,
    0x3C,
    0x2C,
    0x30,
    0x30,
    0x30,
    0x3C,
    0x10,
    0x34,
    0x3C,
    0x34,
    0x34,
    0x18,
    0x38,
    0x35,
    0x39,
    0x35,
    0x39,
    0x34,
    0x3C,
    0x38,
    0x14,
    0x1C,
    0x38,
    0x34,
    0x38,
    0x34,
    0x3C,
    0x30,
    0x30,
    0x10,
    0x30,
    0x34,
    0x3C,
    0x34,
    0x14,
    0x3C,
    0x32,
    0x32,
    0x36,
    0x3E,
    0x3A,
    0x36,
    0x3E,
    0x38,
    0x08,
    0x38,
    0x18,
    0x08,
    0x38,
    0x38,
    0x28,
    0x34,
    0x38,
    0x3C,
    0x28,
    0x38,
    0x3C,
    0x1C,
    0x3C,
    0x38,
    0x34,
    0x30,
    0x34,
    0x28,
    0x34,
    0x3C,
    0x28,
    0x10,
    0x14,
    0x18,
    0x38,
    0x30,
    0x10,
    0x34,
    0x34,
    0x34,
    0x30,
    0x30,
    0x3C,
    0x3C,
    0x30,
    0x10,
    0x30,
    0x30,
    0x30,
    0x38,
    0x30,
    0x34,
    0x24,
    0x24,
    0x3C,
    0x1C,
    0x3C,
    0x34,
    0x14,
    0x3C,
    0x30,
    0x38,
    0x38,
    0x3C,
    0x30,
    0x30,
    0x38,
    0x30,
    0x38,
    0x3C,
    0x3C,
    0x34,
    0x34,
    0x30,
    0x10,
    0x24,
    0x24,
    0x38,
    0x18,
    0x30,
    0x30,
    0x38,
    0x38,
    0x34,
    0x3C,
    0x1C,
    0x34,
    0x3C,
    0x34,
    0x14,
    0x34,
    0x3C,
    0x34,
    0x14,
    0x38,
    0x18,
    0x34,
    0x38,
    0x30,
    0x38,
    0x3C,
    0x38,
    0x38,
    0x34,
    0x38,
    0x38,
    0x34,
    0x38,
    0x38,
    0x30,
    0x34,
    0x38,
    0x38,
    0x30,
    0x30,
    0x34,
    0x3C,
    0x3C,
    0x30,
    0x30,
    0x3C,
    0x38,
    0x3C,
    0x3C,
    0x3C,
    0x38,
    0x34,
    0x38,
    0x34,
    0x30,
    0x34,
    0x34,
    0x3C,
    0x3C,
    0x3C,
    0x38,
    0x38,
    0x38,
    0x38,
    0x3C,
    0x14,
    0x18,
    0x18,
    0x38,
    0x30,
    0x38,
    0x3C,
    0x3C,
    0x30,
    0x30,
    0x14,
    0x34,
    0x34,
    0x38,
    0x34,
    0x30,
    0x30,
    0x34,
    0x34,
    0x38,
    0x10,
    0x18,
    0x34,
    0x24,
    0x24,
    0x3C,
    0x3C,
    0x3C,
    0x3C,
    0x38,
    0x28,
    0x30,
    0x3C,
    0x38,
    0x34,
    0x3C,
    0x1C,
    0x14,
    0x30,
    0x34,
    0x28,
    0x34,
    0x38,
    0x34,
    0x3C,
    0x30,
    0x34,
    0x34,
    0x3C,
    0x38,
    0x18,
    0x18,
    0x10,
    0x30,
    0x30,
    0x34,
    0x34,
    0x3C,
    0x38,
    0x34,
    0x3C,
    0x38,
    0x38,
    0x18,
    0x18,
    0x38,
    0x3C,
    0x2C,
    0x3C,
    0x38,
    0x30,
    0x3C,
    0x34,
    0x34,
    0x2C,
    0x30,
    0x0C,
    0x10,
    0x1C,
    0x14,
    0x14,
    0x0C,
    0x34,
    0x38,
    0x34,
    0x30,
    0x38,
    0x14,
    0x18,
    0x38,
    0x34,
    0x34,
    0x3C,
    0x38,
    0x30,
    0x34,
    0x3C,
    0x30,
    0x38,
    0x30,
    0x3C,
    0x3C,
    0x30,
    0x38,
    0x34,
    0x1C,
    0x1C,
    0x34,
    0x30,
    0x38,
    0x35,
    0x39,
    0x31,
    0x39,
    0x3D,
    0x38,
    0x30,
    0x34,
    0x34,
    0x3C,
    0x3C,
    0x38,
    0x34,
    0x38,
    0x34,
    0x34,
    0x3C,
    0x30,
    0x3C,
    0x30,
    0x14,
    0x18,
    0x30,
    0x38,
    0x34,
    0x3C,
    0x34,
    0x28,
    0x28,
    0x38,
    0x30,
    0x38,
    0x1C,
    0x14,
    0x18,
    0x3C,
    0x3C,
    0x38,
    0x3C,
    0x30,
    0x34,
    0x3C,
    0x38,
    0x38,
    0x34,
    0x3C,
    0x34,
    0x38,
    0x30,
    0x30,
    0x20,
    0x14,
    0x18,
    0x1C,
    0x34,
    0x3C,
    0x20,
    0x34,
    0x38,
    0x3C,
    0x38,
    0x34,
    0x28,
    0x14,
    0x08,
    0x08,
    0x38,
    0x28,
    0x38,
    0x30,
    0x34,
    0x28,
    0x28,
    0x34,
    0x38,
    0x14,
    0x30,
    0x34,
    0x30,
    0x38,
    0x30,
    0x30,
    0x3C,
    0x34,
    0x3C,
    0x34,
    0x14,
    0x3C,
    0x34,
    0x3C,
    0x3C,
    0x38,
    0x38,
    0x38,
    0x38,
    0x18,
    0x38,
    0x3C,
    0x3C,
    0x3C,
    0x30,
    0x3C,
    0x10,
    0x1C,
    0x38,
    0x30,
    0x38,
    0x30,
    0x38,
    0x34,
    0x3C,
    0x34,
    0x3C,
    0x34,
    0x1C,
    0x38,
    0x34,
    0x30,
    0x30,
    0x3C,
    0x28,
    0x38,
    0x38,
    0x28,
    0x3C,
    0x3C,
    0x38,
    0x30,
    0x38,
    0x38,
    0x34,
    0x34,
    0x34,
    0x3C,
    0x3C,
    0x30,
    0x3C,
    0x38,
    0x34,
    0x34,
    0x34,
    0x38,
    0x34,
    0x30,
    0x34,
    0x38,
    0x38,
    0x38,
    0x38,
    0x34,
    0x34,
    0x30,
    0x3C,
    0x3C,
    0x34,
    0x38,
    0x10,
    0x14,
    0x30,
    0x10,
    0x10,
    0x34,
    0x30,
    0x38,
    0x34,
    0x30,
    0x34,
    0x34,
    0x18,
    0x10,
    0x3C,
    0x3C,
    0x34,
    0x38,
    0x1C,
    0x18,
    0x14,
    0x34,
    0x38,
    0x34,
    0x30,
    0x34,
    0x30,
    0x34,
    0x3C,
    0x34,
    0x30,
    0x3C,
    0x30,
    0x10,
    0x30,
    0x3C,
    0x38,
    0x34,
    0x38,
    0x30,
    0x38,
    0x38,
    0x38,
    0x3C,
    0x38,
    0x34,
    0x34,
    0x30,
    0x18,
    0x14,
    0x34,
    0x38,
    0x38,
    0x34,
    0x30,
    0x30,
    0x3C,
    0x10,
    0x1C,
    0x34,
    0x3C,
    0x3C,
    0x10,
    0x30,
    0x3C,
    0x10,
    0x30,
    0x30,
    0x3C,
    0x1C,
    0x30,
    0x34,
    0x38,
    0x3C,
    0x3C,
    0x30,
    0x10,
    0x1C,
    0x38,
    0x3C,
    0x34,
    0x14,
    0x38,
    0x38,
    0x3C,
    0x38,
    0x34,
    0x30,
    0x3C,
    0x10,
    0x18,
    0x30,
    0x34,
    0x3C,
    0x38,
    0x34,
    0x30,
    0x34,
    0x38,
    0x30,
    0x38,
    0x34,
    0x18,
    0x18,
    0x3C,
    0x18,
    0x38,
    0x30,
    0x20,
    0x20,
    0x30,
    0x30,
    0x38,
    0x34,
    0x10,
    0x10,
    0x3C,
    0x3C,
    0x34,
    0x34,
    0x30,
    0x30,
    0x14,
    0x30,
    0x38,
    0x30,
    0x30,
    0x38,
    0x30,
    0x3C,
    0x30,
    0x30,
    0x3C,
    0x34,
    0x38,
    0x38,
    0x38,
    0x30,
    0x34,
    0x38,
    0x3C,
    0x34,
    0x38,
    0x18,
    0x38,
    0x38,
    0x3C,
    0x38,
    0x3C,
    0x18,
    0x14,
    0x34,
    0x34,
    0x34,
    0x34,
    0x30,
    0x38,
    0x30,
    0x14,
    0x14,
    0x34,
    0x34,
    0x34,
    0x34,
    0x3C,
    0x3C,
    0x34,
    0x34,
    0x38,
    0x1C,
    0x14,
    0x34,
    0x38,
    0x30,
    0x38,
    0x18,
    0x38,
    0x34,
    0x28,
    0x28,
    0x30,
    0x24,
    0x24,
    0x34,
    0x38,
    0x34,
    0x34,
    0x34,
    0x38,
    0x34,
    0x30,
    0x34,
    0x3C,
    0x38,
    0x3C,
    0x30,
    0x34,
    0x34,
    0x38,
    0x38,
    0x38,
    0x3C,
    0x3C,
    0x3C,
    0x3C,
    0x34,
    0x30,
    0x34,
    0x3C,
    0x3C,
    0x34,
    0x38,
    0x34,
    0x3C,
    0x38,
    0x38,
    0x34,
    0x38,
    0x38,
    0x28,
    0x28,
    0x30,
    0x34,
    0x38,
    0x3C,
    0x30,
    0x30,
    0x3C,
    0x3C,
    0x20,
    0x20,
    0x38,
    0x38,
    0x30,
    0x31,
    0x39,
    0x35,
    0x35,
    0x3D,
    0x31,
    0x36,
    0x36,
    0x3A,
    0x3C,
    0x30,
    0x34,
    0x34,
    0x3C,
    0x30,
    0x34,
    0x38,
    0x3C,
    0x3C,
    0x38,
    0x34,
    0x38,
    0x30,
    0x38,
    0x38,
    0x3C,
    0x3C,
    0x38,
    0x38,
    0x38,
    0x38,
    0x34,
    0x38,
    0x3C,
    0x3C,
    0x3C,
    0x38,
    0x34,
    0x30,
    0x30,
    0x30,
    0x30,
    0x30,
};
const u32 gWayfarerStoryOrdinaryEncounterCount = ARRAY_COUNT(gWayfarerStoryOrdinaryCallers);
#else
const u8 *const gWayfarerStoryOrdinaryCallers[] = {NULL};
const u8 gWayfarerStoryOrdinaryMetadata[] = {0};
const u32 gWayfarerStoryOrdinaryEncounterCount = 0;
#endif
