#!/usr/bin/env python3
"""Validate League sources and generate explicit metadata and level inventory."""
import argparse
import json
from pathlib import Path
import generate

OUT = generate.OUTPUT
ANCHORS = ((0,15),(4,16),(8,18),(16,23),(30,30),(40,42),(55,60),(65,80),(80,100))
# Trainer, ace species, source-order offsets. Never derive offsets from old levels.
ROSTERS = (
 ('WILL_1_HNS','XATU',(-2,-1,-2,-1,0)),
 ('KOGA_1_HNS','CROBAT',(-2,-1,-2,-1,0)),
 ('BRUNO_1_HNS','MACHAMP',(-1,-2,-1,-1,0)),
 ('KAREN_1_HNS','HOUNDOOM',(-1,-2,-2,-2,0)),
 ('LANCE_1_HNS','DRAGONITE',(-2,-1,-2,-1,-2,0)),
 ('WILL_2_HNS','XATU',(-2,-1,-1,-1,-2,0)),
 ('KOGA_2_HNS','CROBAT',(-1,-1,-1,-1,-1,0)),
 ('BRUNO_2_HNS','MACHAMP',(-1,-1,-1,-1,-1,0)),
 ('KAREN_2_HNS','HOUNDOOM',(-1,-2,-1,-1,-2,0)),
 ('LANCE_2_HNS','ALTARIA',(-1,-2,-1,-2,-1,0)),
 ('SIDNEY','ABSOL',(-1,-1,-1,-1,0)),
 ('PHOEBE','DUSCLOPS',(-1,-1,-1,-1,0)),
 ('GLACIA','WALREIN',(-1,-1,-1,-1,0)),
 ('DRAKE','SALAMENCE',(-1,-1,-1,-1,0)),
 ('WALLACE','MILOTIC',(-1,-2,-1,-1,-1,0)),
)

def baseline(rating):
    rating = min(max(rating, 0), 80)
    for (r0,l0),(r1,l1) in zip(ANCHORS,ANCHORS[1:]):
        if rating <= r1:
            width = r1-r0
            return l0 + (2*(rating-r0)*(l1-l0)+width)//(2*width)

def inventory():
    sources = generate.load_inventory()
    rows = []
    for i,(name,ace,offsets) in enumerate(ROSTERS):
        trainer = 'TRAINER_'+name
        assert set(sources[trainer]) == {'DIFFICULTY_NORMAL'}, f'{trainer}: difficulty resolver needs metadata review'
        source = sources[trainer]['DIFFICULTY_NORMAL']
        assert not source.get('overrideTrainer'), trainer
        slots = source['slots']
        assert source['partySize'] == len(slots) == len(offsets), trainer
        assert slots[-1]['species'] == 'SPECIES_'+ace, trainer
        assert all(len(slot.get('moves',[])) == 4 for slot in slots), trainer
        encounter = (-4,-3,-2,-1,1)[i%5]
        rows.append(dict(trainer=trainer, owner=trainer, region=('KANTO','JOHTO','HOENN')[i//5],
                         difficulty='DIFFICULTY_NORMAL', encounterIndex=i%5, encounterOffset=encounter,
                         aceSlot=len(slots)-1, offsets=offsets, source=source,
                         levels=[[min(max(baseline(tr)+encounter+offset,1),100) for offset in offsets] for tr in range(81)]))
    return rows

def render(rows):
    lines = ['// Generated by tools/trainer_scaling/league.py.', 'static const struct LeagueScalingRoster sLeagueScalingRosters[] =', '{']
    for row in rows:
        lines += ['    {', f"        .trainerId = {row['trainer']}, .ownerId = {row['owner']},",
                  f"        .region = REGION_{row['region']}, .difficulty = DIFFICULTY_NORMAL,",
                  f"        .encounterIndex = {row['encounterIndex']}, .encounterOffset = {row['encounterOffset']},",
                  f"        .count = {len(row['offsets'])}, .aceSlot = {row['aceSlot']},",
                  '        .offsets = { '+', '.join(map(str,row['offsets']))+' },',
                  '        .species = { '+', '.join(s['species'] for s in row['source']['slots'])+' },',
                  '        .items = { '+', '.join(s.get('heldItem','ITEM_NONE') for s in row['source']['slots'])+' },',
                  '        .moves = {']
        lines += ['            { '+', '.join(s['moves'])+' },' for s in row['source']['slots']]
        lines += ['        },','    },']
    return '\n'.join(lines+['};',''])

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check',action='store_true')
    args = parser.parse_args()
    rows=inventory()
    # A reviewed fixture pins all non-level source fields, including AI and inventory.
    fixture=Path(__file__).with_name('league_sources.json')
    actual=[dict(trainer=r['trainer'],source=r['source']) for r in rows]
    if json.loads(fixture.read_text()) != actual:
        raise generate.ValidationError('League source identity changed; explicit metadata review required')
    outputs={'league.h':render(rows),'league.json':json.dumps(rows,indent=2)+'\n'}
    for name,contents in outputs.items():
        path=OUT/name
        if args.check:
            if path.read_text()!=contents:
                raise generate.ValidationError(f'stale {path}')
        else:
            path.write_text(contents)
    print('Validated 15 fixed League rosters, all authored fields, and 81 rating inventories')

if __name__=='__main__':
    main()
