#!/usr/bin/env python3
"""Validate the reviewed ordinary caller allowlist and render its C registry.

New scripts are never enrolled automatically. Changing a reviewed command block
requires updating its audit fingerprint in ordinary.json after reviewing routing.
"""

import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools/wayfarer_hoenn_content"))
from generate import script_symbols, strip_asm_comments  # noqa: E402

REGIONAL_SPEC = importlib.util.spec_from_file_location(
    "wayfarer_story_encounters_generate_regional",
    Path(__file__).with_name("generate_regional.py"),
)
assert REGIONAL_SPEC is not None and REGIONAL_SPEC.loader is not None
REGIONAL_GENERATOR = importlib.util.module_from_spec(REGIONAL_SPEC)
REGIONAL_SPEC.loader.exec_module(REGIONAL_GENERATOR)


def commands(body):
    return [line.strip() for line in strip_asm_comments(body).splitlines()
            if line.strip() and not line.strip().startswith("#")
            and not line.strip().endswith(":")]


def fingerprint(body):
    return hashlib.sha256("\n".join(commands(body)).encode()).hexdigest()


ORDINARY_DIALOGUE_CODES = {
    "ORDINARY": 0,
    "AQUA_GUARD": 1,
    "ROCKET_GUARD": 2,
    "MAGMA_GUARD": 3,
}


def pack_metadata(row):
    """Pack the only ordinary runtime fields, rejecting lossy source rows."""
    stable_key = row["stableKey"]
    dialogue = row["dialogue"]
    loss_return = row["lossReturn"]
    if not isinstance(stable_key, int) or not 0 <= stable_key <= 0xFFFF:
        raise ValueError(f"stableKey outside u16 range: {row['caller']}")
    if dialogue not in ORDINARY_DIALOGUE_CODES:
        raise ValueError(f"unsupported ordinary dialogue: {row['caller']}: {dialogue}")
    if type(loss_return) is not bool:
        raise ValueError(f"lossReturn must be boolean: {row['caller']}")
    post_battle_text = not row["command"].startswith("trainerbattle_rematch")
    return (ORDINARY_DIALOGUE_CODES[dialogue]
            | ((stable_key % 4) << 2)
            | (0x10 if loss_return else 0)
            | (0x20 if post_battle_text else 0))


def unpack_metadata(metadata):
    if not isinstance(metadata, int) or not 0 <= metadata <= 0x3F:
        raise ValueError(f"ordinary metadata outside packed range: {metadata}")
    dialogue = metadata & 0x03
    return {
        "dialogue": next(name for name, code in ORDINARY_DIALOGUE_CODES.items() if code == dialogue),
        "stableKeyModulo4": (metadata >> 2) & 0x03,
        "lossReturn": bool(metadata & 0x10),
        "allowPostBattleText": bool(metadata & 0x20),
    }


def render(rows):
    lines = ["// Generated by tools/wayfarer_story_encounters/generate.py.",
             "// Only reviewed callers in ordinary.json authorize field loss return.",
             "#if IS_WAYFARER",
             "extern const u8 EventScript_WayfarerStoryLossRetreat[];"]
    lines += [f'extern const u8 {row["caller"]}[];' for row in rows]
    lines += ["const u8 *const gWayfarerStoryOrdinaryCallers[] =", "{"]
    for row in rows:
        lines += [f'    {row["caller"]} + 1,']
    lines += ["};", "const u8 gWayfarerStoryOrdinaryMetadata[] =", "{"]
    lines += [f"    0x{pack_metadata(row):02X}," for row in rows]
    lines += ["};", "const u32 gWayfarerStoryOrdinaryEncounterCount = ARRAY_COUNT(gWayfarerStoryOrdinaryCallers);",
              "#else", "const u8 *const gWayfarerStoryOrdinaryCallers[] = {NULL};", "const u8 gWayfarerStoryOrdinaryMetadata[] = {0};",
              "const u32 gWayfarerStoryOrdinaryEncounterCount = 0;", "#endif", ""]
    return "\n".join(lines)


def validate_rematch_dialogue_identities(rows):
    """Require each rematch to reuse its reviewed base caller identity."""
    base_dialogues = {}
    for row in rows:
        if row["command"].startswith("trainerbattle_rematch"):
            continue
        identity = (row["stableKey"], row["dialogue"])
        base_dialogues.setdefault(row["baseTrainer"], set()).add(identity)
    for row in rows:
        if not row["command"].startswith("trainerbattle_rematch"):
            continue
        identities = base_dialogues.get(row["baseTrainer"], set())
        if len(identities) != 1 or (row["stableKey"], row["dialogue"]) not in identities:
            raise ValueError(f"rematch dialogue must match one stable base caller: {row['caller']}")


def validate_regional_caller_ownership(ordinary_callers, regional_sources):
    """Keep every exact trainerbattle caller in exactly one logical registry."""
    for region, source in regional_sources.items():
        regional_callers = {
            caller.removesuffix(" + 1") for caller, _ in REGIONAL_GENERATOR.logical_rows(region, source)
            if caller != "NULL"
        }
        overlap = ordinary_callers.intersection(regional_callers)
        if overlap:
            raise ValueError(f"ordinary/{region} caller ownership overlaps: {sorted(overlap)}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    manifest = json.loads(Path(__file__).with_name("ordinary.json").read_text())
    rows = manifest["callers"]
    _, _, blocks = script_symbols(ROOT)
    seen = set()
    for row in rows:
        caller = row["caller"]
        if caller in seen:
            raise ValueError(f"duplicate caller: {caller}")
        seen.add(caller)
        path, body, _ = blocks[caller]
        if str(path.relative_to(ROOT)) != row["source"]:
            raise ValueError(f"caller moved: {caller}")
        if fingerprint(body) != row["reviewedCommandsSha256"]:
            raise ValueError(f"caller changed; review before renewing audit: {caller}")
        first = commands(body)[0]
        if first != row["command"]:
            raise ValueError(f"caller must point directly to reviewed trainerbattle: {caller}")
        mode = first.split()[0]
        if mode not in ("trainerbattle_single", "trainerbattle_rematch", "trainerbattle_double", "trainerbattle_rematch_double"):
            raise ValueError(f"unaudited mode: {caller}")
        if row["lossReturn"] and mode not in ("trainerbattle_single", "trainerbattle_rematch"):
            raise ValueError(f"exceptional double loss return: {caller}")
        if "Gym" in row["source"]:
            raise ValueError(f"Gym caller requires its own audit: {caller}")
        pack_metadata(row)

    # A rematch is a later caller for the same encounter, not a new dialogue
    # assignment. Keep the frozen base key and its explicit tone together in
    # the reviewed manifest so a row cannot drift when its macro is re-audited.
    validate_rematch_dialogue_identities(rows)
    validate_regional_caller_ownership(seen, {
        region: (ROOT / f"src/data/wayfarer_story_encounter_{region}_entries.inc").read_text()
        for region in ("johto", "hoenn")
    })
    output = ROOT / "src/data/wayfarer_story_encounter_ordinary.h"
    generated = render(rows)
    if args.check:
        if output.read_text() != generated:
            raise ValueError("ordinary registry is stale; run generator")
    else:
        output.write_text(generated)
    print(f"Validated {len(rows)} explicit ordinary callers; {sum(row['lossReturn'] for row in rows)} field-loss redirects.")


if __name__ == "__main__":
    main()
