#!/usr/bin/env python3
"""Validate the reviewed ordinary caller allowlist and render its C registry.

New scripts are never enrolled automatically. Changing a reviewed command block
requires updating its audit fingerprint in ordinary.json after reviewing routing.
"""

import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools/wayfarer_hoenn_content"))
from generate import script_symbols, strip_asm_comments  # noqa: E402


def commands(body):
    return [line.strip() for line in strip_asm_comments(body).splitlines()
            if line.strip() and not line.strip().startswith("#")
            and not line.strip().endswith(":")]


def fingerprint(body):
    return hashlib.sha256("\n".join(commands(body)).encode()).hexdigest()


def render(rows):
    lines = ["// Generated by tools/wayfarer_story_encounters/generate.py.",
             "// Only reviewed callers in ordinary.json authorize field loss return.",
             "#if IS_WAYFARER",
             "extern const u8 EventScript_WayfarerStoryLossRetreat[];"]
    lines += [f'extern const u8 {row["caller"]}[];' for row in rows]
    lines += ["#define ORDINARY_ENTRY(_caller, _key, _dialogue, _flags) \\",
              "    { .caller = (_caller) + 1, .stableKey = (_key), \\",
              "      .dialogue = WAYFARER_STORY_DIALOGUE_ ## _dialogue, .flags = (_flags) },",
              "const struct WayfarerOrdinaryEncounter gWayfarerStoryOrdinaryEncounters[] =", "{"]
    for row in rows:
        loss = row["lossReturn"]
        flags = []
        if not row["command"].startswith("trainerbattle_rematch"):
            flags.append("WAYFARER_STORY_FLAG_ALLOW_POST_BATTLE_TEXT")
        if loss:
            flags.append("WAYFARER_STORY_FLAG_LOSS_RETURN")
        flag_expr = " | ".join(flags) or "0"
        lines += [f'    ORDINARY_ENTRY({row["caller"]}, {row["stableKey"]}, {row["dialogue"]}, {flag_expr})']
    lines += ["};", "const u32 gWayfarerStoryOrdinaryEncounterCount = ARRAY_COUNT(gWayfarerStoryOrdinaryEncounters);",
              "#undef ORDINARY_ENTRY", "#else", "const struct WayfarerOrdinaryEncounter gWayfarerStoryOrdinaryEncounters[] = {{0}};",
              "const u32 gWayfarerStoryOrdinaryEncounterCount = 0;", "#endif", ""]
    return "\n".join(lines)


def validate_rematch_dialogue_identities(rows):
    """Require each rematch to reuse its reviewed base caller identity."""
    base_dialogues = {}
    for row in rows:
        if row["command"].startswith("trainerbattle_rematch"):
            continue
        identity = (row["stableKey"], row["dialogue"])
        base_dialogues.setdefault(row["baseTrainer"], set()).add(identity)
    for row in rows:
        if not row["command"].startswith("trainerbattle_rematch"):
            continue
        identities = base_dialogues.get(row["baseTrainer"], set())
        if len(identities) != 1 or (row["stableKey"], row["dialogue"]) not in identities:
            raise ValueError(f"rematch dialogue must match one stable base caller: {row['caller']}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    manifest = json.loads(Path(__file__).with_name("ordinary.json").read_text())
    rows = manifest["callers"]
    _, _, blocks = script_symbols(ROOT)
    seen = set()
    for row in rows:
        caller = row["caller"]
        if caller in seen:
            raise ValueError(f"duplicate caller: {caller}")
        seen.add(caller)
        path, body, _ = blocks[caller]
        if str(path.relative_to(ROOT)) != row["source"]:
            raise ValueError(f"caller moved: {caller}")
        if fingerprint(body) != row["reviewedCommandsSha256"]:
            raise ValueError(f"caller changed; review before renewing audit: {caller}")
        first = commands(body)[0]
        if first != row["command"]:
            raise ValueError(f"caller must point directly to reviewed trainerbattle: {caller}")
        mode = first.split()[0]
        if mode not in ("trainerbattle_single", "trainerbattle_rematch", "trainerbattle_double", "trainerbattle_rematch_double"):
            raise ValueError(f"unaudited mode: {caller}")
        if row["lossReturn"] and mode not in ("trainerbattle_single", "trainerbattle_rematch"):
            raise ValueError(f"exceptional double loss return: {caller}")
        if "Gym" in row["source"]:
            raise ValueError(f"Gym caller requires its own audit: {caller}")

    # A rematch is a later caller for the same encounter, not a new dialogue
    # assignment. Keep the frozen base key and its explicit tone together in
    # the reviewed manifest so a row cannot drift when its macro is re-audited.
    validate_rematch_dialogue_identities(rows)
    for region, pattern in (
        ("johto", r"^\s*WAYFARER_JOHTO_ENTRY\((\w+),"),
        ("hoenn", r"^\s*HOENN_ENTRY\((\w+) \+ 1,"),
    ):
        regional = (ROOT / f"src/data/wayfarer_story_encounter_{region}.h").read_text()
        overlap = seen.intersection(re.findall(pattern, regional, re.MULTILINE))
        if overlap:
            raise ValueError(f"ordinary/{region} caller ownership overlaps: {sorted(overlap)}")
    output = ROOT / "src/data/wayfarer_story_encounter_ordinary.h"
    generated = render(rows)
    if args.check:
        if output.read_text() != generated:
            raise ValueError("ordinary registry is stale; run generator")
    else:
        output.write_text(generated)
    print(f"Validated {len(rows)} explicit ordinary callers; {sum(row['lossReturn'] for row in rows)} field-loss redirects.")


if __name__ == "__main__":
    main()
