#!/usr/bin/env python3
"""Import the five FRLG first-clear Indigo Trainers under Wayfarer-owned IDs."""

from __future__ import annotations

import argparse
import importlib.util
from pathlib import Path

GAME = Path(__file__).resolve().parents[2]
COAST_PATH = GAME / "tools/wayfarer_coast_trainers/generate.py"
_coast_spec = importlib.util.spec_from_file_location("wayfarer_coast_trainer_generator", COAST_PATH)
coast = importlib.util.module_from_spec(_coast_spec)
_coast_spec.loader.exec_module(coast)

BASE = 1795
SOURCES = (
    ("LORELEI", "TRAINER_ELITE_FOUR_LORELEI"),
    ("BRUNO", "TRAINER_ELITE_FOUR_BRUNO"),
    ("AGATHA", "TRAINER_ELITE_FOUR_AGATHA"),
    ("LANCE", "TRAINER_ELITE_FOUR_LANCE"),
    ("BLUE", "TRAINER_CHAMPION_FIRST_SQUIRTLE"),
)
CONSTANTS = GAME / "include/constants/wayfarer_indigo_trainers.h"
ROSTER = GAME / "src/data/trainers_wayfarer_indigo.h"


def rows():
    if len(SOURCES) != 5 or BASE != 1795:
        raise ValueError("Indigo Trainer allocation changed without collision review")
    return [dict(id=f"TRAINER_WAYFARER_INDIGO_{name}", source_trainer=source,
                 numeric_id=BASE + index)
            for index, (name, source) in enumerate(SOURCES)]


def render_constants():
    lines = ["// Generated by tools/wayfarer_indigo_trainers/generate.py; do not edit.",
             "#ifndef GUARD_CONSTANTS_WAYFARER_INDIGO_TRAINERS_H",
             "#define GUARD_CONSTANTS_WAYFARER_INDIGO_TRAINERS_H", ""]
    lines += [f"#define {row['id']:<42} {row['numeric_id']}" for row in rows()]
    lines += ["", f"#define TRAINER_WAYFARER_INDIGO_FIRST {BASE}",
              f"#define TRAINER_WAYFARER_INDIGO_LAST {BASE + len(SOURCES) - 1}",
              "#if IS_WAYFARER", "#undef TRAINERS_COUNT_WAYFARER",
              f"#define TRAINERS_COUNT_WAYFARER {BASE + len(SOURCES)}",
              "#endif", "", "#endif  // GUARD_CONSTANTS_WAYFARER_INDIGO_TRAINERS_H", ""]
    return "\n".join(lines)


def render_roster():
    selected = coast.compiled_records(rows())
    lines = ["// Generated by tools/wayfarer_indigo_trainers/generate.py; do not edit.", ""]
    for row in rows():
        record = selected[row["source_trainer"]]
        if row["id"].endswith("_BLUE"):
            record = record.replace('.trainerName = _("TERRY")', '.trainerName = _("BLUE")', 1)
        lines += [record.rstrip() + ",", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in ((CONSTANTS, render_constants()), (ROSTER, render_roster())):
        if args.check:
            if path.read_text() != content:
                raise ValueError(f"stale generated file: {path}")
        else:
            path.write_text(content)
    print("Validated five dense collision-audited FRLG first-clear Indigo Trainers")


if __name__ == "__main__":
    main()
