import { type SkyEmuButton } from "../skyemu/client"

export const checkpoints = {
  "bedroom-before-clock": 1,
  "new-bark-after-intro": 2,
  "elm-lab-before-intro": 3,
  "hoenn-before-rescue": 4,
  "hoenn-female-before-rescue": 5,
  "hoenn-before-poison-whiteout": 6,
} as const

export const maps = {
  "fuchsia-city": { mapGroup: 0, mapNum: 39 },
  "fuchsia-wardens-house": { mapGroup: 19, mapNum: 3 },
  "fuchsia-safari-entrance": { mapGroup: 30, mapNum: 103 },
  "fuchsia-safari-beach": { mapGroup: 30, mapNum: 104 },

  "celadon-game-corner": { mapGroup: 17, mapNum: 9 },
  "celadon-hideout-b1f": { mapGroup: 66, mapNum: 42 },
  "celadon-hideout-b2f": { mapGroup: 66, mapNum: 43 },
  "celadon-hideout-b3f": { mapGroup: 66, mapNum: 44 },
  "celadon-hideout-b4f": { mapGroup: 66, mapNum: 45 },
  "celadon-hideout-elevator": { mapGroup: 66, mapNum: 46 },
  "ss-anne-1f": { mapGroup: 66, mapNum: 5 },
  "ss-anne-2f": { mapGroup: 66, mapNum: 6 },
  "ss-anne-b1f": { mapGroup: 66, mapNum: 8 },
  "ss-anne-captains-office": { mapGroup: 66, mapNum: 11 },
  "ss-anne-1f-room-2": { mapGroup: 66, mapNum: 13 },
  "new-bark-town": { mapGroup: 0, mapNum: 0 },
  "cherrygrove-city": { mapGroup: 0, mapNum: 1 },
  "azalea-town": { mapGroup: 0, mapNum: 3 },
  "mahogany-town": { mapGroup: 0, mapNum: 9 },
  "blackthorn-city": { mapGroup: 0, mapNum: 10 },
  "route-30": { mapGroup: 0, mapNum: 12 },
  "route-32": { mapGroup: 0, mapNum: 14 },
  "route-36": { mapGroup: 0, mapNum: 18 },
  "route-40": { mapGroup: 0, mapNum: 22 },
  "route-33": { mapGroup: 0, mapNum: 15 },
  "route-41": { mapGroup: 0, mapNum: 23 },
  "route-44": { mapGroup: 0, mapNum: 26 },
  "saffron-city": { mapGroup: 0, mapNum: 38 },
  "route-5": { mapGroup: 0, mapNum: 45 },
  "route-6": { mapGroup: 0, mapNum: 46 },
  "route-7": { mapGroup: 0, mapNum: 47 },
  "route-8": { mapGroup: 0, mapNum: 48 },
  "route-13": { mapGroup: 0, mapNum: 53 },
  "route-16": { mapGroup: 0, mapNum: 56 },
  "route-17": { mapGroup: 0, mapNum: 57 },
  "route-18": { mapGroup: 0, mapNum: 58 },
  "route-21": { mapGroup: 0, mapNum: 61 },
  "route-24": { mapGroup: 0, mapNum: 65 },
  "route-25": { mapGroup: 0, mapNum: 66 },
  "pallet-town": { mapGroup: 0, mapNum: 31 },
  "cerulean-city": { mapGroup: 0, mapNum: 34 },
  "vermilion-city": { mapGroup: 0, mapNum: 35 },
  "cinnabar-island": { mapGroup: 0, mapNum: 40 },
  "goldenrod-gym": { mapGroup: 5, mapNum: 6 },
  "olivine-city": { mapGroup: 0, mapNum: 6 },
  "cianwood-city": { mapGroup: 0, mapNum: 7 },
  "elm-lab": { mapGroup: 1, mapNum: 0 },
  "players-house-1f": { mapGroup: 1, mapNum: 3 },
  "players-bedroom": { mapGroup: 1, mapNum: 4 },
  "cherrygrove-pokemon-center": { mapGroup: 2, mapNum: 0 },
  "olivine-house-3": { mapGroup: 7, mapNum: 6 },
  "olivine-pokemon-center": { mapGroup: 7, mapNum: 0 },
  "vermilion-pokemon-center": { mapGroup: 15, mapNum: 0 },
  "slateport-pokemon-center": { mapGroup: 40, mapNum: 11 },
  "olivine-port-inside": { mapGroup: 7, mapNum: 8 },
  "blackthorn-move-deleter": { mapGroup: 10, mapNum: 5 },
  "vermilion-port-inside": { mapGroup: 15, mapNum: 3 },
  "vermilion-fan-club": { mapGroup: 15, mapNum: 5 },
  "goldenrod-train-station": { mapGroup: 5, mapNum: 14 },
  "cerulean-gym": { mapGroup: 14, mapNum: 5 },
  "saffron-train-station": { mapGroup: 18, mapNum: 2 },
  "copycats-house-2f": { mapGroup: 18, mapNum: 8 },
  "indigo-plateau": { mapGroup: 0, mapNum: 64 },
  "indigo-league-lobby": { mapGroup: 21, mapNum: 0 },
  "league-will": { mapGroup: 21, mapNum: 1 },
  "league-koga": { mapGroup: 21, mapNum: 2 },
  "league-bruno": { mapGroup: 21, mapNum: 3 },
  "league-karen": { mapGroup: 21, mapNum: 4 },
  "league-lance": { mapGroup: 21, mapNum: 5 },
  "hall-of-fame": { mapGroup: 21, mapNum: 6 },
  "league-sidney": { mapGroup: 47, mapNum: 0 },
  "league-phoebe": { mapGroup: 47, mapNum: 1 },
  "league-glacia": { mapGroup: 47, mapNum: 2 },
  "league-drake": { mapGroup: 47, mapNum: 3 },
  "league-wallace": { mapGroup: 47, mapNum: 4 },
  "hoenn-league-hall1": { mapGroup: 47, mapNum: 5 },
  "hoenn-league-hall2": { mapGroup: 47, mapNum: 6 },
  "hoenn-league-hall3": { mapGroup: 47, mapNum: 7 },
  "hoenn-league-hall4": { mapGroup: 47, mapNum: 8 },
  "hoenn-league-hall5": { mapGroup: 47, mapNum: 9 },
  "hoenn-league-lobby": { mapGroup: 47, mapNum: 10 },
  "hoenn-hall-of-fame": { mapGroup: 47, mapNum: 11 },

  "reception-gate": { mapGroup: 22, mapNum: 22 },
  "mt-silver-pokemon-center": { mapGroup: 22, mapNum: 34 },
  "power-plant-entrance": { mapGroup: 23, mapNum: 20 },
  "power-plant-back-room": { mapGroup: 23, mapNum: 21 },
  "saffron-route-7-gate": { mapGroup: 23, mapNum: 14 },
  "saffron-route-8-gate": { mapGroup: 23, mapNum: 18 },
  "celadon-route-16-gate": { mapGroup: 23, mapNum: 23 },
  "fuchsia-route-18-gate": { mapGroup: 23, mapNum: 24 },
  "ilex-forest": { mapGroup: 24, mapNum: 13 },
  "ice-path-1f": { mapGroup: 24, mapNum: 25 },
  "mt-moon-cave": { mapGroup: 24, mapNum: 57 },
  "snowswept-cavern": { mapGroup: 28, mapNum: 0 },
  "new-sinjoh": { mapGroup: 28, mapNum: 4 },
  "route-32-pokemon-center": { mapGroup: 22, mapNum: 27 },
  "route-12-house": { mapGroup: 23, mapNum: 25 },
  "ss-aqua-1f": { mapGroup: 30, mapNum: 8 },
  "ss-aqua-b1f": { mapGroup: 30, mapNum: 9 },
  "ss-aqua-captains-room": { mapGroup: 30, mapNum: 10 },
  "ss-aqua-room-nw": { mapGroup: 30, mapNum: 12 },
  "ss-aqua-room-sse": { mapGroup: 30, mapNum: 16 },
  "dragons-den-shrine": { mapGroup: 24, mapNum: 32 },
  "dragons-den-cavern": { mapGroup: 24, mapNum: 31 },
  "test-map-1": { mapGroup: 30, mapNum: 27 },
  "petalburg-city": { mapGroup: 31, mapNum: 0 },
  "mauville-gym": { mapGroup: 41, mapNum: 0 },
  "slateport-city": { mapGroup: 31, mapNum: 1 },
  "dewford-town": { mapGroup: 31, mapNum: 11 },
  "route-118": { mapGroup: 31, mapNum: 33 },
  "petalburg-house-1": { mapGroup: 39, mapNum: 2 },
  "slateport-city-harbor": { mapGroup: 40, mapNum: 9 },
  "inside-of-truck": { mapGroup: 56, mapNum: 40 },
  "brendans-house-1f": { mapGroup: 32, mapNum: 0 },
  "brendans-house-2f": { mapGroup: 32, mapNum: 1 },
  "mays-house-1f": { mapGroup: 32, mapNum: 2 },
  "mays-house-2f": { mapGroup: 32, mapNum: 3 },
  "birch-lab": { mapGroup: 32, mapNum: 4 },
  "route-101": { mapGroup: 31, mapNum: 16 },
  "route-103": { mapGroup: 31, mapNum: 18 },
  "littleroot-town": { mapGroup: 31, mapNum: 9 },
  "lavaridge-town": { mapGroup: 31, mapNum: 12 },
  "lavaridge-pokemon-center": { mapGroup: 35, mapNum: 5 },
  "lilycove-city": { mapGroup: 31, mapNum: 5 },
  "mossdeep-city": { mapGroup: 31, mapNum: 6 },
  "mossdeep-house-3": { mapGroup: 45, mapNum: 6 },
  "ever-grande-city": { mapGroup: 31, mapNum: 8 },
  "underwater-route-124": { mapGroup: 31, mapNum: 50 },
  "granite-cave-1f": { mapGroup: 55, mapNum: 7 },
  "mt-chimney": { mapGroup: 55, mapNum: 12 },
  "victory-road-1f": { mapGroup: 55, mapNum: 43 },
} as const

export const storyVars = {
  repelStepCount: 0x4021,
  baobaResearch: 0x4054,
  fuchsiaCityState: 0x4067,
  kantoSafariProgress: 0x406d,
  johtoSafariGateState: 0x4085,
  safariSession: 0x40a4,

  farawayIslandStepCounter: 0x403a,
  newBarkTownLabState: 0x4074,
  newBarkTownState: 0x4075,
  azaleaTownState: 0x4053,
  cherrygroveCityState: 0x405a,
  ceruleanCityState: 0x4059,
  fanClubClefairy: 0x4065,
  kantoRocketStoryState: 0x406c,
  goldenrodCityState: 0x4069,
  mahoganyTownState: 0x4072,
  leagueState: 0x4070,
  numBadges: 0x4076,
  pewterCityState: 0x4079,
  saffronCityState: 0x40bd,
  ssAquaState: 0x408b,
  starterMon: 0x4023,
  train: 0x408e,
  triggerElmRocketCall: 0x40b3,
  blackthornCityState: 0x4056,
  vermilionCityState: 0x408f,
  violetCityState: 0x4091,
} as const

export const storyFlags = {
  fuchsiaGoldTeethClaimed: 0x4bc,
  fuchsiaSurfReceived: 0x4bd,
  fuchsiaStrengthReceived: 0x4be,
  receivedExistingStrength: 0x1f8,
  inKantoSafari: 0x259,
  safariGoodLuck: 0x258,

  celadonHideoutKeyReceived: 0x4ba,
  celadonHideoutScopeReceived: 0x4bb,
  celadonHideoutOpened: 0x4b6,
  celadonHideoutLiftEnabled: 0x4b7,
  celadonHideoutGiovanniTrainerDefeated: 0x7b1,
  celadonHideoutGiovanniDefeated: 0x4b8,
  celadonHideoutEntranceGruntDefeated: 0x7a5,
  celadonHideoutKeyGruntDefeated: 0x7b0,
  celadonHideoutLeftGuardDefeated: 0x7ae,
  celadonHideoutRightGuardDefeated: 0x7af,
  ssAnneCaptainReward: 0x49d,
  ssAnneBlueMet: 0x4a3,
  hoennWhiteoutToLavaridge: 0x606c,
  sharedPokegear: 0x892,
  sharedMatchCall: 0x1f3,
  disableEncounters: 0x965,
  hideSilverInNewBark: 0x04a,
  hideElmLabAide: 0x04b,
  adventureStarted: 0x1d4,
  momVisited: 0x265,
  standardRodRoute32Contributed: 0x304,
  standardRodOlivineContributed: 0x305,
  standardRodRoute12Contributed: 0x306,
  standardRodDewfordContributed: 0x307,
  standardRodRoute118Contributed: 0x308,
  standardRodMossdeepContributed: 0x309,
  hideSudowoodo: 0x036,
  hideCeruleanGymPokemon: 0x038,
  hideVermilionSnorlax: 0x03a,
  hideSilverCherrygrove: 0x051,
  hideSproutTowerSilver: 0x058,
  hideAzaleaSilver: 0x05c,
  hideIndigoPlateauSilver: 0x0a6,
  hideMtMoonSilver: 0x0aa,
  hideViridianBlue: 0x0af,
  hideCinnabarBlue: 0x0d5,
  hideDragonsDenCavernClair: 0x09f,
  hideDragonsDenShrineClair: 0x0a2,
  hideCeruleanCapeRocket: 0x0b5,
  hideCeruleanGymRocket: 0x0b6,
  hideCeruleanGymTrainers: 0x0b7,
  hideRoute25Misty: 0x0ba,
  hidePowerPlantEngineer: 0x0bc,
  hideCopycatClefairyDoll: 0x0d2,
  hideFanClubClefairyDoll: 0x0d3,
  hiddenMachinePart: 0x1d3,
  returnedMachinePart: 0x1dd,
  receivedTogepiEgg: 0x1ff,
  kantoRadioGot: 0x261,
  defeatedVioletGym: 0x227,
  defeatedGoldenrodGym: 0x229,
  defeatedWhitneyTrainer: 0x696,
  defeatedPetalburgGym: 0x64f4,
  hideMauvilleCityWattson: 0x6390,
  hideMauvilleGymWattson: 0x6391,
  cyclingRoad: 0x896,
  isChampion: 0x89f,
  isKantoChampion: 0x8a0,
  visitedNewBarkTown: 0x8f0,
  visitedKanto: 0x8ff,
  visitedVermilionCity: 0x904,
  visitedSaffronCity: 0x907,
  badge1: 0x880,
  badge2: 0x881,
  badge3: 0x882,
  badge4: 0x883,
  badge5: 0x884,
  badge6: 0x885,
  badge7: 0x886,
  badge8: 0x887,
  badge9: 0x888,
} as const

export const species = {
  none: 0,
  pidgey: 16,
  rattata: 19,
  zubat: 41,
  poliwag: 60,
  geodude: 74,
  tentacruel: 73,
  onix: 95,
  hitmonchan: 107,
  krabby: 98,
  goldeen: 118,
  magikarp: 129,
  gyarados: 130,
  lapras: 131,
  dratini: 147,
  treecko: 252,
  torchic: 255,
  mudkip: 258,
  chikorita: 152,
  cyndaquil: 155,
  totodile: 158,
  sentret: 161,
  furret: 162,
  ariados: 168,
  sudowoodo: 185,
  umbreon: 197,
  girafarig: 203,
  steelix: 208,
  gardevoir: 282,
  mightyena: 262,
  wailord: 321,
  dusclops: 356,
  sealeo: 364,
  shelgon: 372,
  salamence: 373,
  wooper: 194,
  quagsire: 195,
  kyogre: 382,
} as const

export const moves = {
  none: 0,
  cut: 15,
  fly: 19,
  tackle: 33,
  surf: 57,
  strength: 70,
  teleport: 100,
  waterfall: 127,
  flash: 148,
  rockSmash: 249,
  whirlpool: 250,
  dive: 291,
} as const

export const hms = {
  cut: 682,
  fly: 683,
  surf: 684,
  strength: 685,
  flash: 686,
  rockSmash: 687,
  waterfall: 688,
  whirlpool: 689,
} as const

export const items = {
  goldTeeth: 749,
  pokeblockCase: 722,

  liftKey: 751,
  silphScope: 752,
  masterBall: 4,
  miracleSeed: 429,
  metalCoat: 441,
  tmThunder: 606,
  bicycle: 706,
  oldRod: 709,
  goodRod: 710,
  superRod: 711,
  ssTicket: 727,
  lostItem: 882,
  machinePart: 883,
  pass: 885,
  squirtBottle: 892,
} as const

export const partyMenuActions = {
  cut: 34,
  flash: 35,
  rockSmash: 36,
  strength: 37,
  surf: 38,
  fly: 39,
  dive: 40,
  waterfall: 41,
  whirlpool: 42,
  teleport: 43,
} as const

export const directions = {
  down: 1,
  up: 2,
  left: 3,
  right: 4,
} as const

export const buttons = {
  a: "A",
  b: "B",
  down: "Down",
  left: "Left",
  r: "R",
  right: "Right",
  select: "Select",
  start: "Start",
  up: "Up",
} as const satisfies Record<string, SkyEmuButton>

export const leagueRegions = ["kanto", "johto", "hoenn"] as const

export const textSpeeds = {
  fast: 2,
  instant: 3,
} as const

export type Checkpoint = keyof typeof checkpoints
export type GameMap = keyof typeof maps
export type Direction = keyof typeof directions
export type StoryVar = keyof typeof storyVars
export type StoryFlag = keyof typeof storyFlags
export type Button = keyof typeof buttons
export type TextSpeed = keyof typeof textSpeeds
export type Species = keyof typeof species
export type FixtureSpecies = Exclude<Species, "none">
export type Move = keyof typeof moves
export type Hm = keyof typeof hms
export type Item = keyof typeof items
export type PartyMenuAction = keyof typeof partyMenuActions
export type LeagueRegion = (typeof leagueRegions)[number]
