import { type SkyEmuButton } from "../skyemu/client"

export const checkpoints = {
  "bedroom-before-clock": 1,
  "new-bark-after-intro": 2,
  "elm-lab-before-intro": 3,
  "hoenn-before-rescue": 4,
  "hoenn-female-before-rescue": 5,
  "hoenn-before-poison-whiteout": 6,
} as const

// Base trainer IDs accepted by the bounded rematch fixture. The ROM validates
// that the chosen id owns a real rematch-table entry before it marks the base
// battle complete and lets the game's normal rematch selection run.
export const rematchTrainers = {
  "joey-hns": 7,
  "ralph-hns": 177,
} as const

export const maps = {
  "new-bark-town": { mapGroup: 0, mapNum: 0 },
  "cherrygrove-city": { mapGroup: 0, mapNum: 1 },
  "azalea-town": { mapGroup: 0, mapNum: 3 },
  "mahogany-town": { mapGroup: 0, mapNum: 9 },
  "blackthorn-city": { mapGroup: 0, mapNum: 10 },
  "route-30": { mapGroup: 0, mapNum: 12 },
  "route-32": { mapGroup: 0, mapNum: 14 },
  "route-36": { mapGroup: 0, mapNum: 18 },
  "route-40": { mapGroup: 0, mapNum: 22 },
  "route-33": { mapGroup: 0, mapNum: 15 },
  "route-41": { mapGroup: 0, mapNum: 23 },
  "route-44": { mapGroup: 0, mapNum: 26 },
  "saffron-city": { mapGroup: 0, mapNum: 38 },
  "route-5": { mapGroup: 0, mapNum: 45 },
  "route-6": { mapGroup: 0, mapNum: 46 },
  "route-7": { mapGroup: 0, mapNum: 47 },
  "route-8": { mapGroup: 0, mapNum: 48 },
  "route-13": { mapGroup: 0, mapNum: 53 },
  "route-16": { mapGroup: 0, mapNum: 56 },
  "route-17": { mapGroup: 0, mapNum: 57 },
  "route-18": { mapGroup: 0, mapNum: 58 },
  "route-21": { mapGroup: 0, mapNum: 61 },
  "route-24": { mapGroup: 0, mapNum: 65 },
  "route-25": { mapGroup: 0, mapNum: 66 },
  "pallet-town": { mapGroup: 0, mapNum: 31 },
  "cerulean-city": { mapGroup: 0, mapNum: 34 },
  "vermilion-city": { mapGroup: 0, mapNum: 35 },
  "cinnabar-island": { mapGroup: 0, mapNum: 40 },
  "goldenrod-gym": { mapGroup: 5, mapNum: 6 },
  "goldenrod-underground-switches": { mapGroup: 5, mapNum: 3 },
  "goldenrod-radio-tower-1f": { mapGroup: 5, mapNum: 15 },
  "goldenrod-radio-tower-4f": { mapGroup: 5, mapNum: 18 },
  "goldenrod-radio-tower-5f": { mapGroup: 5, mapNum: 19 },
  "ecruteak-theater": { mapGroup: 6, mapNum: 2 },
  "olivine-city": { mapGroup: 0, mapNum: 6 },
  "cianwood-city": { mapGroup: 0, mapNum: 7 },
  "elm-lab": { mapGroup: 1, mapNum: 0 },
  "players-house-1f": { mapGroup: 1, mapNum: 3 },
  "players-bedroom": { mapGroup: 1, mapNum: 4 },
  "cherrygrove-pokemon-center": { mapGroup: 2, mapNum: 0 },
  "olivine-house-3": { mapGroup: 7, mapNum: 6 },
  "olivine-pokemon-center": { mapGroup: 7, mapNum: 0 },
  "vermilion-pokemon-center": { mapGroup: 15, mapNum: 0 },
  "slateport-pokemon-center": { mapGroup: 40, mapNum: 11 },
  "olivine-port-inside": { mapGroup: 7, mapNum: 8 },
  "blackthorn-move-deleter": { mapGroup: 10, mapNum: 5 },
  "vermilion-port-inside": { mapGroup: 15, mapNum: 3 },
  "vermilion-fan-club": { mapGroup: 15, mapNum: 5 },
  "goldenrod-train-station": { mapGroup: 5, mapNum: 14 },
  "cerulean-gym": { mapGroup: 14, mapNum: 5 },
  "viridian-gym": { mapGroup: 12, mapNum: 4 },
  "saffron-train-station": { mapGroup: 18, mapNum: 2 },
  "copycats-house-2f": { mapGroup: 18, mapNum: 8 },
  "indigo-plateau": { mapGroup: 0, mapNum: 64 },
  "indigo-league-lobby": { mapGroup: 21, mapNum: 0 },
  "indigo-plateau-pokemon-center": { mapGroup: 21, mapNum: 0 },
  "league-will": { mapGroup: 21, mapNum: 1 },
  "league-koga": { mapGroup: 21, mapNum: 2 },
  "league-bruno": { mapGroup: 21, mapNum: 3 },
  "league-karen": { mapGroup: 21, mapNum: 4 },
  "league-lance": { mapGroup: 21, mapNum: 5 },
  "hall-of-fame": { mapGroup: 21, mapNum: 6 },
  "league-sidney": { mapGroup: 47, mapNum: 0 },
  "league-phoebe": { mapGroup: 47, mapNum: 1 },
  "league-glacia": { mapGroup: 47, mapNum: 2 },
  "league-drake": { mapGroup: 47, mapNum: 3 },
  "league-wallace": { mapGroup: 47, mapNum: 4 },
  "hoenn-league-hall1": { mapGroup: 47, mapNum: 5 },
  "hoenn-league-hall2": { mapGroup: 47, mapNum: 6 },
  "hoenn-league-hall3": { mapGroup: 47, mapNum: 7 },
  "hoenn-league-hall4": { mapGroup: 47, mapNum: 8 },
  "hoenn-league-hall5": { mapGroup: 47, mapNum: 9 },
  "hoenn-league-lobby": { mapGroup: 47, mapNum: 10 },
  "hoenn-hall-of-fame": { mapGroup: 47, mapNum: 11 },

  "reception-gate": { mapGroup: 22, mapNum: 22 },
  "mt-silver-pokemon-center": { mapGroup: 22, mapNum: 34 },
  "power-plant-entrance": { mapGroup: 23, mapNum: 20 },
  "power-plant-back-room": { mapGroup: 23, mapNum: 21 },
  "saffron-route-7-gate": { mapGroup: 23, mapNum: 14 },
  "saffron-route-8-gate": { mapGroup: 23, mapNum: 18 },
  "celadon-route-16-gate": { mapGroup: 23, mapNum: 23 },
  "fuchsia-route-18-gate": { mapGroup: 23, mapNum: 24 },
  "ilex-forest": { mapGroup: 24, mapNum: 13 },
  "sprout-tower-3f": { mapGroup: 24, mapNum: 4 },
  "ice-path-1f": { mapGroup: 24, mapNum: 25 },
  "tohjo-giovanni": { mapGroup: 24, mapNum: 52 },
  "victory-road-kanto-1f": { mapGroup: 24, mapNum: 55 },
  "mt-moon-cave": { mapGroup: 24, mapNum: 57 },
  "slowpoke-well-b1f": { mapGroup: 24, mapNum: 11 },
  "burned-tower-1f": { mapGroup: 24, mapNum: 16 },
  "rocket-hideout-b2f": { mapGroup: 24, mapNum: 84 },
  "rocket-hideout-b3f": { mapGroup: 24, mapNum: 85 },
  "snowswept-cavern": { mapGroup: 28, mapNum: 0 },
  "new-sinjoh": { mapGroup: 28, mapNum: 4 },
  "route-32-pokemon-center": { mapGroup: 22, mapNum: 27 },
  "route-12-house": { mapGroup: 23, mapNum: 25 },
  "ss-aqua-1f": { mapGroup: 30, mapNum: 8 },
  "ss-aqua-b1f": { mapGroup: 30, mapNum: 9 },
  "ss-aqua-captains-room": { mapGroup: 30, mapNum: 10 },
  "ss-aqua-room-nw": { mapGroup: 30, mapNum: 12 },
  "ss-aqua-room-sse": { mapGroup: 30, mapNum: 16 },
  "dragons-den-shrine": { mapGroup: 24, mapNum: 32 },
  "dragons-den-cavern": { mapGroup: 24, mapNum: 31 },
  "test-map-1": { mapGroup: 30, mapNum: 27 },
  "petalburg-city": { mapGroup: 31, mapNum: 0 },
  "mauville-gym": { mapGroup: 41, mapNum: 0 },
  "slateport-city": { mapGroup: 31, mapNum: 1 },
  "dewford-town": { mapGroup: 31, mapNum: 11 },
  "route-118": { mapGroup: 31, mapNum: 33 },
  "petalburg-house-1": { mapGroup: 39, mapNum: 2 },
  "slateport-city-harbor": { mapGroup: 40, mapNum: 9 },
  "inside-of-truck": { mapGroup: 56, mapNum: 40 },
  "brendans-house-1f": { mapGroup: 32, mapNum: 0 },
  "brendans-house-2f": { mapGroup: 32, mapNum: 1 },
  "mays-house-1f": { mapGroup: 32, mapNum: 2 },
  "mays-house-2f": { mapGroup: 32, mapNum: 3 },
  "birch-lab": { mapGroup: 32, mapNum: 4 },
  "route-101": { mapGroup: 31, mapNum: 16 },
  "route-103": { mapGroup: 31, mapNum: 18 },
  "mauville-city": { mapGroup: 31, mapNum: 2 },
  "rustboro-city": { mapGroup: 31, mapNum: 3 },
  "route-110": { mapGroup: 31, mapNum: 25 },
  "route-119": { mapGroup: 31, mapNum: 34 },
  "route-120": { mapGroup: 31, mapNum: 35 },
  "route-124": { mapGroup: 31, mapNum: 39 },
  "littleroot-town": { mapGroup: 31, mapNum: 9 },
  "lavaridge-town": { mapGroup: 31, mapNum: 12 },
  "lavaridge-pokemon-center": { mapGroup: 35, mapNum: 5 },
  "lilycove-city": { mapGroup: 31, mapNum: 5 },
  "mossdeep-city": { mapGroup: 31, mapNum: 6 },
  "mossdeep-house-3": { mapGroup: 45, mapNum: 6 },
  "mossdeep-space-center-1f": { mapGroup: 45, mapNum: 9 },
  "mossdeep-space-center-2f": { mapGroup: 45, mapNum: 10 },
  "slateport-oceanic-museum-2f": { mapGroup: 40, mapNum: 8 },
  "ever-grande-city": { mapGroup: 31, mapNum: 8 },
  "underwater-route-124": { mapGroup: 31, mapNum: 50 },
  "granite-cave-1f": { mapGroup: 55, mapNum: 7 },
  "rusturf-tunnel": { mapGroup: 55, mapNum: 4 },
  "aqua-hideout-b2f": { mapGroup: 55, mapNum: 25 },
  "seafloor-cavern-room9": { mapGroup: 55, mapNum: 36 },
  "mt-chimney": { mapGroup: 55, mapNum: 12 },
  "victory-road-1f": { mapGroup: 55, mapNum: 43 },
  "birth-island-harbor": { mapGroup: 30, mapNum: 39 },
  "navel-rock-harbor": { mapGroup: 57, mapNum: 67 },
  "sevii-mt-ember-ruby-path-b4-f": { mapGroup: 66, mapNum: 96 },
  "sevii-mt-ember-exterior": { mapGroup: 66, mapNum: 97 },
  "sevii-mt-ember-summit-path-1-f": { mapGroup: 66, mapNum: 98 },
  "sevii-mt-ember-summit-path-2-f": { mapGroup: 66, mapNum: 99 },
  "sevii-mt-ember-summit-path-3-f": { mapGroup: 66, mapNum: 100 },
  "sevii-mt-ember-summit": { mapGroup: 66, mapNum: 101 },
  "sevii-mt-ember-ruby-path-b5-f": { mapGroup: 66, mapNum: 102 },
  "sevii-mt-ember-ruby-path-1-f": { mapGroup: 66, mapNum: 103 },
  "sevii-mt-ember-ruby-path-b1-f": { mapGroup: 66, mapNum: 104 },
  "sevii-mt-ember-ruby-path-b2-f": { mapGroup: 66, mapNum: 105 },
  "sevii-mt-ember-ruby-path-b3-f": { mapGroup: 66, mapNum: 106 },
  "sevii-mt-ember-ruby-path-b1-f-stairs": { mapGroup: 66, mapNum: 107 },
  "sevii-mt-ember-ruby-path-b2-f-stairs": { mapGroup: 66, mapNum: 108 },
  "sevii-three-island-berry-forest": { mapGroup: 66, mapNum: 109 },
  "sevii-four-island-icefall-cave-entrance": { mapGroup: 66, mapNum: 110 },
  "sevii-four-island-icefall-cave-1-f": { mapGroup: 66, mapNum: 111 },
  "sevii-four-island-icefall-cave-b1-f": { mapGroup: 66, mapNum: 112 },
  "sevii-four-island-icefall-cave-back": { mapGroup: 66, mapNum: 113 },
  "sevii-five-island-rocket-warehouse": { mapGroup: 66, mapNum: 114 },
  "sevii-six-island-dotted-hole-1-f": { mapGroup: 66, mapNum: 115 },
  "sevii-six-island-dotted-hole-b1-f": { mapGroup: 66, mapNum: 116 },
  "sevii-six-island-dotted-hole-b2-f": { mapGroup: 66, mapNum: 117 },
  "sevii-six-island-dotted-hole-b3-f": { mapGroup: 66, mapNum: 118 },
  "sevii-six-island-dotted-hole-b4-f": { mapGroup: 66, mapNum: 119 },
  "sevii-six-island-dotted-hole-sapphire-room": { mapGroup: 66, mapNum: 120 },
  "sevii-six-island-pattern-bush": { mapGroup: 66, mapNum: 121 },
  "sevii-six-island-altering-cave": { mapGroup: 66, mapNum: 122 },
  "sevii-trainer-tower-1-f": { mapGroup: 67, mapNum: 1 },
  "sevii-trainer-tower-2-f": { mapGroup: 67, mapNum: 2 },
  "sevii-trainer-tower-3-f": { mapGroup: 67, mapNum: 3 },
  "sevii-trainer-tower-4-f": { mapGroup: 67, mapNum: 4 },
  "sevii-trainer-tower-5-f": { mapGroup: 67, mapNum: 5 },
  "sevii-trainer-tower-6-f": { mapGroup: 67, mapNum: 6 },
  "sevii-trainer-tower-7-f": { mapGroup: 67, mapNum: 7 },
  "sevii-trainer-tower-8-f": { mapGroup: 67, mapNum: 8 },
  "sevii-trainer-tower-roof": { mapGroup: 67, mapNum: 9 },
  "sevii-trainer-tower-lobby": { mapGroup: 67, mapNum: 10 },
  "sevii-trainer-tower-elevator": { mapGroup: 67, mapNum: 11 },
  "sevii-five-island-lost-cave-entrance": { mapGroup: 67, mapNum: 12 },
  "sevii-five-island-lost-cave-room1": { mapGroup: 67, mapNum: 13 },
  "sevii-five-island-lost-cave-room2": { mapGroup: 67, mapNum: 14 },
  "sevii-five-island-lost-cave-room3": { mapGroup: 67, mapNum: 15 },
  "sevii-five-island-lost-cave-room4": { mapGroup: 67, mapNum: 16 },
  "sevii-five-island-lost-cave-room5": { mapGroup: 67, mapNum: 17 },
  "sevii-five-island-lost-cave-room6": { mapGroup: 67, mapNum: 18 },
  "sevii-five-island-lost-cave-room7": { mapGroup: 67, mapNum: 19 },
  "sevii-five-island-lost-cave-room8": { mapGroup: 67, mapNum: 20 },
  "sevii-five-island-lost-cave-room9": { mapGroup: 67, mapNum: 21 },
  "sevii-five-island-lost-cave-room10": { mapGroup: 67, mapNum: 22 },
  "sevii-five-island-lost-cave-room11": { mapGroup: 67, mapNum: 23 },
  "sevii-five-island-lost-cave-room12": { mapGroup: 67, mapNum: 24 },
  "sevii-five-island-lost-cave-room13": { mapGroup: 67, mapNum: 25 },
  "sevii-five-island-lost-cave-room14": { mapGroup: 67, mapNum: 26 },
  "sevii-seven-island-tanoby-ruins-monean-chamber": { mapGroup: 67, mapNum: 27 },
  "sevii-seven-island-tanoby-ruins-liptoo-chamber": { mapGroup: 67, mapNum: 28 },
  "sevii-seven-island-tanoby-ruins-weepth-chamber": { mapGroup: 67, mapNum: 29 },
  "sevii-seven-island-tanoby-ruins-dilford-chamber": { mapGroup: 67, mapNum: 30 },
  "sevii-seven-island-tanoby-ruins-scufib-chamber": { mapGroup: 67, mapNum: 31 },
  "sevii-seven-island-tanoby-ruins-rixy-chamber": { mapGroup: 67, mapNum: 32 },
  "sevii-seven-island-tanoby-ruins-viapois-chamber": { mapGroup: 67, mapNum: 33 },
  "sevii-three-island-dunsparce-tunnel": { mapGroup: 67, mapNum: 34 },
  "sevii-seven-island-sevault-canyon-tanoby-key": { mapGroup: 67, mapNum: 35 },
  "sevii-one-island-kindle-road-ember-spa": { mapGroup: 67, mapNum: 57 },
  "sevii-one-island": { mapGroup: 68, mapNum: 12 },
  "sevii-two-island": { mapGroup: 68, mapNum: 13 },
  "sevii-three-island": { mapGroup: 68, mapNum: 14 },
  "sevii-four-island": { mapGroup: 68, mapNum: 15 },
  "sevii-five-island": { mapGroup: 68, mapNum: 16 },
  "sevii-seven-island": { mapGroup: 68, mapNum: 17 },
  "sevii-six-island": { mapGroup: 68, mapNum: 18 },
  "sevii-one-island-kindle-road": { mapGroup: 68, mapNum: 45 },
  "sevii-one-island-treasure-beach": { mapGroup: 68, mapNum: 46 },
  "sevii-two-island-cape-brink": { mapGroup: 68, mapNum: 47 },
  "sevii-three-island-bond-bridge": { mapGroup: 68, mapNum: 48 },
  "sevii-three-island-port": { mapGroup: 68, mapNum: 49 },
  "sevii-five-island-resort-gorgeous": { mapGroup: 68, mapNum: 50 },
  "sevii-five-island-water-labyrinth": { mapGroup: 68, mapNum: 51 },
  "sevii-five-island-meadow": { mapGroup: 68, mapNum: 52 },
  "sevii-five-island-memorial-pillar": { mapGroup: 68, mapNum: 53 },
  "sevii-six-island-outcast-island": { mapGroup: 68, mapNum: 54 },
  "sevii-six-island-green-path": { mapGroup: 68, mapNum: 55 },
  "sevii-six-island-water-path": { mapGroup: 68, mapNum: 56 },
  "sevii-six-island-ruin-valley": { mapGroup: 68, mapNum: 57 },
  "sevii-seven-island-trainer-tower": { mapGroup: 68, mapNum: 58 },
  "sevii-seven-island-sevault-canyon-entrance": { mapGroup: 68, mapNum: 59 },
  "sevii-seven-island-sevault-canyon": { mapGroup: 68, mapNum: 60 },
  "sevii-seven-island-tanoby-ruins": { mapGroup: 68, mapNum: 61 },
  "sevii-seven-island-house-room1": { mapGroup: 94, mapNum: 0 },
  "sevii-seven-island-house-room2": { mapGroup: 94, mapNum: 1 },
  "sevii-seven-island-mart": { mapGroup: 94, mapNum: 2 },
  "sevii-seven-island-pokemon-center-1-f": { mapGroup: 94, mapNum: 3 },
  "sevii-seven-island-pokemon-center-2-f": { mapGroup: 94, mapNum: 4 },
  "sevii-seven-island-harbor": { mapGroup: 94, mapNum: 5 },
  "sevii-one-island-pokemon-center-1-f": { mapGroup: 95, mapNum: 0 },
  "sevii-one-island-pokemon-center-2-f": { mapGroup: 95, mapNum: 1 },
  "sevii-one-island-house1": { mapGroup: 95, mapNum: 2 },
  "sevii-one-island-house2": { mapGroup: 95, mapNum: 3 },
  "sevii-one-island-harbor": { mapGroup: 95, mapNum: 4 },
  "sevii-two-island-joyful-game-corner": { mapGroup: 96, mapNum: 0 },
  "sevii-two-island-house": { mapGroup: 96, mapNum: 1 },
  "sevii-two-island-pokemon-center-1-f": { mapGroup: 96, mapNum: 2 },
  "sevii-two-island-pokemon-center-2-f": { mapGroup: 96, mapNum: 3 },
  "sevii-two-island-harbor": { mapGroup: 96, mapNum: 4 },
  "sevii-three-island-house1": { mapGroup: 97, mapNum: 0 },
  "sevii-three-island-pokemon-center-1-f": { mapGroup: 97, mapNum: 1 },
  "sevii-three-island-pokemon-center-2-f": { mapGroup: 97, mapNum: 2 },
  "sevii-three-island-mart": { mapGroup: 97, mapNum: 3 },
  "sevii-three-island-house2": { mapGroup: 97, mapNum: 4 },
  "sevii-three-island-house3": { mapGroup: 97, mapNum: 5 },
  "sevii-three-island-house4": { mapGroup: 97, mapNum: 6 },
  "sevii-three-island-house5": { mapGroup: 97, mapNum: 7 },
  "sevii-four-island-pokemon-day-care": { mapGroup: 98, mapNum: 0 },
  "sevii-four-island-pokemon-center-1-f": { mapGroup: 98, mapNum: 1 },
  "sevii-four-island-pokemon-center-2-f": { mapGroup: 98, mapNum: 2 },
  "sevii-four-island-house1": { mapGroup: 98, mapNum: 3 },
  "sevii-four-island-loreleis-house": { mapGroup: 98, mapNum: 4 },
  "sevii-four-island-harbor": { mapGroup: 98, mapNum: 5 },
  "sevii-four-island-house2": { mapGroup: 98, mapNum: 6 },
  "sevii-four-island-mart": { mapGroup: 98, mapNum: 7 },
  "sevii-five-island-pokemon-center-1-f": { mapGroup: 99, mapNum: 0 },
  "sevii-five-island-pokemon-center-2-f": { mapGroup: 99, mapNum: 1 },
  "sevii-five-island-harbor": { mapGroup: 99, mapNum: 2 },
  "sevii-five-island-house1": { mapGroup: 99, mapNum: 3 },
  "sevii-five-island-house2": { mapGroup: 99, mapNum: 4 },
  "sevii-six-island-pokemon-center-1-f": { mapGroup: 100, mapNum: 0 },
  "sevii-six-island-pokemon-center-2-f": { mapGroup: 100, mapNum: 1 },
  "sevii-six-island-harbor": { mapGroup: 100, mapNum: 2 },
  "sevii-six-island-house": { mapGroup: 100, mapNum: 3 },
  "sevii-six-island-mart": { mapGroup: 100, mapNum: 4 },
  "sevii-three-island-harbor": { mapGroup: 101, mapNum: 0 },
  "sevii-five-island-resort-gorgeous-house": { mapGroup: 102, mapNum: 0 },
  "sevii-two-island-cape-brink-house": { mapGroup: 103, mapNum: 0 },
  "sevii-six-island-water-path-house1": { mapGroup: 104, mapNum: 0 },
  "sevii-six-island-water-path-house2": { mapGroup: 104, mapNum: 1 },
  "sevii-seven-island-sevault-canyon-house": { mapGroup: 105, mapNum: 0 },
  "magma-hideout-4f": { mapGroup: 55, mapNum: 91 },
  "route119-weather-institute-2f": { mapGroup: 63, mapNum: 1 },
} as const

export const seviiImportedMaps = [
  { map: "sevii-mt-ember-ruby-path-b4-f", x: 14, y: 14 },
  { map: "sevii-mt-ember-exterior", x: 28, y: 48 },
  { map: "sevii-mt-ember-summit-path-1-f", x: 2, y: 15 },
  { map: "sevii-mt-ember-summit-path-2-f", x: 8, y: 39 },
  { map: "sevii-mt-ember-summit-path-3-f", x: 2, y: 4 },
  { map: "sevii-mt-ember-summit", x: 9, y: 15 },
  { map: "sevii-mt-ember-ruby-path-b5-f", x: 11, y: 7 },
  { map: "sevii-mt-ember-ruby-path-1-f", x: 22, y: 17 },
  { map: "sevii-mt-ember-ruby-path-b1-f", x: 9, y: 21 },
  { map: "sevii-mt-ember-ruby-path-b2-f", x: 1, y: 7 },
  { map: "sevii-mt-ember-ruby-path-b3-f", x: 1, y: 4 },
  { map: "sevii-mt-ember-ruby-path-b1-f-stairs", x: 4, y: 1 },
  { map: "sevii-mt-ember-ruby-path-b2-f-stairs", x: 6, y: 1 },
  { map: "sevii-three-island-berry-forest", x: 43, y: 41 },
  { map: "sevii-four-island-icefall-cave-entrance", x: 17, y: 30 },
  { map: "sevii-four-island-icefall-cave-1-f", x: 3, y: 17 },
  { map: "sevii-four-island-icefall-cave-b1-f", x: 12, y: 12 },
  { map: "sevii-four-island-icefall-cave-back", x: 12, y: 23 },
  { map: "sevii-five-island-rocket-warehouse", x: 24, y: 25 },
  { map: "sevii-six-island-dotted-hole-1-f", x: 6, y: 9 },
  { map: "sevii-six-island-dotted-hole-b1-f", x: 6, y: 7 },
  { map: "sevii-six-island-dotted-hole-b2-f", x: 6, y: 7 },
  { map: "sevii-six-island-dotted-hole-b3-f", x: 6, y: 7 },
  { map: "sevii-six-island-dotted-hole-b4-f", x: 6, y: 7 },
  { map: "sevii-six-island-dotted-hole-sapphire-room", x: 11, y: 7 },
  { map: "sevii-six-island-pattern-bush", x: 54, y: 26 },
  { map: "sevii-six-island-altering-cave", x: 18, y: 22 },
  { map: "sevii-trainer-tower-1-f", x: 15, y: 6 },
  { map: "sevii-trainer-tower-2-f", x: 15, y: 6 },
  { map: "sevii-trainer-tower-3-f", x: 15, y: 6 },
  { map: "sevii-trainer-tower-4-f", x: 15, y: 6 },
  { map: "sevii-trainer-tower-5-f", x: 15, y: 6 },
  { map: "sevii-trainer-tower-6-f", x: 15, y: 6 },
  { map: "sevii-trainer-tower-7-f", x: 15, y: 6 },
  { map: "sevii-trainer-tower-8-f", x: 15, y: 6 },
  { map: "sevii-trainer-tower-roof", x: 13, y: 5 },
  { map: "sevii-trainer-tower-lobby", x: 9, y: 2 },
  { map: "sevii-trainer-tower-elevator", x: 2, y: 5 },
  { map: "sevii-five-island-lost-cave-entrance", x: 5, y: 8 },
  { map: "sevii-five-island-lost-cave-room1", x: 8, y: 2 },
  { map: "sevii-five-island-lost-cave-room2", x: 5, y: 1 },
  { map: "sevii-five-island-lost-cave-room3", x: 5, y: 1 },
  { map: "sevii-five-island-lost-cave-room4", x: 5, y: 1 },
  { map: "sevii-five-island-lost-cave-room5", x: 5, y: 1 },
  { map: "sevii-five-island-lost-cave-room6", x: 5, y: 1 },
  { map: "sevii-five-island-lost-cave-room7", x: 5, y: 1 },
  { map: "sevii-five-island-lost-cave-room8", x: 5, y: 1 },
  { map: "sevii-five-island-lost-cave-room9", x: 5, y: 1 },
  { map: "sevii-five-island-lost-cave-room10", x: 5, y: 8 },
  { map: "sevii-five-island-lost-cave-room11", x: 5, y: 1 },
  { map: "sevii-five-island-lost-cave-room12", x: 5, y: 8 },
  { map: "sevii-five-island-lost-cave-room13", x: 2, y: 5 },
  { map: "sevii-five-island-lost-cave-room14", x: 8, y: 5 },
  { map: "sevii-seven-island-tanoby-ruins-monean-chamber", x: 11, y: 15 },
  { map: "sevii-seven-island-tanoby-ruins-liptoo-chamber", x: 11, y: 15 },
  { map: "sevii-seven-island-tanoby-ruins-weepth-chamber", x: 11, y: 15 },
  { map: "sevii-seven-island-tanoby-ruins-dilford-chamber", x: 11, y: 15 },
  { map: "sevii-seven-island-tanoby-ruins-scufib-chamber", x: 11, y: 15 },
  { map: "sevii-seven-island-tanoby-ruins-rixy-chamber", x: 11, y: 15 },
  { map: "sevii-seven-island-tanoby-ruins-viapois-chamber", x: 11, y: 15 },
  { map: "sevii-three-island-dunsparce-tunnel", x: 3, y: 4 },
  { map: "sevii-seven-island-sevault-canyon-tanoby-key", x: 7, y: 13 },
  { map: "sevii-one-island-kindle-road-ember-spa", x: 13, y: 36 },
  { map: "sevii-one-island", x: 14, y: 5 },
  { map: "sevii-two-island", x: 39, y: 9 },
  { map: "sevii-three-island", x: 3, y: 31 },
  { map: "sevii-four-island", x: 18, y: 20 },
  { map: "sevii-five-island", x: 12, y: 14 },
  { map: "sevii-seven-island", x: 11, y: 9 },
  { map: "sevii-six-island", x: 11, y: 23 },
  { map: "sevii-one-island-kindle-road", x: 11, y: 6 },
  { map: "sevii-one-island-treasure-beach", x: 0, y: 0 },
  { map: "sevii-two-island-cape-brink", x: 12, y: 16 },
  { map: "sevii-three-island-bond-bridge", x: 12, y: 6 },
  { map: "sevii-three-island-port", x: 16, y: 4 },
  { map: "sevii-five-island-resort-gorgeous", x: 64, y: 13 },
  { map: "sevii-five-island-water-labyrinth", x: 0, y: 0 },
  { map: "sevii-five-island-meadow", x: 12, y: 21 },
  { map: "sevii-five-island-memorial-pillar", x: 0, y: 0 },
  { map: "sevii-six-island-outcast-island", x: 7, y: 21 },
  { map: "sevii-six-island-green-path", x: 63, y: 10 },
  { map: "sevii-six-island-water-path", x: 5, y: 13 },
  { map: "sevii-six-island-ruin-valley", x: 24, y: 24 },
  { map: "sevii-seven-island-trainer-tower", x: 58, y: 7 },
  { map: "sevii-seven-island-sevault-canyon-entrance", x: 0, y: 0 },
  { map: "sevii-seven-island-sevault-canyon", x: 7, y: 17 },
  { map: "sevii-seven-island-tanoby-ruins", x: 120, y: 10 },
  { map: "sevii-seven-island-house-room1", x: 4, y: 7 },
  { map: "sevii-seven-island-house-room2", x: 3, y: 1 },
  { map: "sevii-seven-island-mart", x: 4, y: 7 },
  { map: "sevii-seven-island-pokemon-center-1-f", x: 7, y: 8 },
  { map: "sevii-seven-island-pokemon-center-2-f", x: 1, y: 6 },
  { map: "sevii-seven-island-harbor", x: 8, y: 2 },
  { map: "sevii-one-island-pokemon-center-1-f", x: 9, y: 9 },
  { map: "sevii-one-island-pokemon-center-2-f", x: 1, y: 6 },
  { map: "sevii-one-island-house1", x: 4, y: 7 },
  { map: "sevii-one-island-house2", x: 4, y: 7 },
  { map: "sevii-one-island-harbor", x: 8, y: 2 },
  { map: "sevii-two-island-joyful-game-corner", x: 5, y: 8 },
  { map: "sevii-two-island-house", x: 4, y: 7 },
  { map: "sevii-two-island-pokemon-center-1-f", x: 7, y: 8 },
  { map: "sevii-two-island-pokemon-center-2-f", x: 1, y: 6 },
  { map: "sevii-two-island-harbor", x: 8, y: 2 },
  { map: "sevii-three-island-house1", x: 4, y: 7 },
  { map: "sevii-three-island-pokemon-center-1-f", x: 7, y: 8 },
  { map: "sevii-three-island-pokemon-center-2-f", x: 1, y: 6 },
  { map: "sevii-three-island-mart", x: 4, y: 7 },
  { map: "sevii-three-island-house2", x: 4, y: 7 },
  { map: "sevii-three-island-house3", x: 4, y: 7 },
  { map: "sevii-three-island-house4", x: 4, y: 7 },
  { map: "sevii-three-island-house5", x: 4, y: 7 },
  { map: "sevii-four-island-pokemon-day-care", x: 4, y: 7 },
  { map: "sevii-four-island-pokemon-center-1-f", x: 7, y: 8 },
  { map: "sevii-four-island-pokemon-center-2-f", x: 1, y: 6 },
  { map: "sevii-four-island-house1", x: 4, y: 7 },
  { map: "sevii-four-island-loreleis-house", x: 4, y: 7 },
  { map: "sevii-four-island-harbor", x: 8, y: 2 },
  { map: "sevii-four-island-house2", x: 4, y: 7 },
  { map: "sevii-four-island-mart", x: 4, y: 7 },
  { map: "sevii-five-island-pokemon-center-1-f", x: 7, y: 8 },
  { map: "sevii-five-island-pokemon-center-2-f", x: 1, y: 6 },
  { map: "sevii-five-island-harbor", x: 8, y: 2 },
  { map: "sevii-five-island-house1", x: 4, y: 7 },
  { map: "sevii-five-island-house2", x: 4, y: 7 },
  { map: "sevii-six-island-pokemon-center-1-f", x: 7, y: 8 },
  { map: "sevii-six-island-pokemon-center-2-f", x: 1, y: 6 },
  { map: "sevii-six-island-harbor", x: 8, y: 2 },
  { map: "sevii-six-island-house", x: 4, y: 7 },
  { map: "sevii-six-island-mart", x: 4, y: 7 },
  { map: "sevii-three-island-harbor", x: 8, y: 2 },
  { map: "sevii-five-island-resort-gorgeous-house", x: 4, y: 7 },
  { map: "sevii-two-island-cape-brink-house", x: 4, y: 7 },
  { map: "sevii-six-island-water-path-house1", x: 3, y: 7 },
  { map: "sevii-six-island-water-path-house2", x: 4, y: 7 },
  { map: "sevii-seven-island-sevault-canyon-house", x: 4, y: 7 },
] as const

export const storyVars = {
  newBarkTownLabState: 0x4074,
  newBarkTownState: 0x4075,
  azaleaTownState: 0x4053,
  cherrygroveCityState: 0x405a,
  ceruleanCityState: 0x4059,
  fanClubClefairy: 0x4065,
  kantoRocketStoryState: 0x406c,
  goldenrodCityState: 0x4069,
  mahoganyTownState: 0x4072,
  leagueState: 0x4070,
  ecruteakCityState: 0x4061,
  ecruteakCityTheater: 0x4062,
  numBadges: 0x4076,
  pewterCityState: 0x4079,
  saffronCityState: 0x40bd,
  ssAquaState: 0x408b,
  rocketPassword: 0x407f,
  tohjoFallsGiovanniState: 0x408d,
  starterMon: 0x4023,
  train: 0x408e,
  triggerElmRocketCall: 0x40b3,
  blackthornCityState: 0x4056,
  hoennStarterChoice: 0x7023,
  vermilionCityState: 0x408f,
  violetCityState: 0x4091,
  route110State: 0x7069,
  route119State: 0x7072,
  mossdeepCityState: 0x705d,
  spaceCenterStairGuardState: 0x709e,
  mossdeepSpaceCenterState: 0x709f,
  slateportMuseum1fState: 0x70aa,
  rustboroCityState: 0x705a,
  mauvilleCityState: 0x7059,
  weatherInstituteState: 0x70b3,
  seafloorCavernState: 0x70a2,
  petalburgCityState: 0x7057,
  lavaridgeTownState: 0x7053,
  victoryRoad1fState: 0x70c3,
} as const

export const storyFlags = {
  hoennDiveAuthorized: 0x607b,
  runningShoes: 0x895,
  noWildRunning: 0x96a,
  hoennWhiteoutToLavaridge: 0x606c,
  sharedPokegear: 0x892,
  sharedMatchCall: 0x1f3,
  disableEncounters: 0x965,
  hideSilverInNewBark: 0x04a,
  hideRoute30Npcs: 0x04f,
  hideElmLabAide: 0x04b,
  adventureStarted: 0x1d4,
  momVisited: 0x265,
  standardRodRoute32Contributed: 0x304,
  standardRodOlivineContributed: 0x305,
  standardRodRoute12Contributed: 0x306,
  standardRodDewfordContributed: 0x307,
  standardRodRoute118Contributed: 0x308,
  standardRodMossdeepContributed: 0x309,
  hideSudowoodo: 0x036,
  hideCeruleanGymPokemon: 0x038,
  hideVermilionSnorlax: 0x03a,
  hideSilverCherrygrove: 0x051,
  hideAzaleaTownRockets: 0x05b,
  hideKurt1: 0x064,
  hideGoldenrodRockets: 0x06c,
  hideGoldenrodUndergroundSilver: 0x06f,
  hideRocketGoldenrodRadiotower1: 0x072,
  hideEcruteakTheaterKimonos: 0x076,
  hideEcruteakRocket: 0x079,
  hideBurnedTowerNpcs: 0x07c,
  hideMahoganyRockets: 0x08c,
  hideSsaquaSailor: 0x088,
  hideRocketHideout2ArianaAndGrunt: 0x090,
  hideRocketHideout3Giovanni: 0x096,
  hideRocketHideout3Petrel: 0x09a,
  hideTohjoGiovanni: 0x0da,
  hideMossdeepSpaceCenter1fTeamMagma: 0x62f4,
  defeatedRivalRoute103: 0x6082,
  defeatedRivalRustboro: 0x60d3,
  defeatedWallyMauville: 0x60be,
  deliveredDevonGoods: 0x6095,
  recoveredDevonGoods: 0x608f,
  defeatedEvilTeamMtChimney: 0x608b,
  groudonAwakenedMagmaHideout: 0x606f,
  teamAquaEscapedSubmarine: 0x6070,
  receivedDevonScope: 0x611d,
  hideAquaHideoutGrunts: 0x639c,
  hideMauvilleCityWally: 0x6324,
  hideRoute120Steven: 0x63cc,
  hideRoute110Rival: 0x6397,
  hideRoute110RivalOnBike: 0x639a,
  hideRoute119Rival: 0x6353,
  hideRoute119RivalOnBike: 0x639b,
  hideLavaridgeTownRival: 0x63a1,
  hideLavaridgeTownRivalOnBike: 0x63a2,
  hidePetalburgCityWally: 0x62d6,
  hideRoute103Rival: 0x62d3,
  hideRustboroCityRival: 0x632e,
  hideOceanicMuseum2fCaptainStern: 0x6377,
  hideLilycoveCityRival: 0x63cb,
  metRivalLilycove: 0x6124,
  hideVictoryRoadEntranceWally: 0x635a,
  hideVictoryRoadExitWally: 0x62ef,
  defeatedWallyVictoryRoad: 0x607e,
  receivedGoGoggles: 0x60dd,
  metRivalRustboro: 0x6120,
  enableRivalMatchCall: 0x60fd,
  hideSproutTowerSilver: 0x058,
  hideAzaleaSilver: 0x05c,
  hideIndigoPlateauSilver: 0x0a6,
  hideMtMoonSilver: 0x0aa,
  hideViridianBlue: 0x0af,
  defeatedViridianGym: 0x236,
  hideCinnabarBlue: 0x0d5,
  hideDragonsDenCavernClair: 0x09f,
  hideDragonsDenShrineClair: 0x0a2,
  hideCeruleanCapeRocket: 0x0b5,
  hideCeruleanGymRocket: 0x0b6,
  hideCeruleanGymTrainers: 0x0b7,
  hideRoute25Misty: 0x0ba,
  hidePowerPlantEngineer: 0x0bc,
  hideCopycatClefairyDoll: 0x0d2,
  hideFanClubClefairyDoll: 0x0d3,
  hiddenMachinePart: 0x1d3,
  returnedMachinePart: 0x1dd,
  receivedHmFlash: 0x1f6,
  receivedTogepiEgg: 0x1ff,
  gotPasswordFromEto: 0x225,
  gotPasswordFromGruntF: 0x226,
  kantoRadioGot: 0x261,
  defeatedVioletGym: 0x227,
  defeatedGoldenrodGym: 0x229,
  defeatedWhitneyTrainer: 0x696,
  defeatedPetalburgGym: 0x64f4,
  hideMauvilleCityWattson: 0x6390,
  hideMauvilleGymWattson: 0x6391,
  cyclingRoad: 0x896,
  isChampion: 0x89f,
  isKantoChampion: 0x8a0,
  systemGameClear: 0x893,
  visitedNewBarkTown: 0x8f0,
  visitedKanto: 0x8ff,
  visitedVermilionCity: 0x904,
  visitedSaffronCity: 0x907,
  badge1: 0x880,
  badge2: 0x881,
  badge3: 0x882,
  badge4: 0x883,
  badge5: 0x884,
  badge6: 0x885,
  badge7: 0x886,
  badge8: 0x887,
  badge9: 0x888,
  badge16: 0x88f,
  johtoStarterChoiceCommitted: 0x930,
  defeatedRoute30Joey: 0x507,
  defeatedRoute30Mikey: 0x508,
  defeatedProton1: 0x6d3,
  defeatedViridianBlue: 0x6af,
  defeatedMossdeepSpaceCenter1fGrunt: 0x60bf,
  registeredRoute30Joey: 0x310,
} as const

export const species = {
  none: 0,
  pidgey: 16,
  shedinja: 292,
  rattata: 19,
  zubat: 41,
  poliwag: 60,
  geodude: 74,
  tentacruel: 73,
  onix: 95,
  hitmonchan: 107,
  krabby: 98,
  goldeen: 118,
  magikarp: 129,
  gyarados: 130,
  lapras: 131,
  dratini: 147,
  treecko: 252,
  torchic: 255,
  mudkip: 258,
  chikorita: 152,
  cyndaquil: 155,
  totodile: 158,
  sentret: 161,
  furret: 162,
  ariados: 168,
  sudowoodo: 185,
  umbreon: 197,
  girafarig: 203,
  steelix: 208,
  gardevoir: 282,
  mightyena: 262,
  wailord: 321,
  dusclops: 356,
  sealeo: 364,
  shelgon: 372,
  salamence: 373,
  wooper: 194,
  quagsire: 195,
  kyogre: 382,
  celebi: 251,
} as const

export const moves = {
  none: 0,
  cut: 15,
  fly: 19,
  tackle: 33,
  surf: 57,
  strength: 70,
  teleport: 100,
  waterfall: 127,
  flash: 148,
  rockSmash: 249,
  whirlpool: 250,
  dive: 291,
} as const

export const hms = {
  cut: 682,
  fly: 683,
  surf: 684,
  strength: 685,
  flash: 686,
  rockSmash: 687,
  waterfall: 688,
  whirlpool: 689,
} as const

export const items = {
  timerBall: 11,
  quickBall: 12,
  masterBall: 4,
  revive: 33,
  antidote: 43,
  ether: 49,
  oranBerry: 520,
  miracleSeed: 429,
  metalCoat: 441,
  tmThunder: 606,
  bicycle: 706,
  machBike: 707,
  acroBike: 708,
  vsSeeker: 714,
  wailmerPail: 720,
  oldRod: 709,
  goodRod: 710,
  superRod: 711,
  ssTicket: 727,
  mysticTicket: 729,
  auroraTicket: 730,
  lostItem: 882,
  machinePart: 883,
  pass: 885,
  squirtBottle: 892,
} as const

export const partyMenuActions = {
  cut: 34,
  flash: 35,
  rockSmash: 36,
  strength: 37,
  surf: 38,
  fly: 39,
  dive: 40,
  waterfall: 41,
  whirlpool: 42,
  teleport: 43,
} as const

export const directions = {
  down: 1,
  up: 2,
  left: 3,
  right: 4,
} as const

export const buttons = {
  a: "A",
  b: "B",
  down: "Down",
  left: "Left",
  r: "R",
  right: "Right",
  select: "Select",
  start: "Start",
  up: "Up",
} as const satisfies Record<string, SkyEmuButton>

export const leagueRegions = ["kanto", "johto", "hoenn"] as const

export const textSpeeds = {
  fast: 2,
  instant: 3,
} as const

export type Checkpoint = keyof typeof checkpoints
export type GameMap = keyof typeof maps
export type Direction = keyof typeof directions
export type StoryVar = keyof typeof storyVars
export type StoryFlag = keyof typeof storyFlags
export type Button = keyof typeof buttons
export type TextSpeed = keyof typeof textSpeeds
export type Species = keyof typeof species
export type FixtureSpecies = Exclude<Species, "none">
export type Move = keyof typeof moves
export type Hm = keyof typeof hms
export type Item = keyof typeof items
export type PartyMenuAction = keyof typeof partyMenuActions
export type LeagueRegion = (typeof leagueRegions)[number]
