#!/usr/bin/env python3
"""Generate test/data/native_hm_coverage.h: the v2 native HM coverage the game must reproduce exactly.

It replays hm_audit.py (game/tools/wild_encounters/v2/) with the reference model, for the v2 tables:

  * the 28 crossing and arrival scenarios (nearby-access scenarios.json plus the v2 scenarios_regions.json),
    TR 20 to 160, day and night, land and Old Rod sources only, ranks as hm_audit reads them;
  * the regional coverage (each region's own utilities), TR 0 to 160, as the best carrier per TR.

Every chance is a whole number out of 5000: slot weight (out of 100) times outcome weight (out of 50).
test/native_hm_catch_coverage.c recomputes each from the game's own distribution and a real
CreateMon and initial moveset, and compares exactly.

--check compares the recorded input digest, which is cheap. --verify regenerates everything.
"""
import argparse
import functools
import json
import sys
from pathlib import Path

TEST_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(TEST_DIR))
import extract_wild_encounter_v2_fixtures as common  # noqa: E402

GAME, REPO = common.GAME, common.REPO
TARGET = TEST_DIR / "data/native_hm_coverage.h"
REVISIONS = REPO / ".product/research/native-hm-windows/revisions"
SCENARIO_FILES = (REVISIONS / "nearby-access/scenarios.json", REVISIONS / "wild-encounters-v2/scenarios_regions.json")
SCENARIO_TRS = range(20, 161)  # the crossing guarantee starts at two badges
REGIONAL_TRS = range(0, 161)
FULL = ("CUT", "FLASH", "STRENGTH", "ROCK_SMASH", "SURF", "WATERFALL", "WHIRLPOOL", "DIVE")
REGIONAL_UTILITIES = (  # the utilities each region's maps need
    ("Johto", FULL), ("Kanto", FULL), ("Hoenn", FULL),
    ("Sevii", ("SURF", "CUT", "ROCK_SMASH", "STRENGTH", "WATERFALL")),
    ("Alola", ("SURF",)), ("Sinjoh", ("ROCK_SMASH",)),
)
LOCAL_ONLY = ("blackthorn_surf", "den_whirlpool")  # rank 0 sources only
FLOOR_PERCENT = 8
WEIGHTS = {"land": [20, 20, 10, 10, 10, 10, 5, 5, 4, 4, 1, 1], "surf": [60, 30, 5, 4, 1], "rock": [60, 30, 5, 4, 1]}
RODS = {"old": [38, 22, 10, 8, 8, 4, 3, 3, 2, 2], "good": [25, 18, 12, 10, 9, 7, 6, 5, 4, 4], "super": [12, 10, 11, 10, 10, 10, 10, 9, 9, 9]}
AREAS = {"land": "WILD_AREA_LAND", "surf": "WILD_AREA_WATER", "rock": "WILD_AREA_ROCKS", "fish": "WILD_AREA_FISHING"}
ROD_CONSTANTS = {None: "WILD_ENCOUNTER_FISHING_ROD_NONE", "old": "WILD_ENCOUNTER_FISHING_ROD_OLD",
                 "good": "WILD_ENCOUNTER_FISHING_ROD_GOOD", "super": "WILD_ENCOUNTER_FISHING_ROD_SUPER"}


class Coverage:
    def __init__(self):
        self.model = common.Model()
        h = self.model.h
        h.ROD_SHIFT = {"old": 0, "good": 0, "super": 0}  # wild level scaling: rods use the place level
        h.apply_roster_v2()
        self.moveset = functools.lru_cache(maxsize=None)(h.moveset)
        self.units = functools.lru_cache(maxsize=None)(self._units)
        self.tables = h.load_tables()

    def _units(self, cap, level, region, move):
        """Outcome weight (out of 50) of a slot cap at a place level whose catch knows the move."""
        return sum(int(probability * 50) for species, lv, probability in self.model.h.slot_dist(cap, level, region)
                   if move in self.moveset(species, lv))

    def chance(self, slots, weights, level, region, move):
        """Numerator out of 5000 (the weights add up to 100)."""
        assert sum(weights) == 100
        return sum(weight * self.units(cap, level, region, move) for cap, weight in zip(slots, weights) if cap != "NONE")

    def sources(self, key):
        table = self.tables[key]
        for method in ("land", "surf", "rock"):
            if method in table:
                yield method, None, table[method], WEIGHTS[method]
        if "fish" in table:
            for rod in ("old", "good", "super"):
                yield "fish", rod, table["fish"], RODS[rod]


def region_of(model, key):
    return model.meta[key]["region"]


def scenarios():
    out = []
    for path in SCENARIO_FILES:
        out += json.loads(path.read_text())["scenarios"]
    return out


def render():
    cov = Coverage()
    model = cov.model
    index = {key: number for number, key in enumerate(model.keys)}
    lines = ["// Generated by test/extract_native_hm_coverage_fixtures.py; do not edit.",
             f"// Input digest: {common.input_digest()}"]

    # ---- scenarios ----
    all_scenarios = scenarios()
    assert len(all_scenarios) == 28
    source_blocks, best_blocks, table_rows = [], [], []
    for number, scenario in enumerate(all_scenarios):
        max_rank = 0 if scenario["id"] in LOCAL_ONLY else 1
        sources = []
        for source in scenario["maps"]:
            key = source["map"].replace("MAP_CINNABAR_ISLAND_HNS", "MAP_CINNABAR_ISLAND")
            if key not in model.tables or source["rank"] > max_rank:
                continue
            for method, area in (("land_mons", "land"), ("fishing_mons", "fish")):
                if method in source["methods"]:
                    sources.append((key, area))
        move = "MOVE_" + scenario["move"]
        best_rows = []
        for time in ("day", "night"):
            row = []
            for tr in SCENARIO_TRS:
                best = 0
                for key, area in sources:
                    region = region_of(model, key)
                    level = model.place_level(key, tr)
                    for method, rod, slots, weights in cov.sources(key):
                        if (area == "land" and method == "land") or (area == "fish" and rod == "old"):
                            slots_for_time = slots.get(time, slots.get("day"))
                            best = max(best, cov.chance(slots_for_time, weights, level, region, move[len("MOVE_"):]))
                assert best * 100 >= FLOOR_PERCENT * 5000, f"{scenario['id']} {time} TR {tr} falls below {FLOOR_PERCENT}%: {best}/5000"
                row.append(best)
            best_rows.append(row)
        source_blocks.append(f"static const struct AcquisitionSource sScenarioSources{number}[] =\n{{\n"
                             + "".join(f"    {{ {index[key]}, {AREAS[area]} }}, // {key}\n" for key, area in sources) + "};\n")
        best_blocks.append(f"static const u16 sScenarioBest{number}[2][{len(SCENARIO_TRS)}] =\n{{\n"
                           + "".join("    { " + ", ".join(map(str, row)) + " },\n" for row in best_rows) + "};\n")
        table_rows.append(f'    {{ "{scenario["id"]}", {move}, sScenarioSources{number}, ARRAY_COUNT(sScenarioSources{number}), sScenarioBest{number} }},')
    lines += [f"_Static_assert(NATIVE_HM_SCENARIO_COUNT == {len(all_scenarios)} && NATIVE_HM_SCENARIO_FIRST_TR == {SCENARIO_TRS[0]}"
              f" && NATIVE_HM_SCENARIO_TRS == {len(SCENARIO_TRS)}, \"scenario fixture shape\");", ""]
    lines += source_blocks + best_blocks
    lines += ["static const struct AcquisitionScenario sAcquisitionScenarios[] =", "{"] + table_rows + ["};", ""]

    # ---- regional coverage ----
    regions = {}
    for key in model.keys:
        regions.setdefault(region_of(model, key), []).append(key)
    profiles, rows = [], []
    for region, utilities in REGIONAL_UTILITIES:
        for utility in utilities:
            witness = []
            for tr in REGIONAL_TRS:
                best, found = 0, None
                for key in regions[region]:
                    level = model.place_level(key, tr)
                    for method, rod, slots, weights in cov.sources(key):
                        for time in ("day", "night"):
                            chance = cov.chance(slots[time], weights, level, region, utility)
                            if chance > best:
                                best, found = chance, (index[key], 0 if time == "day" else 1, AREAS[method], ROD_CONSTANTS[rod])
                assert best > 0, f"regional coverage gap: {region}/{utility} at TR {tr}"
                if found not in profiles:
                    profiles.append(found)
                witness.append((profiles.index(found), best))
            rows.append((region, utility, witness))
    lines += [f"_Static_assert(NATIVE_HM_REGIONAL_COUNT == {len(rows)} && NATIVE_HM_REGIONAL_TRS == {len(REGIONAL_TRS)}, \"regional fixture shape\");", "",
              "static const struct CoverageProfile sRegionalProfiles[] =", "{"]
    for header, time, area, rod in profiles:
        lines.append(f"    {{ {header}, {'TIME_DAY' if time == 0 else 'TIME_NIGHT'}, {area}, {rod} }}, // {model.keys[header]}")
    lines += ["};", "", "static const struct RegionalCoverage sRegionalCoverage[] =", "{"]
    for region, utility, witness in rows:
        lines.append(f'    {{ "{region}/{utility}", MOVE_{utility},')
        lines.append("      { " + ", ".join(str(profile) for profile, _ in witness) + " },")
        lines.append("      { " + ", ".join(str(chance) for _, chance in witness) + " } },")
    lines += ["};", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="compare the recorded input digest (cheap)")
    parser.add_argument("--verify", action="store_true", help="regenerate everything and compare")
    args = parser.parse_args()
    if args.verify:
        if TARGET.read_text() != render():
            raise SystemExit(f"{TARGET} is stale")
    elif args.check:
        if f"// Input digest: {common.input_digest()}" not in TARGET.read_text().split("\n")[:3]:
            raise SystemExit(f"{TARGET} is stale: run test/extract_native_hm_coverage_fixtures.py")
    else:
        TARGET.write_text(render())


if __name__ == "__main__":
    main()
