#!/usr/bin/env python3
"""Copy approved source identities into C fixtures; compute no game outcomes."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REVISION = ROOT / '.product/research/native-hm-windows/revisions/nearby-access'
TARGET = ROOT / 'game/test/data/native_hm_coverage.h'
AREAS = {'land_mons': 'LAND', 'water_mons': 'WATER', 'rock_smash_mons': 'ROCKS', 'fishing_mons': 'FISHING'}
RODS = {'NONE': 'NONE', 'OLD_ROD': 'OLD', 'GOOD_ROD': 'GOOD', 'SUPER_ROD': 'SUPER'}


def render():
    coverage = json.loads((REVISION / 'coverage.json').read_text())['results']
    scenarios = json.loads((REVISION / 'scenarios.json').read_text())['scenarios']
    assert len(coverage) == 48
    assert len(scenarios) == 11
    lines = ['// Generated by test/extract_native_hm_coverage_fixtures.py; do not edit.']
    for name in ('coverage.json', 'scenarios.json'):
        lines.append(f'// Approved {name} SHA256: {hashlib.sha256((REVISION / name).read_bytes()).hexdigest()}')
    profiles = []
    cells = []
    for row in coverage:
        assert set(row['witnesses']) == {str(n) for n in range(81)}
        ids = []
        for rating in range(81):
            p = row['witnesses'][str(rating)]
            key = (p['map'], p['time'], AREAS[p['method']], RODS[p['rod']])
            if key not in profiles:
                profiles.append(key)
            ids.append(profiles.index(key))
        cells.append((row, ids))
    lines += ['static const struct CoverageProfile sRegionalProfiles[] =', '{']
    for map_name, time, area, rod in profiles:
        lines.append(f'    {{ {map_name}, {time}, WILD_AREA_{area}, WILD_ENCOUNTER_FISHING_ROD_{rod} }},')
    lines += ['};', '', 'static const struct RegionalCoverage sRegionalCoverage[] =', '{']
    for row, ids in cells:
        lines.append(f'    {{ "{row["region"]}/{row["mode"]}/{row["move"]}", {row["move"]}, {"TRUE" if row["mode"] == "modern" else "FALSE"},')
        lines.append('      { ' + ', '.join(map(str, ids)) + ' } },')
    lines += ['};', '']
    for index, scenario in enumerate(scenarios):
        lines += [f'static const struct AcquisitionSource sScenarioSources{index}[] =', '{']
        for source in scenario['maps']:
            # The current specification requires the two local proofs without Ice Path.
            if scenario['id'] in ('blackthorn_surf', 'den_whirlpool') and source['rank'] != 0:
                continue
            for method in source['methods']:
                assert method in ('land_mons', 'fishing_mons')
                clock = 'FALSE' if source['map'].endswith('_HNS') else 'TRUE'
                lines.append(f'    {{ {source["map"]}, WILD_AREA_{AREAS[method]}, {clock} }},')
        lines += ['};', '']
    lines += ['static const struct AcquisitionScenario sAcquisitionScenarios[] =', '{']
    for index, scenario in enumerate(scenarios):
        lines.append(f'    {{ "{scenario["id"]}", MOVE_{scenario["move"]}, sScenarioSources{index}, ARRAY_COUNT(sScenarioSources{index}) }},')
    return '\n'.join(lines + ['};', ''])


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = render()
    if args.check:
        if TARGET.read_text() != expected:
            raise SystemExit(f'{TARGET} is stale')
    else:
        TARGET.write_text(expected)
