#!/usr/bin/env python3
"""Refresh representative test records from trainerproc's generated headers."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
RECORDS = {
    "trainers_hns.h": ("TRAINER_ABE_HNS", "TRAINER_QUINN_HNS", "TRAINER_BROCK_HNS"),
    "trainers.h": ("TRAINER_SAWYER_1", "TRAINER_TATE_AND_LIZA_1"),
    "trainers_wayfarer_local.h": ("TRAINER_VIRIDIAN_GYM_GIOVANNI_HNS",),
    "trainers_wayfarer_kanto.h": ("TRAINER_WAYFARER_KANTO_BLUE_BULBASAUR",),
    "trainers_wayfarer_celadon_hideout.h": ("TRAINER_CELADON_HIDEOUT_GIOVANNI_HNS",),
}


def render():
    output = ["// Generated by test/extract_trainer_scaling_fixtures.py; do not edit.", "#if IS_WAYFARER"]
    for filename, ids in RECORDS.items():
        source = (ROOT / "src/data" / filename).read_text()
        for trainer_id in ids:
            match = re.search(r"^[ \t]*\[" + trainer_id + r"\] =\n", source, re.M)
            if match is None:
                raise ValueError(f"Missing {trainer_id} in {filename}")
            start = match.start()
            end = source.index("\n    },", start) + len("\n    },")
            entry = re.sub(r"^#line .*\n", "", source[start:end], flags=re.M)
            output.extend((f"// Source: src/data/{filename}", entry))
    output.append("#endif")
    return "\n".join(output) + "\n"


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "test/trainer_scaling_production_fixtures.h"
    expected = render()
    if args.check:
        if target.read_text() != expected:
            raise SystemExit(f"{target.name} is stale; regenerate trainer fixtures")
        print("Trainer fixtures match trainerproc output")
    else:
        target.write_text(expected)
