#!/usr/bin/env python3
"""Refresh representative test records from trainerproc's generated headers."""
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
RECORDS = {
    "trainers_hns.h": ("TRAINER_ABE_HNS", "TRAINER_QUINN_HNS", "TRAINER_BROCK_HNS"),
    "trainers.h": ("TRAINER_SAWYER_1", "TRAINER_TATE_AND_LIZA_1"),
    "trainers_wayfarer_local.h": ("TRAINER_VIRIDIAN_GYM_GIOVANNI_HNS",),
    "trainers_wayfarer_kanto.h": ("TRAINER_WAYFARER_KANTO_BLUE_BULBASAUR",),
    "trainers_wayfarer_celadon_hideout.h": ("TRAINER_CELADON_HIDEOUT_GIOVANNI_HNS",),
}
TRAINER_HEADERS = (
    "trainers_hns.h",
    "trainers.h",
    "trainers_wayfarer_local.h",
    "trainers_wayfarer_indigo.h",
)


def append_record(output, filename, trainer_id, source):
    match = re.search(r"^[ \t]*\[" + trainer_id + r"\] =\n", source, re.M)
    if match is None:
        raise ValueError(f"Missing {trainer_id} in {filename}")
    start = match.start()
    end = source.index("\n    },", start) + len("\n    },")
    entry = re.sub(r"^#line .*\n", "", source[start:end], flags=re.M)
    output.extend((f"// Source: src/data/{filename}", entry))


def render():
    output = ["// Generated by test/extract_trainer_scaling_fixtures.py; do not edit.",
              '#include "config/notable_trainers.h"', "#if IS_WAYFARER"]
    sources = {filename: (ROOT / "src/data" / filename).read_text() for filename in set(RECORDS) | set(TRAINER_HEADERS)}
    for filename, ids in RECORDS.items():
        for trainer_id in ids:
            append_record(output, filename, trainer_id, sources[filename])

    # These live in league_tiers.h already; the remaining selected sources
    # need real metadata and legacy parties in the native gTrainers fixture.
    existing = set(re.findall(r"^\s*\[(TRAINER_\w+)\]", (ROOT / "test/league_tiers.h").read_text(), re.M))
    existing.update(trainer_id for ids in RECORDS.values() for trainer_id in ids)
    catalog = json.loads((ROOT / "tools/notable_trainers/catalog.json").read_text())
    output.append("#if WAYFARER_V0_TRAINERS")
    for trainer in catalog["trainers"]:
        trainer_id = trainer["league"]["sourceTrainerId"]
        if trainer_id in existing:
            continue
        matches = [filename for filename in TRAINER_HEADERS
                   if re.search(r"^[ \t]*\[" + trainer_id + r"\] =\n", sources[filename], re.M)]
        if len(matches) != 1:
            raise ValueError(f"Expected one production record for {trainer_id}, found {matches}")
        append_record(output, matches[0], trainer_id, sources[matches[0]])
        existing.add(trainer_id)
    output.append("#endif // WAYFARER_V0_TRAINERS")
    output.append("#endif")
    return "\n".join(output) + "\n"


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "test/trainer_scaling_production_fixtures.h"
    expected = render()
    if args.check:
        if target.read_text() != expected:
            raise SystemExit(f"{target.name} is stale; regenerate trainer fixtures")
        print("Trainer fixtures match trainerproc output")
    else:
        target.write_text(expected)
