#include "global.h"
#include "malloc.h"
#include "pokemon.h"
#include "test/test.h"
#include "wild_encounter.h"
#include "constants/maps.h"

// Native HM coverage for the Wayfarer v2 wild tables, through production code: the exact
// outcome distribution of every slot (GetWildEncounterSlotOutcomes), and whether a Pokemon the
// game creates at that species and level (a real CreateMon and initial moveset) knows the move.
// A chance is a whole number out of 5000: slot weight (out of 100) times outcome weight (out of
// 50). The fixture (test/data/native_hm_coverage.h, generated by
// test/extract_native_hm_coverage_fixtures.py) holds the same exact chance the reference model
// (game/tools/wild_encounters/v2/hm_audit.py) finds, so each number is compared exactly.
//
//   - 28 crossing and arrival scenarios: TR 20 to 160, day and night, land and Old Rod sources
//     only, each reaching the 8% floor at one reachable source.
//   - Regional coverage: each region's own utilities, TR 0 to 160, with a carrier at every TR.

#if IS_WAYFARER

#define NATIVE_HM_SCENARIO_COUNT 28
#define NATIVE_HM_SCENARIO_FIRST_TR 20
#define NATIVE_HM_SCENARIO_TRS 141
#define NATIVE_HM_REGIONAL_COUNT 31
#define NATIVE_HM_REGIONAL_TRS 161
#define COVERAGE_DENOMINATOR 5000
#define COVERAGE_FLOOR_PERCENT 8
#define SCENARIO_BLOCK_SIZE 12
#define REGIONAL_BLOCK_SIZE 12

struct CoverageProfile
{
    u16 header;
    u8 time;
    u8 area;
    u8 rod;
};

struct RegionalCoverage
{
    const char *name;
    u16 move;
    u16 profiles[NATIVE_HM_REGIONAL_TRS];
    u16 chances[NATIVE_HM_REGIONAL_TRS];
};

struct AcquisitionSource
{
    u16 header;
    u8 area;
};

struct AcquisitionScenario
{
    const char *name;
    u16 move;
    const struct AcquisitionSource *sources;
    u8 sourceCount;
    const u16 (*best)[NATIVE_HM_SCENARIO_TRS]; // [day, night][TR - first TR]
};

#include "data/native_hm_coverage.h"

// Direct-mapped cache of (species, level) -> knows the move, packed as key << 1 | knows. The heap is
// small, so it holds 512 entries.
#define MOVE_CACHE_SIZE 512

static u32 *sMoveCache;

static void SetCoverageMode(void)
{
    gSaveBlock3Ptr->challengeSettings.tx_Random_Moves = FALSE;
    gSaveBlock3Ptr->challengeSettings.tx_Random_WildPokemon = FALSE;
    // Every parameter of a test shares one heap, so each case frees its cache (FreeCoverageMode).
    sMoveCache = AllocZeroed(MOVE_CACHE_SIZE * sizeof(*sMoveCache));
    EXPECT(sMoveCache != NULL);
}

static void FreeCoverageMode(void)
{
    Free(sMoveCache);
    sMoveCache = NULL;
}

static bool8 CaughtMonKnowsMove(u16 species, u8 level, u16 move)
{
    u32 key = species * 128 + level + 1;
    u32 *cache = &sMoveCache[key % MOVE_CACHE_SIZE];

    // Only actual production-created movesets enter this cache.
    if (*cache >> 1 != key)
    {
        struct Pokemon mon;
        u8 slot;
        u32 knows = 0;

        CreateMon(&mon, species, level, 0, OTID_STRUCT_PRESET(0));
        GiveMonInitialMoveset(&mon);
        for (slot = 0; slot < MAX_MON_MOVES; slot++)
        {
            if (GetMonData(&mon, MON_DATA_MOVE1 + slot) == move)
                knows = 1;
        }
        *cache = key << 1 | knows;
    }
    return *cache & 1;
}

static bool8 ResolveCoverageProfile(u32 header, u32 time, u32 area, u32 rod, struct WildEncounterProfileView *view)
{
    struct WildEncounterProfileContext context =
    {
        .headerId = header,
        .timeOfDay = time,
        .area = area,
        .fishingRod = rod,
    };

    return GetWildEncounterProfileView(&context, view);
}

// The numerator, out of 5000, of a catch from the profile at a Trainer Rating knowing the move.
static u32 ProfileMoveChance(const struct WildEncounterProfileView *view, u32 rating, u16 move)
{
    u32 numerator = 0, weightTotal = 0;
    u8 slot;

    for (slot = view->entryStart; slot < view->entryStart + view->entryCount; slot++)
    {
        struct WildEncounterSlotOutcome outcomes[WILD_ENCOUNTER_MAX_SLOT_OUTCOMES];
        u32 count = GetWildEncounterSlotOutcomes(view, slot, rating, outcomes);
        u32 units = 0, i;

        weightTotal += view->weights[slot];
        for (i = 0; i < count; i++)
        {
            if (CaughtMonKnowsMove(outcomes[i].species, outcomes[i].level, move))
                units += outcomes[i].weight;
        }
        numerator += view->weights[slot] * units;
    }
    EXPECT_EQ(weightTotal, 100);
    return numerator;
}

TEST("Wayfarer native HM regional coverage keeps its exact carrier at every rating")
{
    u32 row = 0, block = 0;
    u32 parameterRow, parameterBlock, rating;
    const struct RegionalCoverage *cell;

    for (parameterRow = 0; parameterRow < NATIVE_HM_REGIONAL_COUNT; parameterRow++)
        for (parameterBlock = 0; parameterBlock * REGIONAL_BLOCK_SIZE < NATIVE_HM_REGIONAL_TRS; parameterBlock++)
            PARAMETRIZE_LABEL("%s TR %d-%d", sRegionalCoverage[parameterRow].name, parameterBlock * REGIONAL_BLOCK_SIZE,
                              min((parameterBlock + 1) * REGIONAL_BLOCK_SIZE, NATIVE_HM_REGIONAL_TRS) - 1)
            {
                row = parameterRow;
                block = parameterBlock;
            }

    EXPECT_EQ(ARRAY_COUNT(sRegionalCoverage), NATIVE_HM_REGIONAL_COUNT);
    SetCoverageMode();
    cell = &sRegionalCoverage[row];
    for (rating = block * REGIONAL_BLOCK_SIZE; rating < (block + 1) * REGIONAL_BLOCK_SIZE && rating < NATIVE_HM_REGIONAL_TRS; rating++)
    {
        const struct CoverageProfile *profile = &sRegionalProfiles[cell->profiles[rating]];
        struct WildEncounterProfileView view;
        u32 chance;

        if (!ResolveCoverageProfile(profile->header, profile->time, profile->area, profile->rod, &view))
            Test_ExitWithResult(TEST_RESULT_FAIL, __LINE__,
                ":L%s:%d: regional %s TR %d is missing header %d area %d time %d rod %d",
                gTestRunnerState.test->filename, __LINE__, cell->name, rating,
                profile->header, profile->area, profile->time, profile->rod);
        chance = ProfileMoveChance(&view, rating, cell->move);
        if (chance == 0)
            Test_ExitWithResult(TEST_RESULT_FAIL, __LINE__,
                ":L%s:%d: regional %s TR %d header %d area %d time %d rod %d has no carrier",
                gTestRunnerState.test->filename, __LINE__, cell->name, rating,
                profile->header, profile->area, profile->time, profile->rod);
        if (chance != cell->chances[rating])
            Test_ExitWithResult(TEST_RESULT_FAIL, __LINE__,
                ":L%s:%d: regional %s TR %d header %d area %d time %d rod %d chance %d/5000, model %d/5000",
                gTestRunnerState.test->filename, __LINE__, cell->name, rating,
                profile->header, profile->area, profile->time, profile->rod, chance, cell->chances[rating]);
    }
    FreeCoverageMode();
}

TEST("Wayfarer native HM crossing and arrival scenarios reach the 8 percent floor with the exact chance from Rating 20 to 160")
{
    u32 scenarioId = 0, clock = 0, block = 0;
    u32 parameterScenario, parameterClock, parameterBlock, rating;
    const struct AcquisitionScenario *scenario;

    for (parameterScenario = 0; parameterScenario < NATIVE_HM_SCENARIO_COUNT; parameterScenario++)
        for (parameterClock = 0; parameterClock < 2; parameterClock++)
            for (parameterBlock = 0; parameterBlock * SCENARIO_BLOCK_SIZE < NATIVE_HM_SCENARIO_TRS; parameterBlock++)
                PARAMETRIZE_LABEL("%s %s TR %d-%d", sAcquisitionScenarios[parameterScenario].name, parameterClock == 0 ? "day" : "night",
                                  NATIVE_HM_SCENARIO_FIRST_TR + parameterBlock * SCENARIO_BLOCK_SIZE,
                                  NATIVE_HM_SCENARIO_FIRST_TR + min((parameterBlock + 1) * SCENARIO_BLOCK_SIZE, NATIVE_HM_SCENARIO_TRS) - 1)
                {
                    scenarioId = parameterScenario;
                    clock = parameterClock;
                    block = parameterBlock;
                }

    EXPECT_EQ(ARRAY_COUNT(sAcquisitionScenarios), NATIVE_HM_SCENARIO_COUNT);
    SetCoverageMode();
    scenario = &sAcquisitionScenarios[scenarioId];
    for (rating = block * SCENARIO_BLOCK_SIZE; rating < (block + 1) * SCENARIO_BLOCK_SIZE && rating < NATIVE_HM_SCENARIO_TRS; rating++)
    {
        u32 best = 0;
        u8 sourceId;

        for (sourceId = 0; sourceId < scenario->sourceCount; sourceId++)
        {
            const struct AcquisitionSource *source = &scenario->sources[sourceId];
            struct WildEncounterProfileView view;
            u32 chance;

            // Land and Old Rod sources only: good and Super Rod odds are reported, not required.
            if (!ResolveCoverageProfile(source->header, clock == 0 ? TIME_DAY : TIME_NIGHT, source->area, source->area == WILD_AREA_FISHING ? WILD_ENCOUNTER_FISHING_ROD_OLD : WILD_ENCOUNTER_FISHING_ROD_NONE, &view))
                continue;
            chance = ProfileMoveChance(&view, NATIVE_HM_SCENARIO_FIRST_TR + rating, scenario->move);
            best = max(best, chance);
        }
        if (best != scenario->best[clock][rating])
            Test_ExitWithResult(TEST_RESULT_FAIL, __LINE__,
                ":L%s:%d: scenario %s %s TR %d best source chance %d/5000, model %d/5000",
                gTestRunnerState.test->filename, __LINE__, scenario->name, clock == 0 ? "day" : "night",
                NATIVE_HM_SCENARIO_FIRST_TR + rating, best, scenario->best[clock][rating]);
        if (best * 100 < COVERAGE_FLOOR_PERCENT * COVERAGE_DENOMINATOR)
            Test_ExitWithResult(TEST_RESULT_FAIL, __LINE__,
                ":L%s:%d: scenario %s %s TR %d has no qualifying single source (best %d/5000)",
                gTestRunnerState.test->filename, __LINE__, scenario->name, clock == 0 ? "day" : "night",
                NATIVE_HM_SCENARIO_FIRST_TR + rating, best);
    }
    FreeCoverageMode();
}

#endif // IS_WAYFARER
