// Generated by test/extract_trainer_scaling_fixtures.py; do not edit.
#if IS_WAYFARER
// Source: src/data/trainers_hns.h
    [DIFFICULTY_NORMAL][TRAINER_ABE_HNS] =
    {
        .trainerName = _("ABE"),
        .trainerClass = TRAINER_CLASS_BIRD_KEEPER_HNS,
        .trainerPic = TRAINER_PIC_FRONT_BIRD_KEEPER,
        .gender = TRAINER_GENDER_MALE,
        .encounterMusic = TRAINER_ENCOUNTER_MUSIC_HG_BOY_1,
        .battleType = TRAINER_BATTLE_TYPE_SINGLES,
        .aiFlags = AI_FLAG_CHECK_BAD_MOVE,
        .trainerBackPic = TRAINER_PIC_FRONT_BIRD_KEEPER,
        .partySize = 1,
        .party = (const struct TrainerMon[])
        {
            {
            .species = SPECIES_SPEAROW,
            .gender = TRAINER_MON_RANDOM_GENDER,
            .iv = TRAINER_PARTY_IVS(0, 0, 0, 0, 0, 0),
            .lvl = 9,
            .ball = POKEBALL_COUNT,
            .nature = NATURE_HARDY,
            .dynamaxLevel = MAX_DYNAMAX_LEVEL,
            },
        },
    },
// Source: src/data/trainers_hns.h
    [DIFFICULTY_NORMAL][TRAINER_QUINN_HNS] =
    {
        .trainerName = _("QUINN"),
        .trainerClass = TRAINER_CLASS_COOLTRAINER_HNS,
        .trainerPic = TRAINER_PIC_FRONT_COOLTRAINER_F,
        .gender = TRAINER_GENDER_MALE,
        .encounterMusic = TRAINER_ENCOUNTER_MUSIC_HG_GIRL_2,
        .battleType = TRAINER_BATTLE_TYPE_SINGLES,
        .aiFlags = AI_FLAG_CHECK_BAD_MOVE,
        .trainerBackPic = TRAINER_PIC_FRONT_COOLTRAINER_F,
        .partySize = 2,
        .party = (const struct TrainerMon[])
        {
            {
            .species = SPECIES_IVYSAUR,
            .gender = TRAINER_MON_RANDOM_GENDER,
            .iv = TRAINER_PARTY_IVS(0, 0, 0, 0, 0, 0),
            .lvl = 58,
            .ball = POKEBALL_COUNT,
            .nature = NATURE_HARDY,
            .dynamaxLevel = MAX_DYNAMAX_LEVEL,
            },
            {
            .species = SPECIES_STARMIE,
            .gender = TRAINER_MON_RANDOM_GENDER,
            .iv = TRAINER_PARTY_IVS(0, 0, 0, 0, 0, 0),
            .lvl = 58,
            .ball = POKEBALL_COUNT,
            .nature = NATURE_HARDY,
            .dynamaxLevel = MAX_DYNAMAX_LEVEL,
            },
        },
    },
// Source: src/data/trainers.h
    [DIFFICULTY_NORMAL][TRAINER_SAWYER_1] =
    {
        .trainerName = _("SAWYER"),
        .trainerClass = TRAINER_CLASS_HIKER,
        .trainerPic = TRAINER_PIC_FRONT_HIKER,
        .gender = TRAINER_GENDER_MALE,
        .encounterMusic = TRAINER_ENCOUNTER_MUSIC_HIKER,
        .battleType = TRAINER_BATTLE_TYPE_SINGLES,
        .aiFlags = AI_FLAG_BASIC_TRAINER,
        .trainerBackPic = TRAINER_PIC_FRONT_HIKER,
        .partySize = 1,
        .party = (const struct TrainerMon[])
        {
            {
            .species = SPECIES_GEODUDE,
            .gender = TRAINER_MON_RANDOM_GENDER,
            .iv = TRAINER_PARTY_IVS(0, 0, 0, 0, 0, 0),
            .lvl = 21,
            .ball = POKEBALL_COUNT,
            .nature = NATURE_HARDY,
            .dynamaxLevel = MAX_DYNAMAX_LEVEL,
            },
        },
    },
#endif
