#include "global.h"
#include "notable_moves.h"
#include "test/test.h"
#include "wild_encounter.h"
#include "constants/maps.h"

// Wild encounters v2: production must reproduce the reference model
// (game/tools/wild_encounters/v2/hm_model.py) exactly. The fixture is generated by
// test/extract_wild_encounter_v2_fixtures.py. This file proves:
//   - every header holds the map the generator expects, in order;
//   - every species of a v2 slot cap or step-down chain has the model's young limit, baby flag,
//     step-down predecessor and evolution level, and prowler minimum in each region;
//   - every header's place level at every TR from 0 to 160;
//   - every day and night slot's exact outcome distribution (species, level and weight, merged)
//     at every TR from 0 to 160, as a CRC per header and TR block;
// and, while walking those distributions, the spec's invariants: no encounter at any TR is below
// its stage's evolution level, above 100, or below a prowler minimum, and a young-level slot never
// reaches its next evolution level except a prowler at its minimum.

#if IS_WAYFARER

#include "data/wild_encounter_v2.h"

#define PARTITIONS 32
#define TIMES_USED 2 // day and night; morning and evening alias them (checked in wild_encounter_scaling.c)

static u32 CountHeaders(void)
{
    u32 count;

    for (count = 0; gWildMonHeaders[count].mapGroup != MAP_GROUP(MAP_UNDEFINED); count++)
    {
    }
    return count;
}

static u32 CrcStart(void)
{
    return 0xFFFFFFFF;
}

static u32 CrcByte(u32 crc, u8 byte)
{
    crc = (crc >> 4) ^ sWildV2CrcNibbles[(crc ^ byte) & 0xF];
    return (crc >> 4) ^ sWildV2CrcNibbles[(crc ^ (byte >> 4)) & 0xF];
}

static u32 CrcFinish(u32 crc)
{
    return crc ^ 0xFFFFFFFF;
}

TEST("Wild encounters v2: every header holds the map the reference model lists, in order")
{
    u32 header;

    EXPECT_EQ(CountHeaders(), WILD_V2_HEADER_COUNT);
    for (header = 0; header < WILD_V2_HEADER_COUNT; header++)
    {
        EXPECT_EQ(gWildMonHeaders[header].mapGroup, MAP_GROUP(sWildV2HeaderMaps[header]));
        EXPECT_EQ(gWildMonHeaders[header].mapNum, MAP_NUM(sWildV2HeaderMaps[header]));
    }
}

static const struct WildProwlerMinimum *FindProwler(u16 species)
{
    u32 low = 0, high = gWildProwlerMinimumCount;

    while (low < high)
    {
        u32 mid = low + (high - low) / 2;

        if (gWildProwlerMinimums[mid].species < species)
            low = mid + 1;
        else
            high = mid;
    }
    if (low < gWildProwlerMinimumCount && gWildProwlerMinimums[low].species == species)
        return &gWildProwlerMinimums[low];
    return NULL;
}

// The prowler minimum a species has in a place region (0 none), from the generated table.
static u32 ProwlerMinimum(u16 species, u32 region)
{
    const struct WildProwlerMinimum *prowler = FindProwler(species);

    if (prowler == NULL
     || (region == WILD_PLACE_REGION_SAFARI && prowler->exemptInSafari)
     || (region == WILD_PLACE_REGION_SINJOH && prowler->exemptInSinjoh))
        return 0;
    return prowler->minimumLevel;
}

// The young-level limit of a slot cap: babies 10, else one under the lowest evolution level; -1 none.
static s32 YoungLimit(u16 cap)
{
    u32 level;

    if (IsBabySpecies(cap))
        return 10;
    level = GetSpeciesLowestEvolutionLevel(cap);
    return level != 0 ? (s32)level - 1 : -1;
}

TEST("Wild encounters v2: young limit, baby flag, step-down edge and prowler minimum of every cap and its chain match the model")
{
    u32 row;

    for (row = 0; row < ARRAY_COUNT(sWildV2SpeciesRows); row++)
    {
        const struct WildV2SpeciesRow *expected = &sWildV2SpeciesRows[row];
        u8 evolutionLevel;
        u16 predecessor = GetSpeciesStepDownPredecessor(expected->species, &evolutionLevel);

        EXPECT_EQ(IsBabySpecies(expected->species), expected->baby);
        EXPECT_EQ(YoungLimit(expected->species), expected->youngLimit);
        EXPECT_EQ(predecessor, expected->predecessor);
        EXPECT_EQ(predecessor == SPECIES_NONE ? 0 : evolutionLevel, expected->evolutionLevel);
        EXPECT_EQ(ProwlerMinimum(expected->species, WILD_PLACE_REGION_OTHER), expected->prowlerMinimum[0]);
        EXPECT_EQ(ProwlerMinimum(expected->species, WILD_PLACE_REGION_SAFARI), expected->prowlerMinimum[1]);
        EXPECT_EQ(ProwlerMinimum(expected->species, WILD_PLACE_REGION_SINJOH), expected->prowlerMinimum[2]);
    }
}

TEST("Wild encounters v2: every place level at every Trainer Rating matches the model and stays in 1..100")
{
    u32 header, tr;

    for (header = 0; header < WILD_V2_HEADER_COUNT; header++)
    {
        u32 crc = CrcStart();

        for (tr = 0; tr <= 160; tr++)
        {
            u32 level = GetWildEncounterPlaceLevel(header, tr);

            EXPECT_GE(level, 1);
            EXPECT_LE(level, MAX_LEVEL);
            crc = CrcByte(crc, level);
        }
        EXPECT_EQ(CrcFinish(crc), sWildV2PlaceDigests[header]);
    }
}

// ---- slot distributions ----

static const struct WildPokemonInfo *TimeMethodInfo(u32 header, u32 time, u32 method)
{
    const struct WildEncounterTypes *types = &gWildMonHeaders[header].encounterTypes[time == 0 ? TIME_DAY : TIME_NIGHT];

    switch (method)
    {
    case 0:
        return types->landMonsInfo;
    case 1:
        return types->waterMonsInfo;
    case 2:
        return types->rockSmashMonsInfo;
    default:
        return types->fishingMonsInfo;
    }
}

static const enum WildPokemonArea sMethodAreas[] = { WILD_AREA_LAND, WILD_AREA_WATER, WILD_AREA_ROCKS, WILD_AREA_FISHING };
static const u8 sMethodSlots[] = { LAND_WILD_COUNT, WATER_WILD_COUNT, ROCK_WILD_COUNT, FISH_WILD_COUNT };

// Merges equal (species, level) entries and sorts by species then level. Returns the count.
static u32 MergeOutcomes(struct WildEncounterSlotOutcome *outcomes, u32 count)
{
    u32 merged = 0, i, j;

    for (i = 0; i < count; i++)
    {
        struct WildEncounterSlotOutcome entry = outcomes[i];

        for (j = 0; j < merged; j++)
            if (outcomes[j].species == entry.species && outcomes[j].level == entry.level)
                break;
        if (j < merged)
        {
            outcomes[j].weight += entry.weight;
            continue;
        }
        // Insertion keeps the merged prefix sorted. The entry is copied first: the shift can overwrite slot i.
        for (j = merged; j > 0 && (outcomes[j - 1].species > entry.species
                                   || (outcomes[j - 1].species == entry.species && outcomes[j - 1].level > entry.level)); j--)
            outcomes[j] = outcomes[j - 1];
        outcomes[j] = entry;
        merged++;
    }
    return merged;
}

static void CheckSlotInvariants(u32 region, s32 youngLimit, u32 capProwler, const struct WildEncounterSlotOutcome *raw, u32 count)
{
    u32 total = 0, i;

    EXPECT_GT(count, 0);
    EXPECT_LE(count, WILD_ENCOUNTER_MAX_SLOT_OUTCOMES);
    for (i = 0; i < count; i++)
    {
        u8 evolutionLevel;
        u16 predecessor = GetSpeciesStepDownPredecessor(raw[i].species, &evolutionLevel);

        total += raw[i].weight;
        EXPECT_GE(raw[i].level, 1);
        EXPECT_LE(raw[i].level, MAX_LEVEL);
        // Never below its stage's evolution level.
        if (predecessor != SPECIES_NONE && evolutionLevel != 0)
            EXPECT_GE(raw[i].level, evolutionLevel);
        // Never below a prowler minimum (the cap's line, and the stage met).
        EXPECT_GE(raw[i].level, capProwler);
        EXPECT_GE(raw[i].level, ProwlerMinimum(raw[i].species, region));
        // A young-level slot stays under its next evolution level, apart from a prowler at its minimum.
        if (youngLimit >= 0)
            EXPECT(raw[i].level <= youngLimit || (capProwler != 0 && raw[i].level == capProwler));
    }
    EXPECT_EQ(total, WILD_ENCOUNTER_OUTCOME_DENOMINATOR);
}

static void CheckHeaderBlock(u32 header, u32 block)
{
    u32 crc = CrcStart();
    u32 firstTr = block * WILD_V2_TR_BLOCK_SIZE;
    u32 lastTr = min(firstTr + WILD_V2_TR_BLOCK_SIZE - 1, 160);
    u32 region = gWildEncounterPlaces[header].region;
    u32 time, method, slot, tr;

    for (time = 0; time < TIMES_USED; time++)
    {
        for (method = 0; method < ARRAY_COUNT(sMethodAreas); method++)
        {
            struct WildEncounterProfileContext context =
            {
                .headerId = header,
                .timeOfDay = time == 0 ? TIME_DAY : TIME_NIGHT,
                .area = sMethodAreas[method],
                .fishingRod = method == 3 ? WILD_ENCOUNTER_FISHING_ROD_OLD : WILD_ENCOUNTER_FISHING_ROD_NONE,
            };
            struct WildEncounterProfileView view;

            if (TimeMethodInfo(header, time, method) == NULL)
            {
                EXPECT(!GetWildEncounterProfileView(&context, &view));
                continue;
            }
            EXPECT(GetWildEncounterProfileView(&context, &view));
            for (slot = 0; slot < sMethodSlots[method]; slot++)
            {
                const struct WildPokemon *entry;
                u16 cap;
                s32 youngLimit;
                u32 capProwler;

                EXPECT(GetWildEncounterProfileEntry(&view, slot, &entry));
                cap = entry->species;
                if (cap == SPECIES_NONE)
                    continue;
                youngLimit = YoungLimit(cap);
                capProwler = ProwlerMinimum(cap, region);
                for (tr = firstTr; tr <= lastTr; tr++)
                {
                    struct WildEncounterSlotOutcome outcomes[WILD_ENCOUNTER_MAX_SLOT_OUTCOMES];
                    u32 count = GetWildEncounterSlotOutcomes(&view, slot, tr, outcomes);
                    u32 merged, i;

                    CheckSlotInvariants(region, youngLimit, capProwler, outcomes, count);
                    merged = MergeOutcomes(outcomes, count);
                    crc = CrcByte(crc, tr);
                    crc = CrcByte(crc, time * 4 + method);
                    crc = CrcByte(crc, slot);
                    crc = CrcByte(crc, merged);
                    for (i = 0; i < merged; i++)
                    {
                        crc = CrcByte(crc, outcomes[i].species & 0xFF);
                        crc = CrcByte(crc, outcomes[i].species >> 8);
                        crc = CrcByte(crc, outcomes[i].level);
                        crc = CrcByte(crc, outcomes[i].weight);
                    }
                }
            }
        }
    }
    if (CrcFinish(crc) != sWildV2OutcomeDigests[header][block])
        Test_ExitWithResult(TEST_RESULT_FAIL, __LINE__, ":L%s:%d: header %d (map %d) TR block %d outcome digest differs from the model",
            gTestRunnerState.test->filename, __LINE__, header, sWildV2HeaderMaps[header], block);
}

TEST("Wild encounters v2: every day and night slot's exact outcome distribution at every Trainer Rating matches the model")
{
    u32 block = 0, partition = 0;
    u32 parameterBlock, parameterPartition, header;

    for (parameterBlock = 0; parameterBlock < WILD_V2_TR_BLOCKS; parameterBlock++)
        for (parameterPartition = 0; parameterPartition < PARTITIONS; parameterPartition++)
            PARAMETRIZE_LABEL("TR %d-%d, headers %d mod %d", parameterBlock * WILD_V2_TR_BLOCK_SIZE,
                              min((parameterBlock + 1) * WILD_V2_TR_BLOCK_SIZE - 1, 160), parameterPartition, PARTITIONS)
            {
                block = parameterBlock;
                partition = parameterPartition;
            }

    for (header = partition; header < WILD_V2_HEADER_COUNT; header += PARTITIONS)
        CheckHeaderBlock(header, block);
}

#endif // IS_WAYFARER
