// Generated by tools/trainer_scaling/reach.py; edit reach_places.json or the wild reach data, then regenerate.
// Every map that hosts an ORDINARY Trainer: the place its battles take their level from.
static const struct TrainerMapPlace sTrainerMapPlaces[] =
{
    { // MAP_ROUTE30_HNS: listed, Route 30 (Road)
        MAP_GROUP(MAP_ROUTE30_HNS), MAP_NUM(MAP_ROUTE30_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE31_HNS: listed, Route 31 (Road)
        MAP_GROUP(MAP_ROUTE31_HNS), MAP_NUM(MAP_ROUTE31_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE32_HNS: listed, Route 32 (Road)
        MAP_GROUP(MAP_ROUTE32_HNS), MAP_NUM(MAP_ROUTE32_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE33_HNS: listed, Route 33 (Road)
        MAP_GROUP(MAP_ROUTE33_HNS), MAP_NUM(MAP_ROUTE33_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE34_HNS: listed, Route 34 (Road)
        MAP_GROUP(MAP_ROUTE34_HNS), MAP_NUM(MAP_ROUTE34_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE35_HNS: listed, Route 35 (Road)
        MAP_GROUP(MAP_ROUTE35_HNS), MAP_NUM(MAP_ROUTE35_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE36_HNS: listed, Route 36 (Road)
        MAP_GROUP(MAP_ROUTE36_HNS), MAP_NUM(MAP_ROUTE36_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE37_HNS: listed, Route 37 (Road)
        MAP_GROUP(MAP_ROUTE37_HNS), MAP_NUM(MAP_ROUTE37_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE38_HNS: listed, Route 38 (Road)
        MAP_GROUP(MAP_ROUTE38_HNS), MAP_NUM(MAP_ROUTE38_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE39_HNS: listed, Route 39 (Road)
        MAP_GROUP(MAP_ROUTE39_HNS), MAP_NUM(MAP_ROUTE39_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE40_HNS: listed, Route 40 (Road)
        MAP_GROUP(MAP_ROUTE40_HNS), MAP_NUM(MAP_ROUTE40_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE41_HNS: listed, Route 41 (Road)
        MAP_GROUP(MAP_ROUTE41_HNS), MAP_NUM(MAP_ROUTE41_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE42_HNS: listed, Route 42 (Road)
        MAP_GROUP(MAP_ROUTE42_HNS), MAP_NUM(MAP_ROUTE42_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE43_HNS: listed, Route 43 (Road)
        MAP_GROUP(MAP_ROUTE43_HNS), MAP_NUM(MAP_ROUTE43_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE44_HNS: listed, Route 44 (Road)
        MAP_GROUP(MAP_ROUTE44_HNS), MAP_NUM(MAP_ROUTE44_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE45_HNS: listed, Route 45 (Road)
        MAP_GROUP(MAP_ROUTE45_HNS), MAP_NUM(MAP_ROUTE45_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE46_HNS: listed, Route 46 (Road)
        MAP_GROUP(MAP_ROUTE46_HNS), MAP_NUM(MAP_ROUTE46_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE47_HNS: listed, Route 47 (Wilds)
        MAP_GROUP(MAP_ROUTE47_HNS), MAP_NUM(MAP_ROUTE47_HNS),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE1_HNS: listed, Route 1 (Road)
        MAP_GROUP(MAP_ROUTE1_HNS), MAP_NUM(MAP_ROUTE1_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE3_HNS: listed, Route 3 (Road)
        MAP_GROUP(MAP_ROUTE3_HNS), MAP_NUM(MAP_ROUTE3_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE4_HNS: listed, Route 4 (Road)
        MAP_GROUP(MAP_ROUTE4_HNS), MAP_NUM(MAP_ROUTE4_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE6_HNS: listed, Route 6 (Road)
        MAP_GROUP(MAP_ROUTE6_HNS), MAP_NUM(MAP_ROUTE6_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE8_HNS: listed, Route 8 (Road)
        MAP_GROUP(MAP_ROUTE8_HNS), MAP_NUM(MAP_ROUTE8_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE9_HNS: listed, Route 9 (Wilds)
        MAP_GROUP(MAP_ROUTE9_HNS), MAP_NUM(MAP_ROUTE9_HNS),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE10_HNS: listed, Route 10 (Wilds)
        MAP_GROUP(MAP_ROUTE10_HNS), MAP_NUM(MAP_ROUTE10_HNS),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE11_HNS: listed, Route 11 (Road)
        MAP_GROUP(MAP_ROUTE11_HNS), MAP_NUM(MAP_ROUTE11_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE12_HNS: listed, Route 12 (Road)
        MAP_GROUP(MAP_ROUTE12_HNS), MAP_NUM(MAP_ROUTE12_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE13_HNS: listed, Route 13 (Road)
        MAP_GROUP(MAP_ROUTE13_HNS), MAP_NUM(MAP_ROUTE13_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE14_HNS: listed, Route 14 (Wilds)
        MAP_GROUP(MAP_ROUTE14_HNS), MAP_NUM(MAP_ROUTE14_HNS),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE15_HNS: listed, Route 15 (Wilds)
        MAP_GROUP(MAP_ROUTE15_HNS), MAP_NUM(MAP_ROUTE15_HNS),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE17_HNS: listed, Route 17 (Road)
        MAP_GROUP(MAP_ROUTE17_HNS), MAP_NUM(MAP_ROUTE17_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE18_HNS: listed, Route 18 (Road)
        MAP_GROUP(MAP_ROUTE18_HNS), MAP_NUM(MAP_ROUTE18_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE24_HNS: listed, Route 24 (Road)
        MAP_GROUP(MAP_ROUTE24_HNS), MAP_NUM(MAP_ROUTE24_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE25_HNS: listed, Route 25 (Wilds)
        MAP_GROUP(MAP_ROUTE25_HNS), MAP_NUM(MAP_ROUTE25_HNS),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE26_HNS: listed, Route 26 (Outlands)
        MAP_GROUP(MAP_ROUTE26_HNS), MAP_NUM(MAP_ROUTE26_HNS),
        { .reach = WILD_REACH_OUTLANDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE26NORTH_HNS: join, Outlands by the joining table
        MAP_GROUP(MAP_ROUTE26NORTH_HNS), MAP_NUM(MAP_ROUTE26NORTH_HNS),
        { .reach = WILD_REACH_OUTLANDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE27_HNS: listed, Route 27 (Wilds)
        MAP_GROUP(MAP_ROUTE27_HNS), MAP_NUM(MAP_ROUTE27_HNS),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_GOLDENROD_CITY_UNDERGROUND_TUNNEL_HNS: new-dungeon, Goldenrod Underground step 1 of 4
        MAP_GROUP(MAP_GOLDENROD_CITY_UNDERGROUND_TUNNEL_HNS), MAP_NUM(MAP_GOLDENROD_CITY_UNDERGROUND_TUNNEL_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD_TO_MODERATE, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 4 },
    },
    { // MAP_GOLDENROD_CITY_UNDERGROUND_SWITCHES_HNS: new-dungeon, Goldenrod Underground step 4 of 4
        MAP_GROUP(MAP_GOLDENROD_CITY_UNDERGROUND_SWITCHES_HNS), MAP_NUM(MAP_GOLDENROD_CITY_UNDERGROUND_SWITCHES_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD_TO_MODERATE, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 3, .floorCount = 4 },
    },
    { // MAP_GOLDENROD_CITY_UNDERGROUND_STORAGE_HNS: new-dungeon, Goldenrod Underground step 3 of 4
        MAP_GROUP(MAP_GOLDENROD_CITY_UNDERGROUND_STORAGE_HNS), MAP_NUM(MAP_GOLDENROD_CITY_UNDERGROUND_STORAGE_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD_TO_MODERATE, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 2, .floorCount = 4 },
    },
    { // MAP_GOLDENROD_CITY_RADIO_TOWER_1F_HNS: interior, opens onto GoldenrodCity_hns
        MAP_GROUP(MAP_GOLDENROD_CITY_RADIO_TOWER_1F_HNS), MAP_NUM(MAP_GOLDENROD_CITY_RADIO_TOWER_1F_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_GOLDENROD_CITY_RADIO_TOWER_2F_HNS: new-dungeon, Radio Tower step 1 of 4
        MAP_GROUP(MAP_GOLDENROD_CITY_RADIO_TOWER_2F_HNS), MAP_NUM(MAP_GOLDENROD_CITY_RADIO_TOWER_2F_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 4 },
    },
    { // MAP_GOLDENROD_CITY_RADIO_TOWER_3F_HNS: new-dungeon, Radio Tower step 2 of 4
        MAP_GROUP(MAP_GOLDENROD_CITY_RADIO_TOWER_3F_HNS), MAP_NUM(MAP_GOLDENROD_CITY_RADIO_TOWER_3F_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 1, .floorCount = 4 },
    },
    { // MAP_GOLDENROD_CITY_RADIO_TOWER_4F_HNS: new-dungeon, Radio Tower step 3 of 4
        MAP_GROUP(MAP_GOLDENROD_CITY_RADIO_TOWER_4F_HNS), MAP_NUM(MAP_GOLDENROD_CITY_RADIO_TOWER_4F_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 2, .floorCount = 4 },
    },
    { // MAP_ECRUTEAK_CITY_THEATER_HNS: interior, opens onto EcruteakCity_hns
        MAP_GROUP(MAP_ECRUTEAK_CITY_THEATER_HNS), MAP_NUM(MAP_ECRUTEAK_CITY_THEATER_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_OLIVINE_CITY_LIGHTHOUSE_HNS: new-dungeon, Olivine Lighthouse step 1 of 1
        MAP_GROUP(MAP_OLIVINE_CITY_LIGHTHOUSE_HNS), MAP_NUM(MAP_OLIVINE_CITY_LIGHTHOUSE_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 1, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 1 },
    },
    { // MAP_CELADON_CITY_GAME_CORNER_HNS: interior, opens onto CeladonCity_hns
        MAP_GROUP(MAP_CELADON_CITY_GAME_CORNER_HNS), MAP_NUM(MAP_CELADON_CITY_GAME_CORNER_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_SPROUT_TOWER_1F_HNS: join, Sprout Tower step 1 of 3
        MAP_GROUP(MAP_SPROUT_TOWER_1F_HNS), MAP_NUM(MAP_SPROUT_TOWER_1F_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 3 },
    },
    { // MAP_SPROUT_TOWER_2F_HNS: join (listed map re-stepped), Sprout Tower step 2 of 3
        MAP_GROUP(MAP_SPROUT_TOWER_2F_HNS), MAP_NUM(MAP_SPROUT_TOWER_2F_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 1, .floorCount = 3 },
    },
    { // MAP_SPROUT_TOWER_3F_HNS: join (listed map re-stepped), Sprout Tower step 3 of 3
        MAP_GROUP(MAP_SPROUT_TOWER_3F_HNS), MAP_NUM(MAP_SPROUT_TOWER_3F_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 2, .floorCount = 3 },
    },
    { // MAP_RUINS_OF_ALPH_OUTSIDE_HNS: listed, Ruins of Alph (Wilds)
        MAP_GROUP(MAP_RUINS_OF_ALPH_OUTSIDE_HNS), MAP_NUM(MAP_RUINS_OF_ALPH_OUTSIDE_HNS),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_UNION_CAVE_1F_HNS: listed, Union Cave (Dungeon)
        MAP_GROUP(MAP_UNION_CAVE_1F_HNS), MAP_NUM(MAP_UNION_CAVE_1F_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 3 },
    },
    { // MAP_UNION_CAVE_B1F_HNS: listed, Union Cave (Dungeon)
        MAP_GROUP(MAP_UNION_CAVE_B1F_HNS), MAP_NUM(MAP_UNION_CAVE_B1F_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 1, .floorCount = 3 },
    },
    { // MAP_UNION_CAVE_B2F_HNS: listed, Union Cave (Dungeon)
        MAP_GROUP(MAP_UNION_CAVE_B2F_HNS), MAP_NUM(MAP_UNION_CAVE_B2F_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 2, .floorCount = 3 },
    },
    { // MAP_SLOWPOKE_WELL_B1F_HNS: listed, Slowpoke Well (Dungeon)
        MAP_GROUP(MAP_SLOWPOKE_WELL_B1F_HNS), MAP_NUM(MAP_SLOWPOKE_WELL_B1F_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 2 },
    },
    { // MAP_ILEX_FOREST_HNS: listed, Ilex Forest (Road)
        MAP_GROUP(MAP_ILEX_FOREST_HNS), MAP_NUM(MAP_ILEX_FOREST_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_NATIONAL_PARK_NORMAL_HNS: listed, National Park (Wilds)
        MAP_GROUP(MAP_NATIONAL_PARK_NORMAL_HNS), MAP_NUM(MAP_NATIONAL_PARK_NORMAL_HNS),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_BURNED_TOWER_1F_HNS: listed, Burned Tower (Dungeon)
        MAP_GROUP(MAP_BURNED_TOWER_1F_HNS), MAP_NUM(MAP_BURNED_TOWER_1F_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 2 },
    },
    { // MAP_MT_MORTAR_1F_NORTH_HNS: listed, Mt. Mortar (Dungeon)
        MAP_GROUP(MAP_MT_MORTAR_1F_NORTH_HNS), MAP_NUM(MAP_MT_MORTAR_1F_NORTH_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 1, .floorCount = 4 },
    },
    { // MAP_MT_MORTAR_2F_HNS: listed, Mt. Mortar (Dungeon)
        MAP_GROUP(MAP_MT_MORTAR_2F_HNS), MAP_NUM(MAP_MT_MORTAR_2F_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 2, .floorCount = 4 },
    },
    { // MAP_MT_MORTAR_B1F_HNS: listed, Mt. Mortar (Dungeon)
        MAP_GROUP(MAP_MT_MORTAR_B1F_HNS), MAP_NUM(MAP_MT_MORTAR_B1F_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 3, .floorCount = 4 },
    },
    { // MAP_LAKE_OF_RAGE_HNS: listed, Lake of Rage (Wilds)
        MAP_GROUP(MAP_LAKE_OF_RAGE_HNS), MAP_NUM(MAP_LAKE_OF_RAGE_HNS),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_DRAGONS_DEN_CAVERN_HNS: listed, Dragon's Den (Dungeon)
        MAP_GROUP(MAP_DRAGONS_DEN_CAVERN_HNS), MAP_NUM(MAP_DRAGONS_DEN_CAVERN_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_HARD, .flat = 1, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 1 },
    },
    { // MAP_VIRIDIAN_FOREST_HNS: listed, Viridian Forest (Road)
        MAP_GROUP(MAP_VIRIDIAN_FOREST_HNS), MAP_NUM(MAP_VIRIDIAN_FOREST_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_MT_MOON_CAVE_HNS: listed, Mt. Moon (Wilds)
        MAP_GROUP(MAP_MT_MOON_CAVE_HNS), MAP_NUM(MAP_MT_MOON_CAVE_HNS),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROCKET_HIDEOUT_B1F_HNS: join (listed map re-stepped), Rocket Hideout (Johto) step 1 of 3
        MAP_GROUP(MAP_ROCKET_HIDEOUT_B1F_HNS), MAP_NUM(MAP_ROCKET_HIDEOUT_B1F_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD_TO_MODERATE, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 3 },
    },
    { // MAP_ROCKET_HIDEOUT_B2F_HNS: join, Rocket Hideout (Johto) step 2 of 3
        MAP_GROUP(MAP_ROCKET_HIDEOUT_B2F_HNS), MAP_NUM(MAP_ROCKET_HIDEOUT_B2F_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD_TO_MODERATE, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 1, .floorCount = 3 },
    },
    { // MAP_ROCKET_HIDEOUT_B3F_HNS: join, Rocket Hideout (Johto) step 3 of 3
        MAP_GROUP(MAP_ROCKET_HIDEOUT_B3F_HNS), MAP_NUM(MAP_ROCKET_HIDEOUT_B3F_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD_TO_MODERATE, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 2, .floorCount = 3 },
    },
    { // MAP_PONI_ISLE_HNS: listed, Poni Isle (Outlands)
        MAP_GROUP(MAP_PONI_ISLE_HNS), MAP_NUM(MAP_PONI_ISLE_HNS),
        { .reach = WILD_REACH_OUTLANDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_AKALA_ISLE_HNS: listed, Akala Isle (Wilds)
        MAP_GROUP(MAP_AKALA_ISLE_HNS), MAP_NUM(MAP_AKALA_ISLE_HNS),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_MELEMELE_ISLE_HNS: listed, Melemele Isle (Road)
        MAP_GROUP(MAP_MELEMELE_ISLE_HNS), MAP_NUM(MAP_MELEMELE_ISLE_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ALOLA_WATER_HNS: listed, Alola sea (Wilds)
        MAP_GROUP(MAP_ALOLA_WATER_HNS), MAP_NUM(MAP_ALOLA_WATER_HNS),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ULAULA_ISLE_HNS: listed, Ula'ula Isle (Outlands)
        MAP_GROUP(MAP_ULAULA_ISLE_HNS), MAP_NUM(MAP_ULAULA_ISLE_HNS),
        { .reach = WILD_REACH_OUTLANDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_AKALA_FOREST_HNS: listed, Akala Forest (Wilds)
        MAP_GROUP(MAP_AKALA_FOREST_HNS), MAP_NUM(MAP_AKALA_FOREST_HNS),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_AKALA_CAVE_HNS: listed, Akala Cave (Dungeon)
        MAP_GROUP(MAP_AKALA_CAVE_HNS), MAP_NUM(MAP_AKALA_CAVE_HNS),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE, .flat = 1, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 1 },
    },
    { // MAP_SSAQUA_1F_HNS: ferry, ferries are Road
        MAP_GROUP(MAP_SSAQUA_1F_HNS), MAP_NUM(MAP_SSAQUA_1F_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_SSAQUA_B1F_HNS: ferry, ferries are Road
        MAP_GROUP(MAP_SSAQUA_B1F_HNS), MAP_NUM(MAP_SSAQUA_B1F_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_SSAQUA_ROOM_NW_HNS: ferry, ferries are Road
        MAP_GROUP(MAP_SSAQUA_ROOM_NW_HNS), MAP_NUM(MAP_SSAQUA_ROOM_NW_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_SSAQUA_ROOM_NE_HNS: ferry, ferries are Road
        MAP_GROUP(MAP_SSAQUA_ROOM_NE_HNS), MAP_NUM(MAP_SSAQUA_ROOM_NE_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_SSAQUA_ROOM_NNE_HNS: ferry, ferries are Road
        MAP_GROUP(MAP_SSAQUA_ROOM_NNE_HNS), MAP_NUM(MAP_SSAQUA_ROOM_NNE_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_SSAQUA_ROOM_SSW_HNS: ferry, ferries are Road
        MAP_GROUP(MAP_SSAQUA_ROOM_SSW_HNS), MAP_NUM(MAP_SSAQUA_ROOM_SSW_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_SSAQUA_ROOM_SE_HNS: ferry, ferries are Road
        MAP_GROUP(MAP_SSAQUA_ROOM_SE_HNS), MAP_NUM(MAP_SSAQUA_ROOM_SE_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_SSAQUA_ROOM_SW_HNS: ferry, ferries are Road
        MAP_GROUP(MAP_SSAQUA_ROOM_SW_HNS), MAP_NUM(MAP_SSAQUA_ROOM_SW_HNS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE102: listed, Route 102 (Road)
        MAP_GROUP(MAP_ROUTE102), MAP_NUM(MAP_ROUTE102),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE103: listed, Route 103 (Road)
        MAP_GROUP(MAP_ROUTE103), MAP_NUM(MAP_ROUTE103),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE104: listed, Route 104 (Road)
        MAP_GROUP(MAP_ROUTE104), MAP_NUM(MAP_ROUTE104),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE105: listed, Route 105 (Road)
        MAP_GROUP(MAP_ROUTE105), MAP_NUM(MAP_ROUTE105),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE106: listed, Route 106 (Road)
        MAP_GROUP(MAP_ROUTE106), MAP_NUM(MAP_ROUTE106),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE107: listed, Route 107 (Wilds)
        MAP_GROUP(MAP_ROUTE107), MAP_NUM(MAP_ROUTE107),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE108: listed, Route 108 (Wilds)
        MAP_GROUP(MAP_ROUTE108), MAP_NUM(MAP_ROUTE108),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE109: listed, Route 109 (Road)
        MAP_GROUP(MAP_ROUTE109), MAP_NUM(MAP_ROUTE109),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE110: listed, Route 110 (Road)
        MAP_GROUP(MAP_ROUTE110), MAP_NUM(MAP_ROUTE110),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE111: listed, Route 111 (Road)
        MAP_GROUP(MAP_ROUTE111), MAP_NUM(MAP_ROUTE111),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE112: listed, Route 112 (Road)
        MAP_GROUP(MAP_ROUTE112), MAP_NUM(MAP_ROUTE112),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE113: listed, Route 113 (Road)
        MAP_GROUP(MAP_ROUTE113), MAP_NUM(MAP_ROUTE113),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE114: listed, Route 114 (Wilds)
        MAP_GROUP(MAP_ROUTE114), MAP_NUM(MAP_ROUTE114),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE115: listed, Route 115 (Road)
        MAP_GROUP(MAP_ROUTE115), MAP_NUM(MAP_ROUTE115),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE116: listed, Route 116 (Road)
        MAP_GROUP(MAP_ROUTE116), MAP_NUM(MAP_ROUTE116),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE117: listed, Route 117 (Road)
        MAP_GROUP(MAP_ROUTE117), MAP_NUM(MAP_ROUTE117),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE118: listed, Route 118 (Road)
        MAP_GROUP(MAP_ROUTE118), MAP_NUM(MAP_ROUTE118),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE119: listed, Route 119 (Road)
        MAP_GROUP(MAP_ROUTE119), MAP_NUM(MAP_ROUTE119),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE120: listed, Route 120 (Wilds)
        MAP_GROUP(MAP_ROUTE120), MAP_NUM(MAP_ROUTE120),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE121: listed, Route 121 (Road)
        MAP_GROUP(MAP_ROUTE121), MAP_NUM(MAP_ROUTE121),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE123: listed, Route 123 (Road)
        MAP_GROUP(MAP_ROUTE123), MAP_NUM(MAP_ROUTE123),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE124: listed, Route 124 (Road)
        MAP_GROUP(MAP_ROUTE124), MAP_NUM(MAP_ROUTE124),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE125: listed, Route 125 (Wilds)
        MAP_GROUP(MAP_ROUTE125), MAP_NUM(MAP_ROUTE125),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE126: listed, Route 126 (Outlands)
        MAP_GROUP(MAP_ROUTE126), MAP_NUM(MAP_ROUTE126),
        { .reach = WILD_REACH_OUTLANDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE127: listed, Route 127 (Road)
        MAP_GROUP(MAP_ROUTE127), MAP_NUM(MAP_ROUTE127),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE128: listed, Route 128 (Road)
        MAP_GROUP(MAP_ROUTE128), MAP_NUM(MAP_ROUTE128),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE129: listed, Route 129 (Outlands)
        MAP_GROUP(MAP_ROUTE129), MAP_NUM(MAP_ROUTE129),
        { .reach = WILD_REACH_OUTLANDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE130: listed, Route 130 (Outlands)
        MAP_GROUP(MAP_ROUTE130), MAP_NUM(MAP_ROUTE130),
        { .reach = WILD_REACH_OUTLANDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE131: listed, Route 131 (Outlands)
        MAP_GROUP(MAP_ROUTE131), MAP_NUM(MAP_ROUTE131),
        { .reach = WILD_REACH_OUTLANDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE132: listed, Route 132 (Wilds)
        MAP_GROUP(MAP_ROUTE132), MAP_NUM(MAP_ROUTE132),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE133: listed, Route 133 (Outlands)
        MAP_GROUP(MAP_ROUTE133), MAP_NUM(MAP_ROUTE133),
        { .reach = WILD_REACH_OUTLANDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE134: listed, Route 134 (Wilds)
        MAP_GROUP(MAP_ROUTE134), MAP_NUM(MAP_ROUTE134),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F: interior, opens onto SlateportCity
        MAP_GROUP(MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F), MAP_NUM(MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_MOSSDEEP_CITY_SPACE_CENTER_1F: new-dungeon, Space Center step 1 of 2
        MAP_GROUP(MAP_MOSSDEEP_CITY_SPACE_CENTER_1F), MAP_NUM(MAP_MOSSDEEP_CITY_SPACE_CENTER_1F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 2 },
    },
    { // MAP_MOSSDEEP_CITY_SPACE_CENTER_2F: new-dungeon, Space Center step 2 of 2
        MAP_GROUP(MAP_MOSSDEEP_CITY_SPACE_CENTER_2F), MAP_NUM(MAP_MOSSDEEP_CITY_SPACE_CENTER_2F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 1, .floorCount = 2 },
    },
    { // MAP_METEOR_FALLS_1F_2R: listed, Meteor Falls (Dungeon)
        MAP_GROUP(MAP_METEOR_FALLS_1F_2R), MAP_NUM(MAP_METEOR_FALLS_1F_2R),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 1, .floorCount = 5 },
    },
    { // MAP_RUSTURF_TUNNEL: listed, Rusturf Tunnel (Wilds)
        MAP_GROUP(MAP_RUSTURF_TUNNEL), MAP_NUM(MAP_RUSTURF_TUNNEL),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_PETALBURG_WOODS: listed, Petalburg Woods (Road)
        MAP_GROUP(MAP_PETALBURG_WOODS), MAP_NUM(MAP_PETALBURG_WOODS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_MT_CHIMNEY: join, Wilds by the joining table
        MAP_GROUP(MAP_MT_CHIMNEY), MAP_NUM(MAP_MT_CHIMNEY),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_JAGGED_PASS: listed, Jagged Pass (Wilds)
        MAP_GROUP(MAP_JAGGED_PASS), MAP_NUM(MAP_JAGGED_PASS),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_MT_PYRE_2F: listed, Mt. Pyre (Dungeon)
        MAP_GROUP(MAP_MT_PYRE_2F), MAP_NUM(MAP_MT_PYRE_2F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 1, .floorCount = 8 },
    },
    { // MAP_MT_PYRE_3F: listed, Mt. Pyre (Dungeon)
        MAP_GROUP(MAP_MT_PYRE_3F), MAP_NUM(MAP_MT_PYRE_3F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 2, .floorCount = 8 },
    },
    { // MAP_MT_PYRE_4F: listed, Mt. Pyre (Dungeon)
        MAP_GROUP(MAP_MT_PYRE_4F), MAP_NUM(MAP_MT_PYRE_4F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 3, .floorCount = 8 },
    },
    { // MAP_MT_PYRE_5F: listed, Mt. Pyre (Dungeon)
        MAP_GROUP(MAP_MT_PYRE_5F), MAP_NUM(MAP_MT_PYRE_5F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 4, .floorCount = 8 },
    },
    { // MAP_MT_PYRE_6F: listed, Mt. Pyre (Dungeon)
        MAP_GROUP(MAP_MT_PYRE_6F), MAP_NUM(MAP_MT_PYRE_6F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 5, .floorCount = 8 },
    },
    { // MAP_MT_PYRE_SUMMIT: listed, Mt. Pyre (Dungeon)
        MAP_GROUP(MAP_MT_PYRE_SUMMIT), MAP_NUM(MAP_MT_PYRE_SUMMIT),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 7, .floorCount = 8 },
    },
    { // MAP_AQUA_HIDEOUT_1F: new-dungeon, Aqua Hideout step 1 of 3
        MAP_GROUP(MAP_AQUA_HIDEOUT_1F), MAP_NUM(MAP_AQUA_HIDEOUT_1F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 3 },
    },
    { // MAP_AQUA_HIDEOUT_B1F: new-dungeon, Aqua Hideout step 2 of 3
        MAP_GROUP(MAP_AQUA_HIDEOUT_B1F), MAP_NUM(MAP_AQUA_HIDEOUT_B1F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 1, .floorCount = 3 },
    },
    { // MAP_AQUA_HIDEOUT_B2F: new-dungeon, Aqua Hideout step 3 of 3
        MAP_GROUP(MAP_AQUA_HIDEOUT_B2F), MAP_NUM(MAP_AQUA_HIDEOUT_B2F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 2, .floorCount = 3 },
    },
    { // MAP_SEAFLOOR_CAVERN_ROOM1: join (listed map re-stepped), Seafloor Cavern step 2 of 10
        MAP_GROUP(MAP_SEAFLOOR_CAVERN_ROOM1), MAP_NUM(MAP_SEAFLOOR_CAVERN_ROOM1),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 1, .floorCount = 10 },
    },
    { // MAP_SEAFLOOR_CAVERN_ROOM3: join (listed map re-stepped), Seafloor Cavern step 4 of 10
        MAP_GROUP(MAP_SEAFLOOR_CAVERN_ROOM3), MAP_NUM(MAP_SEAFLOOR_CAVERN_ROOM3),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 3, .floorCount = 10 },
    },
    { // MAP_SEAFLOOR_CAVERN_ROOM4: join (listed map re-stepped), Seafloor Cavern step 5 of 10
        MAP_GROUP(MAP_SEAFLOOR_CAVERN_ROOM4), MAP_NUM(MAP_SEAFLOOR_CAVERN_ROOM4),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 4, .floorCount = 10 },
    },
    { // MAP_VICTORY_ROAD_1F: listed, Victory Road (Dungeon)
        MAP_GROUP(MAP_VICTORY_ROAD_1F), MAP_NUM(MAP_VICTORY_ROAD_1F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 3 },
    },
    { // MAP_VICTORY_ROAD_B1F: listed, Victory Road (Dungeon)
        MAP_GROUP(MAP_VICTORY_ROAD_B1F), MAP_NUM(MAP_VICTORY_ROAD_B1F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 1, .floorCount = 3 },
    },
    { // MAP_VICTORY_ROAD_B2F: listed, Victory Road (Dungeon)
        MAP_GROUP(MAP_VICTORY_ROAD_B2F), MAP_NUM(MAP_VICTORY_ROAD_B2F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 2, .floorCount = 3 },
    },
    { // MAP_ABANDONED_SHIP_CORRIDORS_1F: join, Abandoned Ship step 1 of 3
        MAP_GROUP(MAP_ABANDONED_SHIP_CORRIDORS_1F), MAP_NUM(MAP_ABANDONED_SHIP_CORRIDORS_1F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD_TO_MODERATE, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 3 },
    },
    { // MAP_ABANDONED_SHIP_ROOMS_1F: join, Abandoned Ship step 1 of 3
        MAP_GROUP(MAP_ABANDONED_SHIP_ROOMS_1F), MAP_NUM(MAP_ABANDONED_SHIP_ROOMS_1F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD_TO_MODERATE, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 3 },
    },
    { // MAP_ABANDONED_SHIP_CORRIDORS_B1F: join, Abandoned Ship step 2 of 3
        MAP_GROUP(MAP_ABANDONED_SHIP_CORRIDORS_B1F), MAP_NUM(MAP_ABANDONED_SHIP_CORRIDORS_B1F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD_TO_MODERATE, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 1, .floorCount = 3 },
    },
    { // MAP_ABANDONED_SHIP_ROOMS2_1F: join, Abandoned Ship step 1 of 3
        MAP_GROUP(MAP_ABANDONED_SHIP_ROOMS2_1F), MAP_NUM(MAP_ABANDONED_SHIP_ROOMS2_1F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD_TO_MODERATE, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 3 },
    },
    { // MAP_MAGMA_HIDEOUT_1F: listed, Magma Hideout (Dungeon)
        MAP_GROUP(MAP_MAGMA_HIDEOUT_1F), MAP_NUM(MAP_MAGMA_HIDEOUT_1F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 8 },
    },
    { // MAP_MAGMA_HIDEOUT_2F_1R: listed, Magma Hideout (Dungeon)
        MAP_GROUP(MAP_MAGMA_HIDEOUT_2F_1R), MAP_NUM(MAP_MAGMA_HIDEOUT_2F_1R),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 1, .floorCount = 8 },
    },
    { // MAP_MAGMA_HIDEOUT_2F_2R: listed, Magma Hideout (Dungeon)
        MAP_GROUP(MAP_MAGMA_HIDEOUT_2F_2R), MAP_NUM(MAP_MAGMA_HIDEOUT_2F_2R),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 2, .floorCount = 8 },
    },
    { // MAP_MAGMA_HIDEOUT_3F_1R: listed, Magma Hideout (Dungeon)
        MAP_GROUP(MAP_MAGMA_HIDEOUT_3F_1R), MAP_NUM(MAP_MAGMA_HIDEOUT_3F_1R),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 4, .floorCount = 8 },
    },
    { // MAP_MAGMA_HIDEOUT_3F_2R: listed, Magma Hideout (Dungeon)
        MAP_GROUP(MAP_MAGMA_HIDEOUT_3F_2R), MAP_NUM(MAP_MAGMA_HIDEOUT_3F_2R),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 5, .floorCount = 8 },
    },
    { // MAP_MAGMA_HIDEOUT_4F: listed, Magma Hideout (Dungeon)
        MAP_GROUP(MAP_MAGMA_HIDEOUT_4F), MAP_NUM(MAP_MAGMA_HIDEOUT_4F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 7, .floorCount = 8 },
    },
    { // MAP_SS_TIDAL_LOWER_DECK: ferry, ferries are Road
        MAP_GROUP(MAP_SS_TIDAL_LOWER_DECK), MAP_NUM(MAP_SS_TIDAL_LOWER_DECK),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_SS_TIDAL_ROOMS: ferry, ferries are Road
        MAP_GROUP(MAP_SS_TIDAL_ROOMS), MAP_NUM(MAP_SS_TIDAL_ROOMS),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE109_SEASHORE_HOUSE: interior, opens onto Route109
        MAP_GROUP(MAP_ROUTE109_SEASHORE_HOUSE), MAP_NUM(MAP_ROUTE109_SEASHORE_HOUSE),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE110_TRICK_HOUSE_PUZZLE1: interior, opens onto Route110
        MAP_GROUP(MAP_ROUTE110_TRICK_HOUSE_PUZZLE1), MAP_NUM(MAP_ROUTE110_TRICK_HOUSE_PUZZLE1),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE110_TRICK_HOUSE_PUZZLE2: interior, opens onto Route110
        MAP_GROUP(MAP_ROUTE110_TRICK_HOUSE_PUZZLE2), MAP_NUM(MAP_ROUTE110_TRICK_HOUSE_PUZZLE2),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE110_TRICK_HOUSE_PUZZLE3: interior, opens onto Route110
        MAP_GROUP(MAP_ROUTE110_TRICK_HOUSE_PUZZLE3), MAP_NUM(MAP_ROUTE110_TRICK_HOUSE_PUZZLE3),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE110_TRICK_HOUSE_PUZZLE4: interior, opens onto Route110
        MAP_GROUP(MAP_ROUTE110_TRICK_HOUSE_PUZZLE4), MAP_NUM(MAP_ROUTE110_TRICK_HOUSE_PUZZLE4),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE110_TRICK_HOUSE_PUZZLE6: interior, opens onto Route110
        MAP_GROUP(MAP_ROUTE110_TRICK_HOUSE_PUZZLE6), MAP_NUM(MAP_ROUTE110_TRICK_HOUSE_PUZZLE6),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE110_TRICK_HOUSE_PUZZLE7: interior, opens onto Route110
        MAP_GROUP(MAP_ROUTE110_TRICK_HOUSE_PUZZLE7), MAP_NUM(MAP_ROUTE110_TRICK_HOUSE_PUZZLE7),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE110_TRICK_HOUSE_PUZZLE8: interior, opens onto Route110
        MAP_GROUP(MAP_ROUTE110_TRICK_HOUSE_PUZZLE8), MAP_NUM(MAP_ROUTE110_TRICK_HOUSE_PUZZLE8),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE119_WEATHER_INSTITUTE_1F: new-dungeon, Weather Institute step 1 of 2
        MAP_GROUP(MAP_ROUTE119_WEATHER_INSTITUTE_1F), MAP_NUM(MAP_ROUTE119_WEATHER_INSTITUTE_1F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 2 },
    },
    { // MAP_ROUTE119_WEATHER_INSTITUTE_2F: new-dungeon, Weather Institute step 2 of 2
        MAP_GROUP(MAP_ROUTE119_WEATHER_INSTITUTE_2F), MAP_NUM(MAP_ROUTE119_WEATHER_INSTITUTE_2F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 1, .floorCount = 2 },
    },
    { // MAP_SSANNE_DECK: new-dungeon, S.S. Anne step 1 of 3
        MAP_GROUP(MAP_SSANNE_DECK), MAP_NUM(MAP_SSANNE_DECK),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 3 },
    },
    { // MAP_SSANNE_1F_ROOM2: new-dungeon, S.S. Anne step 1 of 3
        MAP_GROUP(MAP_SSANNE_1F_ROOM2), MAP_NUM(MAP_SSANNE_1F_ROOM2),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 3 },
    },
    { // MAP_SSANNE_1F_ROOM5: new-dungeon, S.S. Anne step 1 of 3
        MAP_GROUP(MAP_SSANNE_1F_ROOM5), MAP_NUM(MAP_SSANNE_1F_ROOM5),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 3 },
    },
    { // MAP_SSANNE_1F_ROOM7: new-dungeon, S.S. Anne step 1 of 3
        MAP_GROUP(MAP_SSANNE_1F_ROOM7), MAP_NUM(MAP_SSANNE_1F_ROOM7),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 3 },
    },
    { // MAP_SSANNE_2F_ROOM2: new-dungeon, S.S. Anne step 2 of 3
        MAP_GROUP(MAP_SSANNE_2F_ROOM2), MAP_NUM(MAP_SSANNE_2F_ROOM2),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 1, .floorCount = 3 },
    },
    { // MAP_SSANNE_2F_ROOM4: new-dungeon, S.S. Anne step 2 of 3
        MAP_GROUP(MAP_SSANNE_2F_ROOM4), MAP_NUM(MAP_SSANNE_2F_ROOM4),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 1, .floorCount = 3 },
    },
    { // MAP_SSANNE_B1F_ROOM1: new-dungeon, S.S. Anne step 3 of 3
        MAP_GROUP(MAP_SSANNE_B1F_ROOM1), MAP_NUM(MAP_SSANNE_B1F_ROOM1),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 2, .floorCount = 3 },
    },
    { // MAP_SSANNE_B1F_ROOM2: new-dungeon, S.S. Anne step 3 of 3
        MAP_GROUP(MAP_SSANNE_B1F_ROOM2), MAP_NUM(MAP_SSANNE_B1F_ROOM2),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 2, .floorCount = 3 },
    },
    { // MAP_SSANNE_B1F_ROOM3: new-dungeon, S.S. Anne step 3 of 3
        MAP_GROUP(MAP_SSANNE_B1F_ROOM3), MAP_NUM(MAP_SSANNE_B1F_ROOM3),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 2, .floorCount = 3 },
    },
    { // MAP_SSANNE_B1F_ROOM4: new-dungeon, S.S. Anne step 3 of 3
        MAP_GROUP(MAP_SSANNE_B1F_ROOM4), MAP_NUM(MAP_SSANNE_B1F_ROOM4),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 2, .floorCount = 3 },
    },
    { // MAP_ROCKET_HIDEOUT_B1F: new-dungeon, Rocket Hideout (Celadon) step 1 of 4
        MAP_GROUP(MAP_ROCKET_HIDEOUT_B1F), MAP_NUM(MAP_ROCKET_HIDEOUT_B1F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 4 },
    },
    { // MAP_ROCKET_HIDEOUT_B2F: new-dungeon, Rocket Hideout (Celadon) step 2 of 4
        MAP_GROUP(MAP_ROCKET_HIDEOUT_B2F), MAP_NUM(MAP_ROCKET_HIDEOUT_B2F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 1, .floorCount = 4 },
    },
    { // MAP_ROCKET_HIDEOUT_B3F: new-dungeon, Rocket Hideout (Celadon) step 3 of 4
        MAP_GROUP(MAP_ROCKET_HIDEOUT_B3F), MAP_NUM(MAP_ROCKET_HIDEOUT_B3F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 2, .floorCount = 4 },
    },
    { // MAP_ROCKET_HIDEOUT_B4F: new-dungeon, Rocket Hideout (Celadon) step 4 of 4
        MAP_GROUP(MAP_ROCKET_HIDEOUT_B4F), MAP_NUM(MAP_ROCKET_HIDEOUT_B4F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 3, .floorCount = 4 },
    },
    { // MAP_SILPH_CO_2F: new-dungeon, Silph Co. step 1 of 10
        MAP_GROUP(MAP_SILPH_CO_2F), MAP_NUM(MAP_SILPH_CO_2F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 10 },
    },
    { // MAP_SILPH_CO_3F: new-dungeon, Silph Co. step 2 of 10
        MAP_GROUP(MAP_SILPH_CO_3F), MAP_NUM(MAP_SILPH_CO_3F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 1, .floorCount = 10 },
    },
    { // MAP_SILPH_CO_4F: new-dungeon, Silph Co. step 3 of 10
        MAP_GROUP(MAP_SILPH_CO_4F), MAP_NUM(MAP_SILPH_CO_4F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 2, .floorCount = 10 },
    },
    { // MAP_SILPH_CO_5F: new-dungeon, Silph Co. step 4 of 10
        MAP_GROUP(MAP_SILPH_CO_5F), MAP_NUM(MAP_SILPH_CO_5F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 3, .floorCount = 10 },
    },
    { // MAP_SILPH_CO_6F: new-dungeon, Silph Co. step 5 of 10
        MAP_GROUP(MAP_SILPH_CO_6F), MAP_NUM(MAP_SILPH_CO_6F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 4, .floorCount = 10 },
    },
    { // MAP_SILPH_CO_7F: new-dungeon, Silph Co. step 6 of 10
        MAP_GROUP(MAP_SILPH_CO_7F), MAP_NUM(MAP_SILPH_CO_7F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 5, .floorCount = 10 },
    },
    { // MAP_SILPH_CO_8F: new-dungeon, Silph Co. step 7 of 10
        MAP_GROUP(MAP_SILPH_CO_8F), MAP_NUM(MAP_SILPH_CO_8F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 6, .floorCount = 10 },
    },
    { // MAP_SILPH_CO_9F: new-dungeon, Silph Co. step 8 of 10
        MAP_GROUP(MAP_SILPH_CO_9F), MAP_NUM(MAP_SILPH_CO_9F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 7, .floorCount = 10 },
    },
    { // MAP_SILPH_CO_10F: new-dungeon, Silph Co. step 9 of 10
        MAP_GROUP(MAP_SILPH_CO_10F), MAP_NUM(MAP_SILPH_CO_10F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 8, .floorCount = 10 },
    },
    { // MAP_SILPH_CO_11F: new-dungeon, Silph Co. step 10 of 10
        MAP_GROUP(MAP_SILPH_CO_11F), MAP_NUM(MAP_SILPH_CO_11F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 9, .floorCount = 10 },
    },
    { // MAP_POKEMON_MANSION_1F: listed, Pokémon Mansion (Dungeon)
        MAP_GROUP(MAP_POKEMON_MANSION_1F), MAP_NUM(MAP_POKEMON_MANSION_1F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD_TO_MODERATE, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 4 },
    },
    { // MAP_POKEMON_MANSION_2F: listed, Pokémon Mansion (Dungeon)
        MAP_GROUP(MAP_POKEMON_MANSION_2F), MAP_NUM(MAP_POKEMON_MANSION_2F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD_TO_MODERATE, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 1, .floorCount = 4 },
    },
    { // MAP_POKEMON_MANSION_3F: listed, Pokémon Mansion (Dungeon)
        MAP_GROUP(MAP_POKEMON_MANSION_3F), MAP_NUM(MAP_POKEMON_MANSION_3F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD_TO_MODERATE, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 2, .floorCount = 4 },
    },
    { // MAP_POKEMON_MANSION_B1F: listed, Pokémon Mansion (Dungeon)
        MAP_GROUP(MAP_POKEMON_MANSION_B1F), MAP_NUM(MAP_POKEMON_MANSION_B1F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD_TO_MODERATE, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 3, .floorCount = 4 },
    },
    { // MAP_POKEMON_TOWER_3F: listed, Pokémon Tower (Dungeon)
        MAP_GROUP(MAP_POKEMON_TOWER_3F), MAP_NUM(MAP_POKEMON_TOWER_3F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 5 },
    },
    { // MAP_POKEMON_TOWER_4F: listed, Pokémon Tower (Dungeon)
        MAP_GROUP(MAP_POKEMON_TOWER_4F), MAP_NUM(MAP_POKEMON_TOWER_4F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 1, .floorCount = 5 },
    },
    { // MAP_POKEMON_TOWER_5F: listed, Pokémon Tower (Dungeon)
        MAP_GROUP(MAP_POKEMON_TOWER_5F), MAP_NUM(MAP_POKEMON_TOWER_5F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 2, .floorCount = 5 },
    },
    { // MAP_POKEMON_TOWER_6F: listed, Pokémon Tower (Dungeon)
        MAP_GROUP(MAP_POKEMON_TOWER_6F), MAP_NUM(MAP_POKEMON_TOWER_6F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 3, .floorCount = 5 },
    },
    { // MAP_POKEMON_TOWER_7F: listed, Pokémon Tower (Dungeon)
        MAP_GROUP(MAP_POKEMON_TOWER_7F), MAP_NUM(MAP_POKEMON_TOWER_7F),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 4, .floorCount = 5 },
    },
    { // MAP_MT_EMBER_EXTERIOR: listed, Mt. Ember (Dungeon)
        MAP_GROUP(MAP_MT_EMBER_EXTERIOR), MAP_NUM(MAP_MT_EMBER_EXTERIOR),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_MODERATE_TO_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 8 },
    },
    { // MAP_SIX_ISLAND_PATTERN_BUSH: listed, Pattern Bush (Outlands)
        MAP_GROUP(MAP_SIX_ISLAND_PATTERN_BUSH), MAP_NUM(MAP_SIX_ISLAND_PATTERN_BUSH),
        { .reach = WILD_REACH_OUTLANDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_FIVE_ISLAND_LOST_CAVE_ROOM1: listed, Lost Cave (Dungeon)
        MAP_GROUP(MAP_FIVE_ISLAND_LOST_CAVE_ROOM1), MAP_NUM(MAP_FIVE_ISLAND_LOST_CAVE_ROOM1),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 14 },
    },
    { // MAP_FIVE_ISLAND_LOST_CAVE_ROOM4: listed, Lost Cave (Dungeon)
        MAP_GROUP(MAP_FIVE_ISLAND_LOST_CAVE_ROOM4), MAP_NUM(MAP_FIVE_ISLAND_LOST_CAVE_ROOM4),
        { .reach = WILD_REACH_DUNGEON, .intent = WILD_DUNGEON_HARD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 3, .floorCount = 14 },
    },
    { // MAP_ROUTE19: listed, Route 19 (Wilds)
        MAP_GROUP(MAP_ROUTE19), MAP_NUM(MAP_ROUTE19),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE20: listed, Route 20 (Outlands)
        MAP_GROUP(MAP_ROUTE20), MAP_NUM(MAP_ROUTE20),
        { .reach = WILD_REACH_OUTLANDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE21_NORTH: listed, Route 21 (Road)
        MAP_GROUP(MAP_ROUTE21_NORTH), MAP_NUM(MAP_ROUTE21_NORTH),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ROUTE21_SOUTH: listed, Route 21 (Road)
        MAP_GROUP(MAP_ROUTE21_SOUTH), MAP_NUM(MAP_ROUTE21_SOUTH),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ONE_ISLAND_KINDLE_ROAD: listed, Kindle Road (Road)
        MAP_GROUP(MAP_ONE_ISLAND_KINDLE_ROAD), MAP_NUM(MAP_ONE_ISLAND_KINDLE_ROAD),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_ONE_ISLAND_TREASURE_BEACH: listed, Treasure Beach (Wilds)
        MAP_GROUP(MAP_ONE_ISLAND_TREASURE_BEACH), MAP_NUM(MAP_ONE_ISLAND_TREASURE_BEACH),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_THREE_ISLAND_BOND_BRIDGE: listed, Bond Bridge (Road)
        MAP_GROUP(MAP_THREE_ISLAND_BOND_BRIDGE), MAP_NUM(MAP_THREE_ISLAND_BOND_BRIDGE),
        { .reach = WILD_REACH_ROAD, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_FIVE_ISLAND_RESORT_GORGEOUS: listed, Resort Gorgeous (Wilds)
        MAP_GROUP(MAP_FIVE_ISLAND_RESORT_GORGEOUS), MAP_NUM(MAP_FIVE_ISLAND_RESORT_GORGEOUS),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_FIVE_ISLAND_WATER_LABYRINTH: listed, Water Labyrinth (Outlands)
        MAP_GROUP(MAP_FIVE_ISLAND_WATER_LABYRINTH), MAP_NUM(MAP_FIVE_ISLAND_WATER_LABYRINTH),
        { .reach = WILD_REACH_OUTLANDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_FIVE_ISLAND_MEADOW: listed, Five Isle Meadow (Wilds)
        MAP_GROUP(MAP_FIVE_ISLAND_MEADOW), MAP_NUM(MAP_FIVE_ISLAND_MEADOW),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_FIVE_ISLAND_MEMORIAL_PILLAR: listed, Memorial Pillar (Outlands)
        MAP_GROUP(MAP_FIVE_ISLAND_MEMORIAL_PILLAR), MAP_NUM(MAP_FIVE_ISLAND_MEMORIAL_PILLAR),
        { .reach = WILD_REACH_OUTLANDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_SIX_ISLAND_OUTCAST_ISLAND: listed, Outcast Island (Outlands)
        MAP_GROUP(MAP_SIX_ISLAND_OUTCAST_ISLAND), MAP_NUM(MAP_SIX_ISLAND_OUTCAST_ISLAND),
        { .reach = WILD_REACH_OUTLANDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_SIX_ISLAND_GREEN_PATH: listed, Green Path (Outlands)
        MAP_GROUP(MAP_SIX_ISLAND_GREEN_PATH), MAP_NUM(MAP_SIX_ISLAND_GREEN_PATH),
        { .reach = WILD_REACH_OUTLANDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_SIX_ISLAND_WATER_PATH: listed, Water Path (Wilds)
        MAP_GROUP(MAP_SIX_ISLAND_WATER_PATH), MAP_NUM(MAP_SIX_ISLAND_WATER_PATH),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_SIX_ISLAND_RUIN_VALLEY: listed, Ruin Valley (Outlands)
        MAP_GROUP(MAP_SIX_ISLAND_RUIN_VALLEY), MAP_NUM(MAP_SIX_ISLAND_RUIN_VALLEY),
        { .reach = WILD_REACH_OUTLANDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_SEVEN_ISLAND_TRAINER_TOWER: listed, Trainer Tower grounds (Wilds)
        MAP_GROUP(MAP_SEVEN_ISLAND_TRAINER_TOWER), MAP_NUM(MAP_SEVEN_ISLAND_TRAINER_TOWER),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_SEVEN_ISLAND_SEVAULT_CANYON_ENTRANCE: listed, Sevault Canyon Entrance (Wilds)
        MAP_GROUP(MAP_SEVEN_ISLAND_SEVAULT_CANYON_ENTRANCE), MAP_NUM(MAP_SEVEN_ISLAND_SEVAULT_CANYON_ENTRANCE),
        { .reach = WILD_REACH_WILDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_SEVEN_ISLAND_SEVAULT_CANYON: listed, Sevault Canyon (Outlands)
        MAP_GROUP(MAP_SEVEN_ISLAND_SEVAULT_CANYON), MAP_NUM(MAP_SEVEN_ISLAND_SEVAULT_CANYON),
        { .reach = WILD_REACH_OUTLANDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
    { // MAP_SEVEN_ISLAND_TANOBY_RUINS: listed, Tanoby Ruins (Outlands)
        MAP_GROUP(MAP_SEVEN_ISLAND_TANOBY_RUINS), MAP_NUM(MAP_SEVEN_ISLAND_TANOBY_RUINS),
        { .reach = WILD_REACH_OUTLANDS, .intent = WILD_DUNGEON_MILD, .flat = 0, .region = WILD_PLACE_REGION_OTHER,
          .floor = 0, .floorCount = 0 },
    },
};
