"""C tables for include/wayfarer_world_data.h, the content hash, the report."""

import struct
from collections import Counter, defaultdict

import graph
import spots as sp
from authored import ACTIVITIES
from routines import NODE_NONE, REGION_NONE, SIM_COUNT, SPOT_NONE

REGION_NAMES = ["WORLD_REGION_KANTO", "WORLD_REGION_JOHTO", "WORLD_REGION_HOENN",
                "WORLD_REGION_SEVII"]
ACTIVITY_NAMES = ["WORLD_ACTIVITY_" + a.upper().replace(" ", "_") for a in ACTIVITIES]
NODE_SIZE, EDGE_SIZE, SPOT_SIZE, FAVOURITE_SIZE, TRAINER_SIZE = 8, 8, 12, 4, 44


def crc16_ccitt_false(data):
    crc = 0xFFFF
    for byte in data:
        crc ^= byte << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) if crc & 0x8000 else (crc << 1)
            crc &= 0xFFFF
    return crc


def first_edges(wg):
    out, index = [], 0
    for n in wg.nodes:
        out.append(index)
        index += len(n.edges)
    return out


def serialize(wg):
    """Little-endian bytes of the node, edge and spot tables, laid out as
    the structs in include/wayfarer_world_data.h (no padding: every field
    sits on its natural alignment)."""
    firsts = first_edges(wg)
    nodes = b"".join(struct.pack("<HHBBBB", n.map.value, firsts[n.id], n.x, n.y,
                                 len(n.edges), n.flags) for n in wg.nodes)
    edges = b"".join(struct.pack("<HBBBBBB", e.target, e.kind, e.a, e.b, e.c, e.warp_id, 0)
                     for e in wg.edges)
    spot_bytes = []
    for s in wg.spots:
        start, count = wg.spot_data(s)
        spot_bytes.append(struct.pack("<HHHBBBBBB", s.node, start, count, s.kind, s.x, s.y,
                                      s.facing, s.flags, s.activities))
    return nodes, edges, b"".join(spot_bytes)


def content_hash(wg):
    nodes, edges, spot_bytes = serialize(wg)
    return crc16_ccitt_false(nodes + edges + spot_bytes)


def node_flags(n):
    parts = []
    if n.flags & 1:
        parts.append("WORLD_NODE_FLAG_INTERIOR")
    parts.append("(%s << WORLD_NODE_REGION_SHIFT)" % REGION_NAMES[n.flags >> 1])
    return " | ".join(parts)


def spot_flags(s):
    parts = []
    if s.flags & sp.FLAG_PUBLIC:
        parts.append("WORLD_SPOT_FLAG_PUBLIC")
    if s.flags & sp.FLAG_CAPACITY_2:
        parts.append("WORLD_SPOT_FLAG_CAPACITY_2")
    template = (s.flags >> sp.TEMPLATE_SHIFT) & 3
    if template:
        parts.append("(%s << WORLD_SPOT_TEMPLATE_SHIFT)"
                     % ["WORLD_TEMPLATE_DEFAULT", "WORLD_TEMPLATE_STAND_AND_FACE",
                        "WORLD_TEMPLATE_SIT_OR_IDLE", "WORLD_TEMPLATE_WANDER"][template])
    return " | ".join(parts) or "0"


def activity_byte(s):
    if s.kind != sp.NAMED:
        return "0xFF"
    first, second = s.activities & 0xF, s.activities >> 4
    name = lambda a: "WORLD_ACTIVITY_NONE" if a == 15 else ACTIVITY_NAMES[a]
    return "%s | (%s << 4)" % (name(first), name(second))


def trainer_flags(t):
    parts = [name for bit, name in ((1, "WORLD_TRAINER_FLAG_TRAVELLER"),
                                    (2, "WORLD_TRAINER_FLAG_ALOOF"),
                                    (4, "WORLD_TRAINER_FLAG_GYM_LEADER")) if t.flags & bit]
    return " | ".join(parts) or "0"


def render(wg, rt, crc):
    firsts = first_edges(wg)
    out = []
    w = out.append
    w("// DO NOT MODIFY THIS FILE! It is auto-generated by tools/wayfarer_world/generate.py")
    w("// from the Wayfarer map data, tools/wayfarer_world/*.json and the notable-trainer")
    w("// catalog. Include it once, after global.h and wayfarer_world_data.h.")
    w("")
    w("#include \"constants/map_groups.h\"")
    w("#include \"constants/event_objects.h\"")
    w("#include \"constants/notable_trainers.h\"")
    w("")
    w("_Static_assert(sizeof(struct WayfarerWorldNode) == %d, \"node layout\");" % NODE_SIZE)
    w("_Static_assert(sizeof(struct WayfarerWorldEdge) == %d, \"edge layout\");" % EDGE_SIZE)
    w("_Static_assert(sizeof(struct WayfarerWorldSpot) == %d, \"spot layout\");" % SPOT_SIZE)
    w("_Static_assert(sizeof(struct WayfarerWorldTrainer) == %d, \"trainer layout\");" % TRAINER_SIZE)
    w("")
    w("const u16 gWayfarerWorldContentHash = 0x%04X;" % crc)
    w("")
    w("// {map, firstEdge, x, y, edgeCount, flags}")
    w("const struct WayfarerWorldNode gWayfarerWorldNodes[] = {")
    for n in wg.nodes:
        w("    /* %4d */ {%s, %d, %d, %d, %d, %s}," % (n.id, n.map.const, firsts[n.id], n.x, n.y,
                                                    len(n.edges), node_flags(n)))
    w("};")
    w("const u16 gWayfarerWorldNodeCount = %d;" % len(wg.nodes))
    w("")
    w("// {target, kind, a, b, c, warpId, padding}")
    w("const struct WayfarerWorldEdge gWayfarerWorldEdges[] = {")
    for i, e in enumerate(wg.edges):
        w("    /* %4d */ {%d, %s, %d, %d, %d, %d, 0}, // from %d" % (
            i, e.target, graph.EDGE_KIND_NAMES[e.kind], e.a, e.b, e.c, e.warp_id, e.source))
    w("};")
    w("const u16 gWayfarerWorldEdgeCount = %d;" % len(wg.edges))
    w("")
    w("// {node, dataStart, dataCount, kind, x, y, facing, flags, activities}")
    w("const struct WayfarerWorldSpot gWayfarerWorldSpots[] = {")
    for i, s in enumerate(wg.spots):
        start, count = wg.spot_data(s)
        start_text = "0x%04X" % start if s.kind == sp.NAMED else str(start)
        w("    /* %4d */ {%d, %s, %d, %s, %d, %d, %s, %s, %s}," % (
            i, s.node, start_text, count, sp.KIND_NAMES[s.kind], s.x, s.y,
            sp.DIR_NAMES[s.facing], spot_flags(s), activity_byte(s)))
    w("};")
    w("const u16 gWayfarerWorldSpotCount = %d;" % len(wg.spots))
    w("")
    w("// {x, y}: tall-grass patches, square centres, Gym approach tiles")
    w("const u8 gWayfarerWorldAreaTiles[][2] = {")
    tiles = wg.area_tiles or [(0, 0)]
    for k in range(0, len(tiles), 8):
        w("    " + " ".join("{%d, %d}," % t for t in tiles[k:k + 8]))
    w("};")
    w("")
    w("// Store floor nodes, one run per store")
    w("const u16 gWayfarerWorldStoreFloors[] = {")
    floors = wg.store_floors or [0]
    for k in range(0, len(floors), 16):
        w("    " + " ".join("%d," % f for f in floors[k:k + 16]))
    w("};")
    w("")
    cands, hops = [], []
    starts = []
    for t in rt.trainers:
        starts.append(len(cands))
        cands += t.candidates
        hops += t.candidate_hops
    w("const struct WayfarerWorldTrainer gWayfarerWorldTrainers[WORLD_SIM_TRAINER_COUNT] = {")
    for k, t in enumerate(rt.trainers):
        cycle = [ACTIVITY_NAMES[a] for a in t.cycle]
        cycle += ["WORLD_ACTIVITY_NONE"] * (4 - len(cycle))
        favs = ", ".join("{%d, %d, %s}" % (first, count, ACTIVITY_NAMES[act])
                         for first, count, _, act in t.favourites)
        w("    [%d] = { // %s" % (k, t.name))
        w("        .characterId = %s," % t.character)
        w("        .graphicsId = %s," % t.graphics)
        w("        .homeMap = %s," % t.home.const)
        w("        .homeNode = %d," % t.home_node)
        w("        .homePlace = %s," % ("WORLD_SPOT_NONE" if t.home_place == SPOT_NONE else t.home_place))
        w("        .gymNode = %s," % ("WORLD_NODE_NONE" if t.gym_node == NODE_NONE else t.gym_node))
        w("        .ownGymSpot = %s," % ("WORLD_SPOT_NONE" if t.own_gym_spot == SPOT_NONE
                                         else t.own_gym_spot))
        w("        .candidateStart = %d," % starts[k])
        w("        .candidateCount = %d," % len(t.candidates))
        w("        .searchBound = %d," % t.search_bound)
        w("        .radius = %s," % ("WORLD_RADIUS_TRAVELLER" if t.traveller else "WORLD_RADIUS_NARROW"))
        w("        .flags = %s," % trainer_flags(t))
        w("        .badgeRegion = %s," % ("WORLD_REGION_NONE" if t.badge_region == REGION_NONE
                                          else REGION_NAMES[t.badge_region]))
        w("        .badgeIndex = %d," % t.badge_index)
        w("        .cycleLength = %d," % len(t.cycle))
        w("        .cycle = {%s}," % ", ".join(cycle))
        w("        .favouriteCount = %d," % len(t.favourites))
        w("        .favourites = {%s}," % favs)
        w("    },")
    w("};")
    w("")
    w("const u16 gWayfarerWorldCandidates[] = {")
    for k in range(0, max(len(cands), 1), 16):
        w("    " + " ".join("%d," % c for c in (cands or [0])[k:k + 16]))
    w("};")
    w("const u8 gWayfarerWorldCandidateHops[] = {")
    for k in range(0, max(len(hops), 1), 32):
        w("    " + " ".join("%d," % h for h in (hops or [0])[k:k + 32]))
    w("};")
    w("")
    return "\n".join(out), len(cands)


def sizes(wg, rt, candidate_count):
    out = {
        "nodes": len(wg.nodes) * NODE_SIZE,
        "edges": len(wg.edges) * EDGE_SIZE,
        "spots": len(wg.spots) * SPOT_SIZE,
        "area_tiles": len(wg.area_tiles) * 2,
        "store_floors": len(wg.store_floors) * 2,
        "trainers": SIM_COUNT * TRAINER_SIZE,
        "candidates": candidate_count * 3,
    }
    out["total"] = sum(out.values())
    return out


def report(wg, rt, crc, byte_sizes, seconds):
    world = wg.world
    per_map = {}
    split = {}
    for info in world.scope:
        nodes = wg.map_nodes(info.name)
        per_map[info.name] = len(nodes)
        if len(nodes) > 1:
            split[info.name] = [[n.id, n.x, n.y] for n in nodes]
    kinds = defaultdict(Counter)
    for s in wg.spots:
        kinds[s.map.region][sp.KIND_KEYS[s.kind]] += 1
    edge_kinds = Counter(graph.EDGE_KIND_NAMES[e.kind] for e in wg.edges)
    det = wg.detector
    trainers = []
    for t in rt.trainers:
        trainers.append({
            "name": t.name, "home": t.home.name, "home_node": t.home_node,
            "gym_node": None if t.gym_node == NODE_NONE else t.gym_node,
            "home_place": None if t.home_place == SPOT_NONE else t.home_place,
            "radius": t.radius, "traveller": t.traveller, "aloof": t.aloof,
            "candidates": len(t.candidates), "search_bound": t.search_bound,
            "search_targets": t.targets,
            "favourites": [{"map": m, "first_spot": f, "spots": c, "serves": ACTIVITIES[a]}
                           for f, c, m, a in t.favourites],
            "disabled_favourites": t.disabled, "skippable_steps": t.skips,
            "sprite": t.graphics, "sprite_sheet": t.sheet,
        })
    return {
        "schema": 1,
        "content_hash": "0x%04X" % crc,
        "generator_seconds": round(seconds, 2),
        "maps_in_scope": len(world.scope),
        "maps_in_scope_by_region": dict(Counter(m.region for m in world.scope)),
        "excluded_maps": {k: len(v) for k, v in world.excluded.items()},
        "nodes": len(wg.nodes), "edges": len(wg.edges), "spots": len(wg.spots),
        "edges_by_kind": dict(sorted(edge_kinds.items())),
        "spots_by_region_and_kind": {r: dict(sorted(c.items())) for r, c in sorted(kinds.items())},
        "table_bytes": byte_sizes,
        "table_bytes_over_300k": byte_sizes["total"] > 300 * 1024,
        "dynamic_warps": dict(wg.builder.report["dynamic_warps"]),
        "skipped_warps": dict(wg.builder.report["skipped_warps"]),
        "asymmetric_moves": wg.builder.report["asymmetric_moves"],
        "dropped_spots": dict(wg.dropped),
        "unreachable_spots_by_map": {m: dict(c) for m, c in sorted(wg.unreachable.items())},
        "dropped_components_by_map": dict(sorted(wg.dropped_components.items())),
        "split_maps": split,
        "nodes_per_map": per_map,
        "stores": [{"door": s["door"], "floors": s["floors"]} for s in det.stores],
        "rooftops": sorted(det.roofs),
        "findings": {k: v for k, v in det.findings.items()},
        "npc_chat_rejects": dict(det.report["npc_rejects"]),
        "squares_over_cap": dict(det.report["squares_over_cap"]),
        "ignored_objects": [{"map": m, "local_id": l, "why": why}
                            for (m, l), why in sorted(wg.overrides.ignore_objects.items())],
        "new_game_hidden_flags": {k: len(v) for k, v in wg.flags.items()},
        "warnings": rt.warnings,
        "trainers": trainers,
    }
