SSAnne_1F_Room2_EventScript_ItemTM31::
	finditem ITEM_TM31
	end

SSAnne_2F_Room2_EventScript_ItemStardust::
	finditem ITEM_STARDUST
	end

SSAnne_2F_Room4_EventScript_ItemXAttack::
	finditem ITEM_X_ATTACK
	end

SSAnne_B1F_Room2_EventScript_ItemTM44::
	finditem ITEM_TM44
	end

SSAnne_B1F_Room3_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

SSAnne_B1F_Room5_EventScript_ItemSuperPotion::
	finditem ITEM_SUPER_POTION
	end

SSAnne_Kitchen_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

RocketHideout_B1F_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

RocketHideout_B1F_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

RocketHideout_B2F_EventScript_ItemXSpeed::
	finditem ITEM_X_SPEED
	end

RocketHideout_B2F_EventScript_ItemMoonStone::
	finditem ITEM_MOON_STONE
	end

RocketHideout_B2F_EventScript_ItemTM12::
	finditem ITEM_TM12
	end

RocketHideout_B2F_EventScript_ItemSuperPotion::
	finditem ITEM_SUPER_POTION
	end

RocketHideout_B3F_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

RocketHideout_B3F_EventScript_ItemTM21::
	finditem ITEM_TM21
	end

RocketHideout_B3F_EventScript_ItemBlackGlasses::
	finditem ITEM_BLACK_GLASSES
	end

RocketHideout_B4F_EventScript_ItemTM49::
	finditem ITEM_TM49
	end

RocketHideout_B4F_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

RocketHideout_B4F_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end
