RocketHideout_B1F_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

RocketHideout_B1F_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

RocketHideout_B2F_EventScript_ItemXSpeed::
	finditem ITEM_X_SPEED
	end

RocketHideout_B2F_EventScript_ItemMoonStone::
	finditem ITEM_MOON_STONE
	end

RocketHideout_B2F_EventScript_ItemTM12::
	finditem ITEM_TM12
	end

RocketHideout_B2F_EventScript_ItemSuperPotion::
	finditem ITEM_SUPER_POTION
	end

RocketHideout_B3F_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

RocketHideout_B3F_EventScript_ItemTM21::
	finditem ITEM_TM21
	end

RocketHideout_B3F_EventScript_ItemBlackGlasses::
	finditem ITEM_BLACK_GLASSES
	end

RocketHideout_B4F_EventScript_ItemTM49::
	finditem ITEM_TM49
	end

RocketHideout_B4F_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

RocketHideout_B4F_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end

PowerPlant_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

PowerPlant_EventScript_ItemTM17::
	finditem ITEM_TM_PROTECT
	end

PowerPlant_EventScript_ItemTM25::
	finditem ITEM_TM_THUNDER
	end

PowerPlant_EventScript_ItemThunderStone::
	finditem ITEM_THUNDER_STONE
	end

PowerPlant_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end
