#ifndef GUARD_CONSTANTS_LEAGUE_CIRCUIT_H
#define GUARD_CONSTANTS_LEAGUE_CIRCUIT_H

#define CIRCUIT_STAGE_NONE 0
#define CIRCUIT_STAGE_INDIGO 1
#define CIRCUIT_STAGE_MASTERS 2
#define CIRCUIT_STAGE_HOENN 3

#define CIRCUIT_ADMISSION_AVAILABLE 0
#define CIRCUIT_ADMISSION_NEEDS_8_BADGES 1
#define CIRCUIT_ADMISSION_NEEDS_INDIGO_CLEAR 2
#define CIRCUIT_ADMISSION_NEEDS_16_BADGES 3
#define CIRCUIT_ADMISSION_NEEDS_MASTERS_CLEAR 4
#define CIRCUIT_ADMISSION_NEEDS_24_BADGES 5
#define CIRCUIT_ADMISSION_UNAVAILABLE 6

#define CIRCUIT_COMMIT_INVALID 0
#define CIRCUIT_COMMIT_REPLAY 1
#define CIRCUIT_COMMIT_FIRST_CLEAR 2

#endif
