#ifndef GUARD_CONSTANTS_NOTABLE_TRAINERS_H
#define GUARD_CONSTANTS_NOTABLE_TRAINERS_H

// Stable v0 character identities; encounter IDs are mapped separately.
enum NotableTrainerId
{
    NOTABLE_TRAINER_NONE = 0,
    NOTABLE_TRAINER_BROCK = 1,
    NOTABLE_TRAINER_MISTY = 2,
    NOTABLE_TRAINER_LT_SURGE = 3,
    NOTABLE_TRAINER_ERIKA = 4,
    NOTABLE_TRAINER_JANINE = 5,
    NOTABLE_TRAINER_SABRINA = 6,
    NOTABLE_TRAINER_BLAINE = 7,
    NOTABLE_TRAINER_GIOVANNI = 8,
    NOTABLE_TRAINER_BLUE = 9,
    NOTABLE_TRAINER_LORELEI = 10,
    NOTABLE_TRAINER_BRUNO = 11,
    NOTABLE_TRAINER_AGATHA = 12,
    NOTABLE_TRAINER_KOGA = 13,
    NOTABLE_TRAINER_LANCE = 14,
    NOTABLE_TRAINER_FALKNER = 15,
    NOTABLE_TRAINER_BUGSY = 16,
    NOTABLE_TRAINER_WHITNEY = 17,
    NOTABLE_TRAINER_MORTY = 18,
    NOTABLE_TRAINER_CHUCK = 19,
    NOTABLE_TRAINER_JASMINE = 20,
    NOTABLE_TRAINER_PRYCE = 21,
    NOTABLE_TRAINER_CLAIR = 22,
    NOTABLE_TRAINER_WILL = 23,
    NOTABLE_TRAINER_KAREN = 24,
    NOTABLE_TRAINER_ROXANNE = 25,
    NOTABLE_TRAINER_BRAWLY = 26,
    NOTABLE_TRAINER_WATTSON = 27,
    NOTABLE_TRAINER_FLANNERY = 28,
    NOTABLE_TRAINER_NORMAN = 29,
    NOTABLE_TRAINER_WINONA = 30,
    NOTABLE_TRAINER_TATE_LIZA = 31,
    NOTABLE_TRAINER_JUAN = 32,
    NOTABLE_TRAINER_SIDNEY = 33,
    NOTABLE_TRAINER_PHOEBE = 34,
    NOTABLE_TRAINER_GLACIA = 35,
    NOTABLE_TRAINER_DRAKE = 36,
    NOTABLE_TRAINER_WALLACE = 37,
    NOTABLE_TRAINER_STEVEN = 38,
};

#endif // GUARD_CONSTANTS_NOTABLE_TRAINERS_H
