#ifndef GUARD_CONSTANTS_WAYFARER_ORIGIN_H
#define GUARD_CONSTANTS_WAYFARER_ORIGIN_H

#define ORIGIN_NONE 0
#define ORIGIN_NEW_BARK 1
#define ORIGIN_LITTLEROOT 2

#define ORIGIN_SCENE_JOHTO_HOUSEHOLD 0
#define ORIGIN_SCENE_JOHTO_PROFESSOR 1
#define ORIGIN_SCENE_HOENN_HOUSEHOLD 2
#define ORIGIN_SCENE_HOENN_RESCUE 3
#define ORIGIN_SCENES_COUNT 4
#define ORIGIN_SCENE_VISITOR 0
#define ORIGIN_SCENE_NATIVE 1
#define ORIGIN_SCENE_AUTHORED 2
#endif
