#ifndef GUARD_CONSTANTS_WAYFARER_KANTO_TRAINERS_H
#define GUARD_CONSTANTS_WAYFARER_KANTO_TRAINERS_H

#define TRAINER_WAYFARER_KANTO_BLUE_BULBASAUR 1809
#define TRAINER_WAYFARER_KANTO_BLUE_CHARMANDER 1810
#define TRAINER_WAYFARER_KANTO_BLUE_SQUIRTLE 1811

#define TRAINER_WAYFARER_KANTO_FIRST TRAINER_WAYFARER_KANTO_BLUE_BULBASAUR
#define TRAINER_WAYFARER_KANTO_LAST TRAINER_WAYFARER_KANTO_BLUE_SQUIRTLE
#define TRAINER_WAYFARER_KANTO_COUNT 3
// The first Blue battle's defeat record follows the Indigo League slots. The
// opening's own save state, not these flags, drives the story.
#define WAYFARER_KANTO_DEFEAT_SLOT_FIRST 717
#define WAYFARER_KANTO_DEFEAT_FLAG_FIRST (TRAINER_FLAGS_START + WAYFARER_KANTO_DEFEAT_SLOT_FIRST)

#if IS_WAYFARER
#undef TRAINERS_COUNT_WAYFARER
#define TRAINERS_COUNT_WAYFARER 1812
#endif

#endif
