#ifndef GUARD_CONSTANTS_WAYFARER_VIRIDIAN_TRAINERS_H
#define GUARD_CONSTANTS_WAYFARER_VIRIDIAN_TRAINERS_H

// Selected FRLG Viridian Gym roster follows the shared Indigo League allocation.
#define TRAINER_VIRIDIAN_GYM_TAKASHI_HNS 1800
#define TRAINER_VIRIDIAN_GYM_YUJI_HNS 1801
#define TRAINER_VIRIDIAN_GYM_ATSUSHI_HNS 1802
#define TRAINER_VIRIDIAN_GYM_JASON_HNS 1803
#define TRAINER_VIRIDIAN_GYM_COLE_HNS 1804
#define TRAINER_VIRIDIAN_GYM_KIYO_HNS 1805
#define TRAINER_VIRIDIAN_GYM_SAMUEL_HNS 1806
#define TRAINER_VIRIDIAN_GYM_WARREN_HNS 1807
#define TRAINER_VIRIDIAN_GYM_GIOVANNI_HNS 1808

#define TRAINER_VIRIDIAN_GYM_FIRST TRAINER_VIRIDIAN_GYM_TAKASHI_HNS
#define TRAINER_VIRIDIAN_GYM_LAST TRAINER_VIRIDIAN_GYM_GIOVANNI_HNS
#define TRAINER_VIRIDIAN_GYM_COUNT 9
#define VIRIDIAN_GYM_DEFEAT_FLAG_FIRST (TRAINER_FLAGS_START + 703)

#if IS_WAYFARER
#undef TRAINERS_COUNT_WAYFARER
#define TRAINERS_COUNT_WAYFARER 1809
#endif

#endif // GUARD_CONSTANTS_WAYFARER_VIRIDIAN_TRAINERS_H
