#ifndef GUARD_CONSTANTS_WAYFARER_PERSISTENCE_H
#define GUARD_CONSTANTS_WAYFARER_PERSISTENCE_H

// Wayfarer keeps Hoenn script state out of the HnS SaveBlock1 namespaces.
// The upper nibble identifies the bank; the remaining bits retain the original
// Emerald flag id or variable offset.
#define WAYFARER_HOENN_FLAG_NAMESPACE       0x6000
#define WAYFARER_HOENN_VAR_NAMESPACE        0x7000
#define WAYFARER_COMMON_FLAG_NAMESPACE      0xA000
#define WAYFARER_COMMON_VAR_NAMESPACE       0xB000
#define WAYFARER_PERSISTENCE_NAMESPACE_MASK 0xF000
#define WAYFARER_PERSISTENCE_VALUE_MASK     0x0FFF

// Hidden-item events have a 13-bit flag field. Its top bit identifies a
// source Hoenn flag while the lower bits retain the Emerald flag id.
#define WAYFARER_HOENN_HIDDEN_ITEM_MARKER 0x1000

#define HOENN_FLAG_ID(sourceId) (WAYFARER_HOENN_FLAG_NAMESPACE | (sourceId))
#define HOENN_VAR_ID(sourceId)  (WAYFARER_HOENN_VAR_NAMESPACE | ((sourceId) - 0x4000))

#define IS_HOENN_FLAG_ID(id) (((id) & WAYFARER_PERSISTENCE_NAMESPACE_MASK) == WAYFARER_HOENN_FLAG_NAMESPACE)
#define IS_HOENN_VAR_ID(id)  (((id) & WAYFARER_PERSISTENCE_NAMESPACE_MASK) == WAYFARER_HOENN_VAR_NAMESPACE)
#define IS_WAYFARER_COMMON_FLAG_ID(id) (((id) & WAYFARER_PERSISTENCE_NAMESPACE_MASK) == WAYFARER_COMMON_FLAG_NAMESPACE)
#define IS_WAYFARER_COMMON_VAR_ID(id)  (((id) & WAYFARER_PERSISTENCE_NAMESPACE_MASK) == WAYFARER_COMMON_VAR_NAMESPACE)

#define HOENN_FLAG_SOURCE_ID(id) ((id) & WAYFARER_PERSISTENCE_VALUE_MASK)
#define HOENN_VAR_SOURCE_ID(id)  (0x4000 + ((id) & WAYFARER_PERSISTENCE_VALUE_MASK))
#define WAYFARER_COMMON_ID_INDEX(id) ((id) & WAYFARER_PERSISTENCE_VALUE_MASK)

#define WAYFARER_HOENN_VARS_COUNT 256

// Temporary flags (0x000-0x01F), Trainer flags (0x500-0x85F), and special
// flags (0x4000-0x407F) have separate lifecycles and are not stored here.
#define WAYFARER_HOENN_FLAGS_LOW_START  0x020
#define WAYFARER_HOENN_FLAGS_LOW_END    0x4FF
#define WAYFARER_HOENN_FLAGS_HIGH_START 0x860
#define WAYFARER_HOENN_FLAGS_HIGH_END   0x95F
#define WAYFARER_HOENN_FLAGS_LOW_COUNT  (WAYFARER_HOENN_FLAGS_LOW_END - WAYFARER_HOENN_FLAGS_LOW_START + 1)
#define WAYFARER_HOENN_FLAGS_HIGH_COUNT (WAYFARER_HOENN_FLAGS_HIGH_END - WAYFARER_HOENN_FLAGS_HIGH_START + 1)
#define WAYFARER_HOENN_PERSISTENT_FLAG_COUNT (WAYFARER_HOENN_FLAGS_LOW_COUNT + WAYFARER_HOENN_FLAGS_HIGH_COUNT)
#define WAYFARER_HOENN_PERSISTENT_FLAG_BYTES ((WAYFARER_HOENN_PERSISTENT_FLAG_COUNT + 7) / 8)

#define WAYFARER_HOENN_DAILY_FLAGS_START 0x920
#define WAYFARER_HOENN_DAILY_FLAGS_END   0x95F

#define WAYFARER_HOENN_BADGE_FLAG_START   0x867
#define WAYFARER_HOENN_BADGE_COUNT        8
#define WAYFARER_HOENN_VISITED_FLAG_START 0x86F
#define WAYFARER_HOENN_VISITED_COUNT      16
#define WAYFARER_HOENN_GAME_CLEAR_FLAG    0x864
#define WAYFARER_HOENN_CHAMPION_FLAG      0x87F
#define WAYFARER_HOENN_USE_FLASH_FLAG     0x888
#define WAYFARER_HOENN_USE_STRENGTH_FLAG  0x889
#define WAYFARER_HOENN_WHITEOUT_TO_LAVARIDGE_FLAG 0x06C
#define WAYFARER_HOENN_HIDE_ROUTE_103_RIVAL_FLAG  0x2D3

// Emerald leaves source flag 0x4FF unused. Wayfarer reserves its mapped Hoenn
// bank bit for Birch's starter delivery state. The source-constant audit tests
// that no authored Emerald content claims the original flag.
#define WAYFARER_HOENN_STARTER_RECEIVED_SOURCE_FLAG 0x4FF

#define WAYFARER_HOENN_TRAINERS_COUNT      855
#define WAYFARER_HOENN_TRAINER_FLAG_BYTES ((WAYFARER_HOENN_TRAINERS_COUNT + 7) / 8)

#define WAYFARER_HOENN_STATE_MAGIC 0x57

#endif // GUARD_CONSTANTS_WAYFARER_PERSISTENCE_H
