// Generated by tools/wayfarer_ss_anne_trainers/generate.py; do not edit.
#ifndef GUARD_CONSTANTS_WAYFARER_SS_ANNE_TRAINERS_H
#define GUARD_CONSTANTS_WAYFARER_SS_ANNE_TRAINERS_H

#define TRAINER_WAYFARER_SS_ANNE_YOUNGSTER_TYLER                               1707
#define TRAINER_WAYFARER_SS_ANNE_LASS_ANN                                      1708
#define TRAINER_WAYFARER_SS_ANNE_GENTLEMAN_ARTHUR                              1709
#define TRAINER_WAYFARER_SS_ANNE_GENTLEMAN_THOMAS                              1710
#define TRAINER_WAYFARER_SS_ANNE_FISHERMAN_DALE                                1711
#define TRAINER_WAYFARER_SS_ANNE_GENTLEMAN_BROOKS                              1712
#define TRAINER_WAYFARER_SS_ANNE_GENTLEMAN_LAMAR                               1713
#define TRAINER_WAYFARER_SS_ANNE_LASS_DAWN                                     1714
#define TRAINER_WAYFARER_SS_ANNE_FISHERMAN_BARNY                               1715
#define TRAINER_WAYFARER_SS_ANNE_SAILOR_PHILLIP                                1716
#define TRAINER_WAYFARER_SS_ANNE_SAILOR_HUEY                                   1717
#define TRAINER_WAYFARER_SS_ANNE_SAILOR_DYLAN                                  1718
#define TRAINER_WAYFARER_SS_ANNE_SAILOR_LEONARD                                1719
#define TRAINER_WAYFARER_SS_ANNE_SAILOR_DUNCAN                                 1720
#define TRAINER_WAYFARER_SS_ANNE_SAILOR_EDMOND                                 1721
#define TRAINER_WAYFARER_SS_ANNE_SAILOR_TREVOR                                 1722

#define TRAINER_WAYFARER_SS_ANNE_FIRST 1707
#define TRAINER_WAYFARER_SS_ANNE_LAST  1722
#define TRAINER_WAYFARER_SS_ANNE_COUNT 16

#if IS_WAYFARER
#undef TRAINERS_COUNT_WAYFARER
#define TRAINERS_COUNT_WAYFARER      1723
#endif

#endif  // GUARD_CONSTANTS_WAYFARER_SS_ANNE_TRAINERS_H
