#ifndef GUARD_CONSTANTS_WAYFARER_APPEARANCE_H
#define GUARD_CONSTANTS_WAYFARER_APPEARANCE_H

#define APPEARANCE_NONE 0
#define APPEARANCE_GOLD 1
#define APPEARANCE_KRIS 2
#define APPEARANCE_RED 3
#define APPEARANCE_LEAF 4
#define APPEARANCE_BRENDAN 5
#define APPEARANCE_MAY 6
#define APPEARANCE_COUNT 6
#define APPEARANCE_INVALID_GRAPHICS 0xFFFF

#endif
