#ifndef GUARD_CONSTANTS_WAYFARER_KANTO_OPENING_H
#define GUARD_CONSTANTS_WAYFARER_KANTO_OPENING_H

#define KANTO_STARTER_SLOT_BULBASAUR 0
#define KANTO_STARTER_SLOT_CHARMANDER 1
#define KANTO_STARTER_SLOT_SQUIRTLE 2
#define KANTO_STARTER_SLOT_NONE 3

#define PALLET_OPENING_HOME 0
#define PALLET_OPENING_OAK_INTERCEPTION_AVAILABLE 1
#define PALLET_OPENING_LAB_STARTER_CHOICE 2
#define PALLET_OPENING_STARTER_RECEIVED 3
#define PALLET_OPENING_FIRST_BLUE_BATTLE_RESOLVED 4
#define PALLET_OPENING_PARCEL_RECEIVED 5
#define PALLET_OPENING_PARCEL_ACCEPTED 6
#define PALLET_OPENING_POKEDEX_HANDOFF_COMPLETE 7
#define PALLET_OPENING_POKE_BALLS_RECEIVED 8
#define PALLET_OPENING_COMPLETE 9

#define PALLET_RECEIPT_STARTER            (1 << 0)
#define PALLET_RECEIPT_FIRST_BATTLE       (1 << 1)
#define PALLET_RECEIPT_PARCEL_RECEIVED    (1 << 2)
#define PALLET_RECEIPT_PARCEL_ACCEPTED    (1 << 3)
#define PALLET_RECEIPT_BLUE_ARRIVED       (1 << 4)
#define PALLET_RECEIPT_POKEDEX            (1 << 5)
#define PALLET_RECEIPT_POKE_BALLS         (1 << 6)
#define PALLET_RECEIPT_PRESENTATION_DONE  (1 << 7)
#define PALLET_RECEIPT_COMPLETE           (1 << 8)

#endif
