#ifndef GUARD_GAMEPLAY_PROGRESSION_H
#define GUARD_GAMEPLAY_PROGRESSION_H

enum GameplayCurveId
{
    GAMEPLAY_CURVE_ORDINARY_TRAINER_BASELINE,
    GAMEPLAY_CURVE_SOFT_CAP,
    GAMEPLAY_CURVE_GYM_BASELINE,
    GAMEPLAY_CURVE_LEAGUE_BASELINE,
};

bool32 EvaluateGameplayCurve(u16 curveId, u32 rating, u8 *out);

#endif
