#ifndef GUARD_MULTIBOOT_POKEMON_COLOSSEUM_H
#define GUARD_MULTIBOOT_POKEMON_COLOSSEUM_H
#if ENABLE_COLOSSEUM_MULTIBOOT

extern const u16 gMultiBootProgram_PokemonColosseum_Start[0x14000];

#endif

#endif // GUARD_MULTIBOOT_POKEMON_COLOSSEUM_H
