// Generated by tools/wayfarer_coast_trainers/generate.py; do not edit.
#ifndef GUARD_WAYFARER_COAST_TRAINER_DEFEATS_H
#define GUARD_WAYFARER_COAST_TRAINER_DEFEATS_H

#include "global.h"
#include "constants/wayfarer_coast_trainers.h"

#define WAYFARER_COAST_TRAINER_DEFEAT_SLOT_NONE 0xFFFF

static const u8 sWayfarerCoastTrainerDefeatSlots[] =
{
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    8,
    13,
    18,
    18,
    22,
    25,
    28,
    28,
    2,
    5,
    29,
};

static inline u16 WayfarerCoastTrainerGetDefeatSlot(u16 trainerId)
{
    if (trainerId < TRAINER_WAYFARER_COAST_FIRST || trainerId > TRAINER_WAYFARER_COAST_LAST)
        return WAYFARER_COAST_TRAINER_DEFEAT_SLOT_NONE;
    return sWayfarerCoastTrainerDefeatSlots[trainerId - TRAINER_WAYFARER_COAST_FIRST];
}

#endif  // GUARD_WAYFARER_COAST_TRAINER_DEFEATS_H
