#ifndef GUARD_WAYFARER_AMBIENCE_DATA_H
#define GUARD_WAYFARER_AMBIENCE_DATA_H

// The notable-ambience ROM tables (beat pool, trainer tags, relations),
// generated by tools/wayfarer_world/generate.py from ambience.json into
// src/data/wayfarer_world/tables.h. Engine-free, like wayfarer_world_data.h.

#include "gba/types.h"
#include "constants/wayfarer_world.h"
#include "constants/wayfarer_ambience.h"

struct WayfarerAmbienceBeat
{
    u32 all;             // AMBIENCE_FACT_* that must all hold
    u32 any;             // at least one of these holds; 0 = no any-term
    u16 spotKinds;       // FACT_SPOT: bit per WORLD_SPOT_* kind
    u16 spotNamed;       // FACT_SPOT: a named spot offering one of these (bit per WORLD_ACTIVITY_*)
    u16 notSpotKinds;    // FACT_NOT_SPOT: bit per WORLD_SPOT_* kind
    u16 activities;      // FACT_ACTIVITY: bit per WORLD_ACTIVITY_*
    u16 tagsAny;         // AMBIENCE_TAG_*: the trainer has one of these; 0 = no requirement
    u16 tagsNone;        // AMBIENCE_TAG_*: the trainer has none of these
    u8 playerWithin;     // FACT_PLAYER_WITHIN: tiles
    u8 adjacentTicks;    // FACT_PLAYER_ADJACENT: ticks
    u8 notableWithin;    // FACT_NOTABLE: tiles
    u8 relation;         // FACT_NOTABLE: enum AmbienceRelation, NONE = any walker
    u8 cls;              // enum AmbienceClass
    u8 flags;            // AMBIENCE_FLAG_*
    u8 cooldown;         // ticks before the same walker may run it again
    u8 stepCount;        // 1 to AMBIENCE_MAX_STEPS
    // {op, arg}: enum AmbienceOp, then per op the target, ticks, step, object,
    // icon, effect | where << 4, even icon | odd icon << 4, or companion act.
    // Raw bytes: apcs-gnu would pad a 2-byte struct to 4.
    u8 steps[AMBIENCE_MAX_STEPS][2];
};

// Indexed by simulated-trainer slot (gWayfarerWorldTrainers order).
struct WayfarerAmbienceTrainer
{
    u16 tags;            // AMBIENCE_TAG_*
    u8 preferred;        // beat index listed twice at the pick, or AMBIENCE_PREFERRED_NONE
    u8 companionCount;   // 1 to AMBIENCE_COMPANION_MAX
    u16 companions[AMBIENCE_COMPANION_MAX]; // species | AMBIENCE_COMPANION_BIG, in fallback order; 0 unused
};

extern const struct WayfarerAmbienceBeat gWayfarerAmbienceBeats[];
extern const u8 gWayfarerAmbienceBeatCount;
extern const struct WayfarerAmbienceTrainer gWayfarerAmbienceTrainers[WORLD_SIM_TRAINER_COUNT];
// [slot][slot]: enum AmbienceRelation, symmetric, NONE on the diagonal.
extern const u8 gWayfarerAmbienceRelations[WORLD_SIM_TRAINER_COUNT][WORLD_SIM_TRAINER_COUNT];

#endif // GUARD_WAYFARER_AMBIENCE_DATA_H
