// Generated by tools/wayfarer_ss_anne_trainers/generate.py; do not edit.
#ifndef GUARD_WAYFARER_SS_ANNE_TRAINER_DEFEATS_H
#define GUARD_WAYFARER_SS_ANNE_TRAINER_DEFEATS_H

#include "global.h"
#include "constants/wayfarer_ss_anne_trainers.h"

#define WAYFARER_SS_ANNE_TRAINER_DEFEAT_SLOT_NONE 0xFFFF

static inline u16 WayfarerSSAnneTrainerGetDefeatSlot(u16 trainerId)
{
    if (trainerId < TRAINER_WAYFARER_SS_ANNE_FIRST || trainerId > TRAINER_WAYFARER_SS_ANNE_LAST)
        return WAYFARER_SS_ANNE_TRAINER_DEFEAT_SLOT_NONE;
    return trainerId - TRAINER_WAYFARER_SS_ANNE_FIRST;
}

#endif  // GUARD_WAYFARER_SS_ANNE_TRAINER_DEFEATS_H
