#ifndef GUARD_WAYFARER_WORLD_DATA_H
#define GUARD_WAYFARER_WORLD_DATA_H

// Saved world state and the generated walker-graph and spot tables. This
// header has no engine dependencies so the offline report tool can compile
// the simulation core on the host.

#include "gba/types.h"
#include "constants/wayfarer_world.h"

// One simulated trainer: 8 bytes, the layout in the world simulation spec.
// Each 32-bit word is filled exactly, so no field straddles a storage unit.
struct WayfarerWorldRecord
{
    u32 node:12;      // current walker-graph node
    u32 destKind:2;   // enum WorldDestKind
    u32 destId:14;    // spot id (WORLD_DEST_SPOT, or WORLD_DEST_HOME for non-leaders)
    u32 state:3;      // enum WorldState
    u32 waited:1;     // blocked at the last heartbeat
    u32 arrival:3;    // enum WorldArrival
    u32 crossing:8;   // map side: coordinate along it on this map; door/transit: landing warp id
    u32 step:2;       // activity cycle position
    u32 activity:4;   // enum WorldActivity
    u32 dwell:6;      // heartbeats left
    u32 lifeEvent:2;  // enum WorldLifeEvent
    u32 lifeSteps:2;
    u32 stayBits:2;   // WORLD_STAY_*
    u32 reserved:3;
};

// Local actor block entry, 3 bytes: trainer (6 bits) and facing (2 bits, DIR - 1),
// then x and y. Kept as raw bytes because apcs-gnu would pad a 3-byte struct.
#define WORLD_LOCAL_ACTOR_BYTES 3

struct WayfarerWorldState
{
    u8 schemaVersion;
    u8 reserved;
    u16 contentHash;
    struct WayfarerWorldRecord records[WORLD_SIM_TRAINER_COUNT];
    u8 localActors[WORLD_LOCAL_ACTOR_COUNT * WORLD_LOCAL_ACTOR_BYTES];
    u8 padding[3];
};

#define WORLD_STATE_SIZE 216

// ROM tables, generated by tools/wayfarer_world/generate.py.

struct WayfarerWorldNode
{
    u16 map;          // MAP_* constant
    u16 firstEdge;    // into gWayfarerWorldEdges
    u8 x;             // representative tile: the component's first tile in scan order
    u8 y;
    u8 edgeCount;
    u8 flags;         // WORLD_NODE_FLAG_*, region
};

// Map side: a, b = lane run on the source map's border (inclusive, along the
// side), c = the lane's first coordinate on the target map. Warp: a, b = the
// warp tile, c = the destination warp id on the target map. Transit: a, b =
// the boarding tile, c = the landing warp id on the target map.
struct WayfarerWorldEdge
{
    u16 target;
    u8 kind;          // enum WorldEdgeKind
    u8 a;
    u8 b;
    u8 c;
    u8 warpId;        // warp edges: the source warp id; otherwise 0xFF
    u8 padding;
};

// Spots of one map are contiguous, ordered by kind, then y, then x, and maps
// follow map order, so (map, kind) is a contiguous run. dataStart/dataCount:
//   tall grass, square, Gym visitor: area tiles in gWayfarerWorldAreaTiles
//     (the patch, the square's centres, the approach tiles nearest the exit first);
//   store: floor nodes in gWayfarerWorldStoreFloors;
//   NPC chat: dataStart = the NPC's local id, dataCount = 0;
//   named: dataStart = second trainer tile (x | y << 8) at capacity 2, else 0xFFFF;
//   otherwise 0.
struct WayfarerWorldSpot
{
    u16 node;
    u16 dataStart;
    u16 dataCount;
    u8 kind;          // enum WorldSpotKind
    u8 x;             // standing or anchor tile; a Gym visitor's exit warp
    u8 y;
    u8 facing;        // DIR_* for standing kinds, DIR_NONE for areas
    u8 flags;         // WORLD_SPOT_FLAG_*
    u8 activities;    // named: first activity | second << 4 (15 = none); else 0xFF
};

// A favourite is a contiguous run of spots: one named spot, or every spot of
// one kind on one map (or a tile-precise one).
struct WayfarerWorldFavourite
{
    u16 firstSpot;
    u8 spotCount;
    u8 activity;      // the cycle activity it serves
};

struct WayfarerWorldTrainer
{
    u16 characterId;     // NOTABLE_TRAINER_*
    u16 graphicsId;      // OBJ_EVENT_GFX_* with a Full 9-frame sheet
    u16 homeMap;         // MAP_* home base
    u16 homeNode;        // the home map's node holding most of its spots
    u16 homePlace;       // non-leaders: home place spot, or WORLD_SPOT_NONE
    u16 gymNode;         // Gym Leaders: their Gym's interior node; else WORLD_NODE_NONE
    u16 ownGymSpot;      // Gym Leaders: their own Gym's visitor spot; else WORLD_SPOT_NONE
    u16 candidateStart;  // into gWayfarerWorldCandidates / gWayfarerWorldCandidateHops
    u16 candidateCount;
    u8 searchBound;      // path search depth limit (hops)
    u8 radius;           // WORLD_RADIUS_NARROW or WORLD_RADIUS_TRAVELLER
    u8 flags;            // WORLD_TRAINER_FLAG_*
    u8 badgeRegion;      // Gym Leaders: WORLD_REGION_KANTO/JOHTO/HOENN; else WORLD_REGION_NONE
    u8 badgeIndex;       // badge index within that region (0-7)
    u8 cycleLength;      // 3 or 4
    u8 cycle[WORLD_CYCLE_MAX_STEPS];
    u8 favouriteCount;
    u8 leaderLocalId;    // Gym Leaders: their own Gym object's local id; else 0
    u8 padding[2];
    struct WayfarerWorldFavourite favourites[WORLD_FAVOURITE_MAX];
    u16 altGraphicsIds[2]; // the same character's other sprites (FRLG, HNS), or 0
};

struct WayfarerWorldCandidateRange
{
    u16 start;
    u16 count;
};

extern const struct WayfarerWorldNode gWayfarerWorldNodes[];
extern const u16 gWayfarerWorldNodeCount;
extern const struct WayfarerWorldEdge gWayfarerWorldEdges[];
extern const u16 gWayfarerWorldEdgeCount;
extern const struct WayfarerWorldSpot gWayfarerWorldSpots[];
extern const u16 gWayfarerWorldSpotCount;
extern const u8 gWayfarerWorldAreaTiles[][2];
extern const u16 gWayfarerWorldStoreFloors[];
extern const struct WayfarerWorldTrainer gWayfarerWorldTrainers[WORLD_SIM_TRAINER_COUNT];
extern const u16 gWayfarerWorldCandidates[];   // spot ids, sorted by hops, then spot id
extern const u8 gWayfarerWorldCandidateHops[];  // hops from the home node, per candidate
extern const u8 gWayfarerWorldHomeHops[];
// The candidates that offer each activity, as positions in the trainer's list.
extern const struct WayfarerWorldCandidateRange gWayfarerWorldActivityRanges[WORLD_SIM_TRAINER_COUNT][WORLD_ACTIVITY_COUNT];
extern const u16 gWayfarerWorldActivityCandidates[];       // [slot * node count + node]: hops to the home node, 255 none
extern const u16 gWayfarerWorldContentHash;

#endif // GUARD_WAYFARER_WORLD_DATA_H
