#!/usr/bin/env python3
"""Generate the isolated, one-time S.S. Anne Trainer roster."""
from __future__ import annotations

import hashlib
import importlib.util
import json
import re
import subprocess
import tempfile
from pathlib import Path

TOOL_DIR = Path(__file__).resolve().parent
GAME = TOOL_DIR.parents[1]
REPO = GAME.parent
BASE = 1707
TRAINERS = (
    "TRAINER_YOUNGSTER_TYLER", "TRAINER_LASS_ANN", "TRAINER_GENTLEMAN_ARTHUR",
    "TRAINER_GENTLEMAN_THOMAS", "TRAINER_FISHERMAN_DALE", "TRAINER_GENTLEMAN_BROOKS",
    "TRAINER_GENTLEMAN_LAMAR", "TRAINER_LASS_DAWN", "TRAINER_FISHERMAN_BARNY",
    "TRAINER_SAILOR_PHILLIP", "TRAINER_SAILOR_HUEY", "TRAINER_SAILOR_DYLAN",
    "TRAINER_SAILOR_LEONARD", "TRAINER_SAILOR_DUNCAN", "TRAINER_SAILOR_EDMOND",
    "TRAINER_SAILOR_TREVOR",
)

def numeric_defines(path: Path) -> dict[str, int]:
    return {
        match.group(1): int(match.group(2), 0)
        for match in re.finditer(
            r"(?m)^#define\s+([A-Z0-9_]+)\s+(0x[0-9A-Fa-f]+|[0-9]+)\s*(?://.*)?$",
            path.read_text(),
        )
    }

def validate_allocations(rows: list[dict]) -> None:
    runtime_ids = [row["numeric_id"] for row in rows]
    defeat_slots = [row["slot"] for row in rows]
    if len(runtime_ids) != len(set(runtime_ids)) or len(defeat_slots) != len(set(defeat_slots)):
        raise ValueError("Anne runtime IDs and defeat slots must be unique")

    coast = numeric_defines(GAME / "include/constants/wayfarer_coast_trainers.h")
    opponents = numeric_defines(GAME / "include/constants/opponents.h")
    if BASE != coast["TRAINER_WAYFARER_COAST_LAST"] + 1:
        raise ValueError("Anne runtime IDs must begin after the current Wayfarer Trainer ranges")
    if runtime_ids[-1] >= opponents["MAX_TRAINERS_COUNT_WAYFARER"]:
        raise ValueError("Anne runtime IDs overlap the reserved partner/facility range")

    flags = numeric_defines(GAME / "include/constants/flags_hns.h")
    wayfarer_flag_owners: dict[int, list[str]] = {}
    for name, value in flags.items():
        if name.startswith("FLAG_WAYFARER_"):
            wayfarer_flag_owners.setdefault(value, []).append(name)
    for row in rows:
        flag = "FLAG_WAYFARER_SS_ANNE_TRAINER_" + row["source"].rsplit("_", 1)[1]
        if flag not in flags:
            raise ValueError(f"missing Anne defeat flag {flag}")
        if wayfarer_flag_owners[flags[flag]] != [flag]:
            raise ValueError(f"Anne defeat flag overlaps another Wayfarer state: {flag}")

def runtime(source: str) -> str:
    return "TRAINER_WAYFARER_SS_ANNE_" + source.removeprefix("TRAINER_")

def blocks() -> dict[str, str]:
    data = (GAME / "src/data/trainers_frlg.party").read_text().replace("\r\n", "\n")
    marks = list(re.finditer(r"(?m)^=== (TRAINER_[A-Z0-9_]+) ===\s*$", data))
    return {m.group(1): data[m.start(): marks[i + 1].start() if i + 1 < len(marks) else len(data)]
            for i, m in enumerate(marks)}

def parser():
    spec = importlib.util.spec_from_file_location("anne_scaling", GAME / "tools/trainer_scaling/generate.py")
    module = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    spec.loader.exec_module(module)
    return module

def roster(rows: list[dict]) -> str:
    with tempfile.TemporaryDirectory(prefix="wayfarer-anne-") as temp:
        temp = Path(temp); binary = temp / "trainerproc"; output = temp / "out.h"
        run = lambda cmd, **kw: subprocess.run(cmd, text=True, capture_output=True, check=True, **kw)
        run(["cc", "-O2", str(GAME / "tools/trainerproc/main.c"), "-o", str(binary)])
        source = run(["cpp", "-traditional-cpp", "-P", "-DPOKEMON_WAYFARER", "-DPOKEMON_HNS",
                      "-DIS_WAYFARER=1", "-DIS_HNS=1", "-DIS_FRLG=0", "-DIS_EMERALD=0",
                      "-I", str(GAME / "include"), str(GAME / "src/data/trainers_frlg.party")]).stdout
        run([str(binary), "-i", "src/data/trainers_frlg.party", "-o", str(output), "-"], input=source)
        header = output.read_text()
    p = parser(); out = []
    for row in rows:
        source = row["source"]
        match = re.search(rf"\[{re.escape(source)}\]\s*=\s*\{{", header)
        if not match: raise ValueError(f"missing {source}")
        _, end = p.balanced(header, match.end() - 1)
        record = re.sub(r"(?m)^#line .*\n", "", header[match.start():end])
        out.extend([record.replace(f"[{source}]", f"[{row['id']}]", 1) + ",", ""])
    return "// Generated by tools/wayfarer_ss_anne_trainers/generate.py; do not edit.\n\n" + "\n".join(out)

def constants(rows: list[dict]) -> str:
    lines = ["// Generated by tools/wayfarer_ss_anne_trainers/generate.py; do not edit.",
             "#ifndef GUARD_CONSTANTS_WAYFARER_SS_ANNE_TRAINERS_H", "#define GUARD_CONSTANTS_WAYFARER_SS_ANNE_TRAINERS_H", ""]
    lines += [f"#define {row['id']:<70} {row['numeric_id']}" for row in rows]
    lines += ["", f"#define TRAINER_WAYFARER_SS_ANNE_FIRST {BASE}",
              f"#define TRAINER_WAYFARER_SS_ANNE_LAST  {rows[-1]['numeric_id']}",
              f"#define TRAINER_WAYFARER_SS_ANNE_COUNT {len(rows)}", "", "#if IS_WAYFARER",
              "#undef TRAINERS_COUNT_WAYFARER", f"#define TRAINERS_COUNT_WAYFARER      {BASE + len(rows)}", "#endif", "",
              "#endif  // GUARD_CONSTANTS_WAYFARER_SS_ANNE_TRAINERS_H", ""]
    return "\n".join(lines)

def defeats(rows: list[dict]) -> str:
    lines = ["// Generated by tools/wayfarer_ss_anne_trainers/generate.py; do not edit.",
             "#ifndef GUARD_WAYFARER_SS_ANNE_TRAINER_DEFEATS_H", "#define GUARD_WAYFARER_SS_ANNE_TRAINER_DEFEATS_H", "",
             "#include \"global.h\"", "#include \"constants/wayfarer_ss_anne_trainers.h\"", "",
             "#define WAYFARER_SS_ANNE_TRAINER_DEFEAT_SLOT_NONE 0xFFFF", "",
             "static inline u16 WayfarerSSAnneTrainerGetDefeatSlot(u16 trainerId)", "{",
             "    if (trainerId < TRAINER_WAYFARER_SS_ANNE_FIRST || trainerId > TRAINER_WAYFARER_SS_ANNE_LAST)",
             "        return WAYFARER_SS_ANNE_TRAINER_DEFEAT_SLOT_NONE;",
             "    return trainerId - TRAINER_WAYFARER_SS_ANNE_FIRST;", "}", "",
             "#endif  // GUARD_WAYFARER_SS_ANNE_TRAINER_DEFEATS_H", ""]
    return "\n".join(lines)

def write(path: Path, text: str, check: bool):
    if check:
        if not path.is_file() or path.read_text() != text: raise ValueError(f"stale generated output: {path}")
    else:
        path.parent.mkdir(parents=True, exist_ok=True); path.write_text(text)

def main() -> int:
    import argparse
    args = argparse.ArgumentParser(); args.add_argument("--check", action="store_true"); check = args.parse_args().check
    source = blocks(); rows = []
    for slot, name in enumerate(TRAINERS):
        if name not in source: raise ValueError(f"missing source party {name}")
        rows.append({"id": runtime(name), "source": name, "slot": slot, "numeric_id": BASE + slot,
                     "policy": "ORDINARY", "source_hash": hashlib.sha256(source[name].encode()).hexdigest()})
    if rows[-1]["numeric_id"] != 1722: raise ValueError("Anne allocation extent drift")
    validate_allocations(rows)
    outputs = {GAME / "include/constants/wayfarer_ss_anne_trainers.h": constants(rows),
               GAME / "src/data/trainers_wayfarer_ss_anne.h": roster(rows),
               GAME / "include/wayfarer_ss_anne_trainer_defeats.h": defeats(rows),
               REPO / "docs/ss-anne-trainer-implementation/allocation-inventory.json": json.dumps({"schema_version": 1, "allocation": {"base": BASE, "count": len(rows), "next_id": BASE + len(rows), "allocations": rows}}, indent=2, sort_keys=True) + "\n"}
    for path, text in outputs.items(): write(path, text, check)
    return 0

if __name__ == "__main__": raise SystemExit(main())
