// Generated by tools/wayfarer_sinnoh_port/assets.py; do not edit.

const struct Tileset gTileset_Sinnoh_General =
{
    .isCompressed = TRUE,
    .isSecondary = FALSE,
    .tiles = gTilesetTiles_Sinnoh_General,
    .palettes = gTilesetPalettes_Sinnoh_General,
    .metatiles = gMetatiles_Sinnoh_General,
    .metatileAttributes = gMetatileAttributes_Sinnoh_General,
    .callback = InitTilesetAnim_General,
};

const struct Tileset gTileset_Sinnoh_Building =
{
    .isCompressed = TRUE,
    .isSecondary = FALSE,
    .tiles = gTilesetTiles_InsideBuilding,
    .palettes = gTilesetPalettes_Sinnoh_Building,
    .metatiles = gMetatiles_InsideBuilding,
    .metatileAttributes = gMetatileAttributes_InsideBuilding,
    .callback = InitTilesetAnim_Building,
};

const struct Tileset gTileset_Sinnoh_Petalburg =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_Sinnoh_Petalburg,
    .palettes = gTilesetPalettes_Sinnoh_Petalburg,
    .metatiles = gMetatiles_Sinnoh_Petalburg,
    .metatileAttributes = gMetatileAttributes_Sinnoh_Petalburg,
    .callback = NULL,
};

const struct Tileset gTileset_Sinnoh_Rustboro =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_Sinnoh_Rustboro,
    .palettes = gTilesetPalettes_Sinnoh_Rustboro,
    .metatiles = gMetatiles_Sinnoh_Rustboro,
    .metatileAttributes = gMetatileAttributes_Sinnoh_Rustboro,
    .callback = InitTilesetAnim_Rustboro,
};

const struct Tileset gTileset_Sinnoh_Jubilife =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_Sinnoh_Jubilife,
    .palettes = gTilesetPalettes_Sinnoh_Jubilife,
    .metatiles = gMetatiles_Sinnoh_Jubilife,
    .metatileAttributes = gMetatileAttributes_Sinnoh_Jubilife,
    .callback = NULL,
};

const struct Tileset gTileset_Sinnoh_Mauville =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_Sinnoh_Mauville,
    .palettes = gTilesetPalettes_Sinnoh_Mauville,
    .metatiles = gMetatiles_Sinnoh_Mauville,
    .metatileAttributes = gMetatileAttributes_Sinnoh_Mauville,
    .callback = InitTilesetAnim_Mauville,
};

const struct Tileset gTileset_Sinnoh_Hearthome =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_Sinnoh_Hearthome,
    .palettes = gTilesetPalettes_Sinnoh_Hearthome,
    .metatiles = gMetatiles_Sinnoh_Hearthome,
    .metatileAttributes = gMetatileAttributes_Sinnoh_Hearthome,
    .callback = NULL,
};

const struct Tileset gTileset_Sinnoh_Celestic =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_Sinnoh_Celestic,
    .palettes = gTilesetPalettes_Sinnoh_Celestic,
    .metatiles = gMetatiles_Sinnoh_Celestic,
    .metatileAttributes = gMetatileAttributes_Sinnoh_Celestic,
    .callback = NULL,
};

const struct Tileset gTileset_Sinnoh_Veilstone =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_Sinnoh_Veilstone,
    .palettes = gTilesetPalettes_Sinnoh_Veilstone,
    .metatiles = gMetatiles_Sinnoh_Veilstone,
    .metatileAttributes = gMetatileAttributes_Sinnoh_Veilstone,
    .callback = NULL,
};

const struct Tileset gTileset_Sinnoh_Lilycove =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_Sinnoh_Lilycove,
    .palettes = gTilesetPalettes_Sinnoh_Lilycove,
    .metatiles = gMetatiles_Sinnoh_Lilycove,
    .metatileAttributes = gMetatileAttributes_Sinnoh_Lilycove,
    .callback = NULL,
};

const struct Tileset gTileset_Sinnoh_Canalave =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_Sinnoh_Canalave,
    .palettes = gTilesetPalettes_Sinnoh_Canalave,
    .metatiles = gMetatiles_Sinnoh_Canalave,
    .metatileAttributes = gMetatileAttributes_Sinnoh_Canalave,
    .callback = NULL,
};

const struct Tileset gTileset_Sinnoh_Snowpoint =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_Sinnoh_Snowpoint,
    .palettes = gTilesetPalettes_Sinnoh_Snowpoint,
    .metatiles = gMetatiles_Sinnoh_Snowpoint,
    .metatileAttributes = gMetatileAttributes_Sinnoh_Snowpoint,
    .callback = NULL,
};

const struct Tileset gTileset_Sinnoh_Sunnyshore =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_Sinnoh_Sunnyshore,
    .palettes = gTilesetPalettes_Sinnoh_Sunnyshore,
    .metatiles = gMetatiles_Sinnoh_Sunnyshore,
    .metatileAttributes = gMetatileAttributes_Sinnoh_Sunnyshore,
    .callback = NULL,
};

const struct Tileset gTileset_Sinnoh_EverGrande =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_Sinnoh_EverGrande,
    .palettes = gTilesetPalettes_Sinnoh_EverGrande,
    .metatiles = gMetatiles_Sinnoh_EverGrande,
    .metatileAttributes = gMetatileAttributes_Sinnoh_EverGrande,
    .callback = InitTilesetAnim_EverGrande,
};

const struct Tileset gTileset_Sinnoh_Valor =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_Sinnoh_Valor,
    .palettes = gTilesetPalettes_Sinnoh_Valor,
    .metatiles = gMetatiles_Sinnoh_Valor,
    .metatileAttributes = gMetatileAttributes_Sinnoh_Valor,
    .callback = NULL,
};

const struct Tileset gTileset_Sinnoh_Lavaridge =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_Sinnoh_Lavaridge,
    .palettes = gTilesetPalettes_Sinnoh_Lavaridge,
    .metatiles = gMetatiles_Sinnoh_Lavaridge,
    .metatileAttributes = gMetatileAttributes_Sinnoh_Lavaridge,
    .callback = InitTilesetAnim_Lavaridge,
};

const struct Tileset gTileset_Sinnoh_Cave =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_Cave,
    .palettes = gTilesetPalettes_Cave,
    .metatiles = gMetatiles_Sinnoh_Cave,
    .metatileAttributes = gMetatileAttributes_Sinnoh_Cave,
    .callback = InitTilesetAnim_Cave,
};

const struct Tileset gTileset_Sinnoh_Pasos =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_Sinnoh_Pasos,
    .palettes = gTilesetPalettes_Sinnoh_Pasos,
    .metatiles = gMetatiles_Sinnoh_Pasos,
    .metatileAttributes = gMetatileAttributes_Sinnoh_Pasos,
    .callback = NULL,
};

const struct Tileset gTileset_Sinnoh_Shop =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_Shop,
    .palettes = gTilesetPalettes_Shop,
    .metatiles = gMetatiles_Sinnoh_Shop,
    .metatileAttributes = gMetatileAttributes_Shop,
    .callback = NULL,
};
