// Generated by tools/wayfarer_sinnoh_port/assets.py; do not edit.

const u16 gMetatiles_Sinnoh_General[] = INCBIN_U16("data/tilesets/sinnoh/primary/general/metatiles.bin");
const u16 gMetatileAttributes_Sinnoh_General[] = INCBIN_U16("data/tilesets/sinnoh/primary/general/metatile_attributes.bin");

const u16 gMetatiles_Sinnoh_Petalburg[] = INCBIN_U16("data/tilesets/sinnoh/secondary/petalburg/metatiles.bin");
const u16 gMetatileAttributes_Sinnoh_Petalburg[] = INCBIN_U16("data/tilesets/sinnoh/secondary/petalburg/metatile_attributes.bin");

const u16 gMetatiles_Sinnoh_Rustboro[] = INCBIN_U16("data/tilesets/sinnoh/secondary/rustboro/metatiles.bin");
const u16 gMetatileAttributes_Sinnoh_Rustboro[] = INCBIN_U16("data/tilesets/sinnoh/secondary/rustboro/metatile_attributes.bin");

const u16 gMetatiles_Sinnoh_Jubilife[] = INCBIN_U16("data/tilesets/sinnoh/secondary/jubilife/metatiles.bin");
const u16 gMetatileAttributes_Sinnoh_Jubilife[] = INCBIN_U16("data/tilesets/sinnoh/secondary/jubilife/metatile_attributes.bin");

const u16 gMetatiles_Sinnoh_Mauville[] = INCBIN_U16("data/tilesets/sinnoh/secondary/mauville/metatiles.bin");
const u16 gMetatileAttributes_Sinnoh_Mauville[] = INCBIN_U16("data/tilesets/sinnoh/secondary/mauville/metatile_attributes.bin");

const u16 gMetatiles_Sinnoh_Hearthome[] = INCBIN_U16("data/tilesets/sinnoh/secondary/hearthome/metatiles.bin");
const u16 gMetatileAttributes_Sinnoh_Hearthome[] = INCBIN_U16("data/tilesets/sinnoh/secondary/hearthome/metatile_attributes.bin");

const u16 gMetatiles_Sinnoh_Celestic[] = INCBIN_U16("data/tilesets/sinnoh/secondary/celestic/metatiles.bin");
const u16 gMetatileAttributes_Sinnoh_Celestic[] = INCBIN_U16("data/tilesets/sinnoh/secondary/celestic/metatile_attributes.bin");

const u16 gMetatiles_Sinnoh_Veilstone[] = INCBIN_U16("data/tilesets/sinnoh/secondary/veilstone/metatiles.bin");
const u16 gMetatileAttributes_Sinnoh_Veilstone[] = INCBIN_U16("data/tilesets/sinnoh/secondary/veilstone/metatile_attributes.bin");

const u16 gMetatiles_Sinnoh_Lilycove[] = INCBIN_U16("data/tilesets/sinnoh/secondary/lilycove/metatiles.bin");
const u16 gMetatileAttributes_Sinnoh_Lilycove[] = INCBIN_U16("data/tilesets/sinnoh/secondary/lilycove/metatile_attributes.bin");

const u16 gMetatiles_Sinnoh_Canalave[] = INCBIN_U16("data/tilesets/sinnoh/secondary/canalave/metatiles.bin");
const u16 gMetatileAttributes_Sinnoh_Canalave[] = INCBIN_U16("data/tilesets/sinnoh/secondary/canalave/metatile_attributes.bin");

const u16 gMetatiles_Sinnoh_Snowpoint[] = INCBIN_U16("data/tilesets/sinnoh/secondary/snowpoint/metatiles.bin");
const u16 gMetatileAttributes_Sinnoh_Snowpoint[] = INCBIN_U16("data/tilesets/sinnoh/secondary/snowpoint/metatile_attributes.bin");

const u16 gMetatiles_Sinnoh_Sunnyshore[] = INCBIN_U16("data/tilesets/sinnoh/secondary/sunnyshore/metatiles.bin");
const u16 gMetatileAttributes_Sinnoh_Sunnyshore[] = INCBIN_U16("data/tilesets/sinnoh/secondary/sunnyshore/metatile_attributes.bin");

const u16 gMetatiles_Sinnoh_EverGrande[] = INCBIN_U16("data/tilesets/sinnoh/secondary/ever_grande/metatiles.bin");
const u16 gMetatileAttributes_Sinnoh_EverGrande[] = INCBIN_U16("data/tilesets/sinnoh/secondary/ever_grande/metatile_attributes.bin");

const u16 gMetatiles_Sinnoh_Valor[] = INCBIN_U16("data/tilesets/sinnoh/secondary/valor/metatiles.bin");
const u16 gMetatileAttributes_Sinnoh_Valor[] = INCBIN_U16("data/tilesets/sinnoh/secondary/valor/metatile_attributes.bin");

const u16 gMetatiles_Sinnoh_Lavaridge[] = INCBIN_U16("data/tilesets/sinnoh/secondary/lavaridge/metatiles.bin");
const u16 gMetatileAttributes_Sinnoh_Lavaridge[] = INCBIN_U16("data/tilesets/sinnoh/secondary/lavaridge/metatile_attributes.bin");

const u16 gMetatiles_Sinnoh_Cave[] = INCBIN_U16("data/tilesets/sinnoh/secondary/cave/metatiles.bin");
const u16 gMetatileAttributes_Sinnoh_Cave[] = INCBIN_U16("data/tilesets/sinnoh/secondary/cave/metatile_attributes.bin");

const u16 gMetatiles_Sinnoh_Pasos[] = INCBIN_U16("data/tilesets/sinnoh/secondary/pasos/metatiles.bin");
const u16 gMetatileAttributes_Sinnoh_Pasos[] = INCBIN_U16("data/tilesets/sinnoh/secondary/pasos/metatile_attributes.bin");

const u16 gMetatiles_Sinnoh_Shop[] = INCBIN_U16("data/tilesets/sinnoh/secondary/shop/metatiles.bin");
