// Generated by tools/wayfarer_sinnoh_port/assets.py; do not edit.

const u32 gTilesetTiles_Sinnoh_General[] = INCBIN_U32("data/tilesets/sinnoh/primary/general/tiles.4bpp.fastSmol");
const u16 gTilesetPalettes_Sinnoh_General[][16] =
{
    INCBIN_U16("data/tilesets/sinnoh/primary/general/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/primary/general/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/primary/general/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/primary/general/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/primary/general/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/primary/general/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/primary/general/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/primary/general/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/primary/general/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/primary/general/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/primary/general/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/primary/general/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/primary/general/palettes/12.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/primary/general/palettes/13.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/primary/general/palettes/14.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/primary/general/palettes/15.gbapal"),
};

const u16 gTilesetPalettes_Sinnoh_Building[][16] =
{
    INCBIN_U16("data/tilesets/primary/building/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/primary/building/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/primary/building/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/primary/building/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/primary/building/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/primary/building/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/primary/building/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/primary/building/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/primary/building/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/primary/building/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/primary/building/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/primary/building/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/primary/building/palettes/12.gbapal"),
    INCBIN_U16("data/tilesets/primary/building/palettes/13.gbapal"),
    INCBIN_U16("data/tilesets/primary/building/palettes/14.gbapal"),
    INCBIN_U16("data/tilesets/primary/building/palettes/15.gbapal"),
};

const u32 gTilesetTiles_Sinnoh_Petalburg[] = INCBIN_U32("data/tilesets/sinnoh/secondary/petalburg/tiles.4bpp.fastSmol");
const u16 gTilesetPalettes_Sinnoh_Petalburg[][16] =
{
    INCBIN_U16("data/tilesets/sinnoh/secondary/petalburg/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/petalburg/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/petalburg/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/petalburg/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/petalburg/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/petalburg/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/petalburg/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/petalburg/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/petalburg/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/petalburg/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/petalburg/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/petalburg/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/petalburg/palettes/12.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/petalburg/palettes/13.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/petalburg/palettes/14.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/petalburg/palettes/15.gbapal"),
};

const u32 gTilesetTiles_Sinnoh_Rustboro[] = INCBIN_U32("data/tilesets/sinnoh/secondary/rustboro/tiles.4bpp.fastSmol");
const u16 gTilesetPalettes_Sinnoh_Rustboro[][16] =
{
    INCBIN_U16("data/tilesets/sinnoh/secondary/rustboro/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/rustboro/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/rustboro/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/rustboro/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/rustboro/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/rustboro/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/rustboro/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/rustboro/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/rustboro/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/rustboro/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/rustboro/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/rustboro/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/rustboro/palettes/12.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/rustboro/palettes/13.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/rustboro/palettes/14.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/rustboro/palettes/15.gbapal"),
};

const u32 gTilesetTiles_Sinnoh_Jubilife[] = INCBIN_U32("data/tilesets/sinnoh/secondary/jubilife/tiles.4bpp.fastSmol");
const u16 gTilesetPalettes_Sinnoh_Jubilife[][16] =
{
    INCBIN_U16("data/tilesets/sinnoh/secondary/jubilife/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/jubilife/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/jubilife/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/jubilife/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/jubilife/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/jubilife/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/jubilife/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/jubilife/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/jubilife/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/jubilife/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/jubilife/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/jubilife/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/jubilife/palettes/12.gbapal"),
};

const u32 gTilesetTiles_Sinnoh_Mauville[] = INCBIN_U32("data/tilesets/sinnoh/secondary/mauville/tiles.4bpp.fastSmol");
const u16 gTilesetPalettes_Sinnoh_Mauville[][16] =
{
    INCBIN_U16("data/tilesets/sinnoh/secondary/mauville/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/mauville/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/mauville/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/mauville/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/mauville/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/mauville/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/mauville/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/mauville/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/mauville/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/mauville/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/mauville/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/mauville/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/mauville/palettes/12.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/mauville/palettes/13.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/mauville/palettes/14.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/mauville/palettes/15.gbapal"),
};

const u32 gTilesetTiles_Sinnoh_Hearthome[] = INCBIN_U32("data/tilesets/sinnoh/secondary/hearthome/tiles.4bpp.fastSmol");
const u16 gTilesetPalettes_Sinnoh_Hearthome[][16] =
{
    INCBIN_U16("data/tilesets/sinnoh/secondary/hearthome/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/hearthome/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/hearthome/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/hearthome/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/hearthome/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/hearthome/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/hearthome/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/hearthome/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/hearthome/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/hearthome/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/hearthome/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/hearthome/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/hearthome/palettes/12.gbapal"),
};

const u32 gTilesetTiles_Sinnoh_Celestic[] = INCBIN_U32("data/tilesets/sinnoh/secondary/celestic/tiles.4bpp.fastSmol");
const u16 gTilesetPalettes_Sinnoh_Celestic[][16] =
{
    INCBIN_U16("data/tilesets/sinnoh/secondary/celestic/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/celestic/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/celestic/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/celestic/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/celestic/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/celestic/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/celestic/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/celestic/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/celestic/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/celestic/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/celestic/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/celestic/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/celestic/palettes/12.gbapal"),
};

const u32 gTilesetTiles_Sinnoh_Veilstone[] = INCBIN_U32("data/tilesets/sinnoh/secondary/veilstone/tiles.4bpp.fastSmol");
const u16 gTilesetPalettes_Sinnoh_Veilstone[][16] =
{
    INCBIN_U16("data/tilesets/sinnoh/secondary/veilstone/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/veilstone/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/veilstone/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/veilstone/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/veilstone/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/veilstone/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/veilstone/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/veilstone/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/veilstone/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/veilstone/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/veilstone/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/veilstone/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/veilstone/palettes/12.gbapal"),
};

const u32 gTilesetTiles_Sinnoh_Lilycove[] = INCBIN_U32("data/tilesets/sinnoh/secondary/lilycove/tiles.4bpp.fastSmol");
const u16 gTilesetPalettes_Sinnoh_Lilycove[][16] =
{
    INCBIN_U16("data/tilesets/sinnoh/secondary/lilycove/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lilycove/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lilycove/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lilycove/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lilycove/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lilycove/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lilycove/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lilycove/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lilycove/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lilycove/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lilycove/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lilycove/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lilycove/palettes/12.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lilycove/palettes/13.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lilycove/palettes/14.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lilycove/palettes/15.gbapal"),
};

const u32 gTilesetTiles_Sinnoh_Canalave[] = INCBIN_U32("data/tilesets/sinnoh/secondary/canalave/tiles.4bpp.fastSmol");
const u16 gTilesetPalettes_Sinnoh_Canalave[][16] =
{
    INCBIN_U16("data/tilesets/sinnoh/secondary/canalave/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/canalave/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/canalave/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/canalave/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/canalave/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/canalave/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/canalave/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/canalave/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/canalave/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/canalave/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/canalave/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/canalave/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/canalave/palettes/12.gbapal"),
};

const u32 gTilesetTiles_Sinnoh_Snowpoint[] = INCBIN_U32("data/tilesets/sinnoh/secondary/snowpoint/tiles.4bpp.fastSmol");
const u16 gTilesetPalettes_Sinnoh_Snowpoint[][16] =
{
    INCBIN_U16("data/tilesets/sinnoh/secondary/snowpoint/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/snowpoint/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/snowpoint/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/snowpoint/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/snowpoint/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/snowpoint/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/snowpoint/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/snowpoint/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/snowpoint/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/snowpoint/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/snowpoint/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/snowpoint/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/snowpoint/palettes/12.gbapal"),
};

const u32 gTilesetTiles_Sinnoh_Sunnyshore[] = INCBIN_U32("data/tilesets/sinnoh/secondary/sunnyshore/tiles.4bpp.fastSmol");
const u16 gTilesetPalettes_Sinnoh_Sunnyshore[][16] =
{
    INCBIN_U16("data/tilesets/sinnoh/secondary/sunnyshore/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/sunnyshore/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/sunnyshore/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/sunnyshore/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/sunnyshore/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/sunnyshore/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/sunnyshore/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/sunnyshore/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/sunnyshore/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/sunnyshore/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/sunnyshore/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/sunnyshore/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/sunnyshore/palettes/12.gbapal"),
};

const u32 gTilesetTiles_Sinnoh_EverGrande[] = INCBIN_U32("data/tilesets/sinnoh/secondary/ever_grande/tiles.4bpp.fastSmol");
const u16 gTilesetPalettes_Sinnoh_EverGrande[][16] =
{
    INCBIN_U16("data/tilesets/sinnoh/secondary/ever_grande/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/ever_grande/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/ever_grande/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/ever_grande/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/ever_grande/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/ever_grande/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/ever_grande/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/ever_grande/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/ever_grande/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/ever_grande/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/ever_grande/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/ever_grande/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/ever_grande/palettes/12.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/ever_grande/palettes/13.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/ever_grande/palettes/14.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/ever_grande/palettes/15.gbapal"),
};

const u32 gTilesetTiles_Sinnoh_Valor[] = INCBIN_U32("data/tilesets/sinnoh/secondary/valor/tiles.4bpp.fastSmol");
const u16 gTilesetPalettes_Sinnoh_Valor[][16] =
{
    INCBIN_U16("data/tilesets/sinnoh/secondary/valor/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/valor/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/valor/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/valor/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/valor/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/valor/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/valor/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/valor/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/valor/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/valor/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/valor/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/valor/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/valor/palettes/12.gbapal"),
};

const u32 gTilesetTiles_Sinnoh_Lavaridge[] = INCBIN_U32("data/tilesets/sinnoh/secondary/lavaridge/tiles.4bpp.fastSmol");
const u16 gTilesetPalettes_Sinnoh_Lavaridge[][16] =
{
    INCBIN_U16("data/tilesets/sinnoh/secondary/lavaridge/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lavaridge/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lavaridge/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lavaridge/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lavaridge/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lavaridge/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lavaridge/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lavaridge/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lavaridge/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lavaridge/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lavaridge/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lavaridge/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lavaridge/palettes/12.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lavaridge/palettes/13.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lavaridge/palettes/14.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/lavaridge/palettes/15.gbapal"),
};

const u32 gTilesetTiles_Sinnoh_Pasos[] = INCBIN_U32("data/tilesets/sinnoh/secondary/pasos/tiles.4bpp.fastSmol");
const u16 gTilesetPalettes_Sinnoh_Pasos[][16] =
{
    INCBIN_U16("data/tilesets/sinnoh/secondary/pasos/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/pasos/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/pasos/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/pasos/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/pasos/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/pasos/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/pasos/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/pasos/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/pasos/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/pasos/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/pasos/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/pasos/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/sinnoh/secondary/pasos/palettes/12.gbapal"),
};
